### ISSUE TITLE
theme_boost (2017051500)

### ISSUE THREAD

**Issue by pedrohstaub** [willianmano/moodle-theme_moove#100]
Estou enfrentando esse problema na instalação do tema, poderiam me ajudar?

I'm facing this problem during the theme instalation, could someone help me?

![moodle_error](https://user-images.githubusercontent.com/18274435/42336597-874bc2a0-805a-11e8-9000-0d0383968ecb.PNG)

**Comment by LilianaVale** [comment]
Parece que faltam os arquivos na pasta theme/moove

**Comment by pedrohstaub** [comment]
Obrigado Liliana, tem alguma sugestão do que pode ser feito? Já tentei baixar o arquivo novamente pensando ser este o problema, porém não resolveu. Já estou a algum tempo pesquisando sobre isso porém não encontrei nada, a versão do moodle que estou utilizando é 3.4.

**Comment by giselebrugger** [comment]
Pedro e vc tem certeza que baixou a versão certa para o moodle 3.4 e não para o moodle 3.5 ou versões mais antigas?
Confira antes https://moodle.org/plugins/pluginversions.php?plugin=theme_moove

**Comment by pedrohstaub** [comment]
Obrigado Gisele, mas baixei e versão 3.4, aliás, conforme falei acima, baixei 2 vezes pra ter certeza que não havia corrompido nada, até porque achei estranho estar dando aquele erro, mas depois de pesquisar bastante não encontrei nada relacionado a isto. Tem mais alguma dica?

**Comment by giselebrugger** [comment]
@pedrohstaub vc tem certeza que seu moodle é 3.4 ?
Porque tbem tenho um moodle 3.4 a versão dele é 20180308
E o seu esta mostrando versão 2017102500 e que parece ser versão antes da 3.2 quando ainda não usávamos o boost como tema padrão. Dá uma conferida no seu moodle em ../moodle/admin/index.php?cache=1

**Comment by giselebrugger** [comment]
O moodle 3.4 foi lançado em novembro de 2017. Veja que seu moodle é de 25/10/2017

**Comment by pedrohstaub** [comment]
Não estou na mesma versão que a sua, porém estou numa versão de 2018.
Vou tentar atualizar para esta versão, se funcionar volto postar aqui.

![vmod](https://user-images.githubusercontent.com/18274435/42460811-38c238a8-8375-11e8-8805-fe1c1e4d9876.PNG)

**Comment by pedrohstaub** [comment]
Talvez ja fuja um pouco do tema deste post, mas ao atualizar apresenta erro "check_unoconv_version", mesmo erro que apresentava quando tento atualizar para versão 3.5, tem alguma ideia do que possa ser?

**Comment by giselebrugger** [comment]
@pedrohstaub https://docs.moodle.org/34/en/Universal_Office_Converter_(unoconv)

**Comment by pedrohstaub** [comment]
@giselebrugger ja fiz os procedimentos desse post porém não funcionou, estive semanas pesquisando sobre pra ver o que poderia ser, ai resolvi deixar na 3.4 por enquanto. Agora me deparo com esse problema novamente :( 

Pode ter a ver com a versão do SO do server? Estou hospedando o moodle em um ubuntu server 14.04.

**Comment by willianmano** [comment]
@pedrohstaub este erro está informando que os requisitos mínimos para o tema não estão satisfeitos, ou seja, você precisa do tema Boost naquela versão ou superior.

Vou encerrar essa issue por não se tratar de um erro do tema .
