### ISSUE TITLE
Slider - responsive

### ISSUE THREAD

**Issue by LilianaVale** [willianmano/moodle-theme_moove#101]
Olá, No slider da home, quando utilizo versões para dispositivos menores que 900 px, o title e caption desaparecem. Percebi que tem a ver com display:none, mas não consegui encontrar onde mexer para resolver. 

Hello, In the home slider, when I use versions for devices smaller than 900 px, the title and caption disappear. I noticed that it has to do with display: none, but I could not find where to change to solve it.

**Comment by rafaelpbaptista** [comment]
Up

**Comment by lukacspeter** [comment]
To show title and caption all the time, youll need to delete bootstrap's attributes in slideshow.mustache. 
Change this line:

`<div class="carousel-caption d-none d-md-block animated fadeInRightBig">`

to this line:
` <div class="carousel-caption animated fadeInRightBig">`

**Comment by willianmano** [comment]
@LilianaVale isso foi resolvido na versão mais atual do tema, por favor atualize o seu tema.

**Comment by LilianaVale** [comment]
Obrigada!!
