### ISSUE TITLE
Activity navigation not visible on Quizzes

### ISSUE THREAD

**Issue by maetxabe** [willianmano/moodle-theme_moove#102]
[Activity navigation](https://moodle.com/moodle-releases/experience-faster-intuitive-navigation-activities-moodle-3-4/) link is not visible on Quizzes
Moodle 3.5+
Moove 2.3.3

**Comment by giselebrugger** [comment]
see your custumizacion css
is color link 
here is normal
![questionario de conhecimento](https://user-images.githubusercontent.com/5620195/42592882-54ed4d26-8521-11e8-8397-8592fc9ff80a.jpg)

**Comment by maetxabe** [comment]
That is the quiz navigation. But on the bottom it should appear the link to go to the next activity.

**Comment by giselebrugger** [comment]
Here is normal 
code css is:

button, html [type="button"], [type="reset"], [type="submit"] {
    -webkit-appearance: button;
    background-color: #f60;
    color: #fff;
}

![questionario de conhecimento](https://user-images.githubusercontent.com/5620195/42639190-ccb6f286-85c5-11e8-8d79-ed5e3209563d.jpg)

**Comment by maetxabe** [comment]
That is next page button. If you change the theme to Boost you will see the next activity link:
![test_-_2018-07-13_12 45 44](https://user-images.githubusercontent.com/40593125/42687966-d6927ce6-869a-11e8-8b6c-37d69b0afd64.png)

**Comment by agrosupdijon** [comment]
Hi,

We have the same problem "Activity navigation" link is not visible on Quizzes.
Moodle 3.4.1
Moove : 2.1.1

Thanks for your help.

**Comment by janisfiss** [comment]
We are still experiencing this issue too.

**Comment by ihyaksm** [comment]
Hi, 
we have problem , quiz navigation not visible when Safe Exam Browser **enabled**
moodle 3.6.3+
moove 3.6.4
![image](https://user-images.githubusercontent.com/50066179/56858855-55b8a880-69ab-11e9-8f71-85a291a336f2.png)

**Comment by agrosupdijon** [comment]
Hi, 

Thanks for your answer and the correction. 
Is it possible for the 3.5.5 moodle for example ? 
Thanks for your answer. 

PS : merci de bien vouloir noter ma nouvelle adresse mail : [ mailto:nathalie.de-filippo@agrosupdijon.fr | nathalie.de-filippo@agrosupdijon.fr ] 

Cordialement, 

Nathalie DE FILIPPO 

Chef de projet web du Service Cnerta-Web 
AgroSup Dijon - Direction des Systèmes d'Information - Bât. Grands-Champs 
26, bd Dr Petitjean -BP 87999 - 21079 Dijon Cedex 
T él : 03.80.77.29.02 
[ https://partage.agrosupdijon.fr/agrosupdijon.fr%20 | agrosupdijon.fr ] 
[ https://partage.agrosupdijon.fr/cnerta-web.fr ] 



De: "willianmano/moodle-theme_moove" <reply@reply.github.com> 
À: "nathalie de-filippo" <nathalie.de-filippo@agrosupdijon.fr>, "willianmano/moodle-theme_moove" <moodle-theme_moove@noreply.github.com> 
Cc: "NATHALIE DEFILIPPO" <nathalie.defilippo@educagri.fr>, "Comment" <comment@noreply.github.com> 
Envoyé: Dimanche 28 Avril 2019 06:51:53 
Objet: Re: [willianmano/moodle-theme_moove] Activity navigation not visible on Quizzes (#102) 

Hi, 
we have problem , quiz navigation not visible when Safe Exam Browser enabled 
moodle 3.6.3+ 
moove 3.6.4 
[ https://user-images.githubusercontent.com/50066179/56858855-55b8a880-69ab-11e9-8f71-85a291a336f2.png ]

**Comment by cb526** [comment]
Just to report that this issue is still present in Moodle 3.6.4 (Plugin version 3.6.4 (2019022800)).

**Comment by willianmano** [comment]
I just updated the theme with a new version solving this.

**Comment by agrosupdijon** [comment]
Hi, 

Thank you very much for your update. 
Regards, 
Nathalie 

Cordialement, 

Nathalie DE FILIPPO 

Chef de projet web du Service Cnerta-Web 
AgroSup Dijon - Direction des Systèmes d'Information - Bât. Grands-Champs 
26, bd Dr Petitjean -BP 87999 - 21079 Dijon Cedex 
T él : 03.80.77.29.02 
[ https://partage.agrosupdijon.fr/agrosupdijon.fr%20 | agrosupdijon.fr ] 
[ https://partage.agrosupdijon.fr/cnerta-web.fr ] 



De: "willianmano/moodle-theme_moove" <reply@reply.github.com> 
À: "Nathalie DE FILIPPO" <nathalie.de-filippo@agrosupdijon.fr>, "willianmano/moodle-theme_moove" <moodle-theme_moove@noreply.github.com> 
Cc: "NATHALIE DEFILIPPO" <nathalie.defilippo@educagri.fr>, "Comment" <comment@noreply.github.com> 
Envoyé: Vendredi 17 Avril 2020 02:05:13 
Objet: Re: [willianmano/moodle-theme_moove] Activity navigation not visible on Quizzes (#102) 


I just updated the theme with a new version solving this.
