### ISSUE TITLE
Stay in touch

### ISSUE THREAD

**Issue by jmd87fr** [willianmano/moodle-theme_moove#103]
Hi William,
I installed your theme in a customer moodle. He con't want the text : ''stay in touch' in the footer. 
can you tell me which file I should modify so that this text is no longer displayed? 
Hope to read you
_**I'm sad for Seleção :-( I would have liked a half with your team._

**Comment by sean1746** [comment]
Not sure if this helps, but you can changing the wording of 'stay in touch' to something different through Moodle's Language Customisation tool. 

Select theme_moove.php from the component filter, and modify the string 'stayintouch' to what you want to say instead.

https://docs.moodle.org/35/en/Language_customisation

**Comment by jmd87fr** [comment]
OK I mooved texte by a dot  OK :-)

**Comment by toinkhimura** [comment]
> 
> 
> Hi William,
> I installed your theme in a customer moodle. He con't want the text : ''stay in touch' in the footer.
> can you tell me which file I should modify so that this text is no longer displayed?
> Hope to read you
> _**I'm sad for Seleção :-( I would have liked a half with your team._

you can put css in Raw initial SCSS and Raw SCSS
setting>appearance > theme > moove > advanced like this :

#top-footer h3 {
visibility: hidden;
}

**Comment by Rintoh300** [comment]
haii william, can you help me, i use theme moove in moomdle, and use server localhost,  i want change code you for 
which are desired, do you tell me how to change code use server localhost? thank you
