### ISSUE TITLE
icone "mycourses" em tela pequena

### ISSUE THREAD

**Issue by rpolesi** [willianmano/moodle-theme_moove#110]
Olá @willianmano , observei que na mudança do Moodle 3.4 para o 3.5 o icone de "mycourses", só aparece para telas maores que 750px.
Para telas menores que isso está oculto.
Gostaria de uma das soluções:
01. ou simplesmente voltar, indiferente tamanho da tela;
02. ou deixar exibindo para todos, com opção de esconder para quem deseja;
03. ou esconder para todos, com opção de exibir para quem deseja;
---
Talvez um script CSS para exibir esse ícone mesmo em telas pequenas.

Suponho que um dos objetivos de ocultar para telas pequenas, seria para instituições que o aluno está matriculado em muitas disciplinas, de tal maneira, que a exibição desses ficaria muito ruim em telas pequenas ficando mais adequado o acesso somente pelo painel "/my"
Mas para mim, onde meus alunos estão inscritos em no máximo 05 disciplinas simultaneamente esse icone no mene ajuda muito na navegação.

**Comment by willianmano** [comment]
Essa modificação foi feita para melhorar a experiência de TODOS os usuários de TODOS os sites Moodle que usam o tema. Por este motivo sua issue não pode ser atendida.
