### ISSUE TITLE
Arquivos de resumo do curso não está plenamente responsivo

### ISSUE THREAD

**Issue by rpolesi** [willianmano/moodle-theme_moove#112]
Na configuração de cursos tem o campo "Arquivos de resumo do curso", onde se pode inserir uma imagem. Por padrão, se não for inserido uma imagem, o Moove automaticamente randoniza uma imagem genérica. Isso é bom.
Vendo no desktop, observei que a imagem tem o tamanho de 385x150.
Então preparei imagens com esse tamanho.
Para o desktop e algumas telas de celular esse tamanho ficou ótimo.
Mas para outras telas a imagem fica cortada nas laterais, em vez de ser responsiva.
Visão no desktop: [http://prntscr.com/kfsfaq]
visão no Motorola: [http://prntscr.com/kfsfr5]
Observe como no Motorola fica cortado nas laterais a mesma imagem.

**Comment by rafaelpbaptista** [comment]
Up

**Comment by carinnacostta** [comment]
Olá pessoal, boa tarde! Espero que vocês estejam bem.

Estou com um problema em relação a imagem do background do tema Moove. No desktop ele aparece da forma adequada, mas no celular, a imagem fica muito pequena e é totalmente cortada na horizontal. 

Vocês podem me ajudar a resolver esse problema?

Já tentei o código, mas não funcionou: (joguei ele na parte que tem no próprio tema em administração do site)

@media (max-width: 767px)
#page-site-index.notloggedin #page-header {
    padding-top: 70px;
    margin-top: 0;
    background-color: #fff;
    min-height: inherit;
} 

Abaixo mando o link:
Celular: https://prnt.sc/tzrokd
Desktop: https://prnt.sc/tzrp50

Grata,
Carina.
