### ISSUE TITLE
quiz navigation 

### ISSUE THREAD

**Issue by janisfiss** [willianmano/moodle-theme_moove#113]
Having the quiz navigation on the right means that there are now three columns for a quiz. The main quiz area where the content and questions is far too narrow. 
I'm sure you have a good reason for having moved the navigation to the right but is there any way to have an option to keep it to the left?

**Comment by willianmano** [comment]
In this new vision of Boost theme and the themes based on it, the blocks are placed on the right side.

**Comment by janisfiss** [comment]
I know this is closed but perhaps you would reconsider. In Boost, the quiz navigation block shows under the quiz questions on a quiz page. rather than beside the questions when viewed on an iPad. Curiously. this also happens in Moove on Android phones but not on iPads. Students just can't see the whole question or answer comfortably on iPad if the theme is set to Moove.
