### ISSUE TITLE
Course section sub menu is not display correctly when in responsive (mobile)

### ISSUE THREAD

**Issue by sobirin90** [willianmano/moodle-theme_moove#114]
As you can see in the first screenshot is when it's on full screen which looks okay.
![course_section](https://user-images.githubusercontent.com/13135604/43936248-5847ec08-9c8a-11e8-891d-6c384b4f1a12.jpg)

Below is the screenshot after its on responsive mode (Chrome).
![course_section_bug](https://user-images.githubusercontent.com/13135604/43936273-6f2c0a80-9c8a-11e8-8fb3-7647372115fb.jpg)

The course section menu is totally missing. Not to mention user also have to scroll to the right at the side menu icons when they open it to view the wording. I personally like the view to be much wider to accommodate the description of the icons. Thank you.

**Comment by willianmano** [comment]
Hi @sobirin90 I fixed the menu in mobile mode. About the course sections, this is the expected behavior.
