### ISSUE TITLE
How to add Courses tab in dashboard

### ISSUE THREAD

**Issue by adepuv** [willianmano/moodle-theme_moove#115]
Hi,

1.We have tried to add the course overview tab on dashboard of Moodle LMS but unable to make visible 
   this course overview page on admin and user end page.
2. Moodle home main page also we are not able to display the available  courses.

 kindly help me to add this page on admin and user dashboard page.
 
![image](https://user-images.githubusercontent.com/42275494/43990096-407c5c22-9d74-11e8-9ddd-cb06c3202a27.png)
 
But when i see the same in this below screen shot i can see course overview tab with upcoming courses and status of all courses 

![image](https://user-images.githubusercontent.com/42275494/43990107-7a7acc88-9d74-11e8-8404-0b100a0015d0.png)

![image](https://user-images.githubusercontent.com/42275494/43990129-cba4341e-9d74-11e8-83af-8301db917272.png)

**Comment by willianmano** [comment]
@adepuv These courses are only presented in the frontpage, not in the dashboard page.

You can configure the frontpage in the frontpage settings. "Site Administration -> Frontpage settings"
