### ISSUE TITLE
Left sidebar My courses doesn't show more courses

### ISSUE THREAD

**Issue by SubjectXXX** [willianmano/moodle-theme_moove#120]
My teachers have more course listed that theme shows on left sidebar, thus creating More.. link, but if pressed, page refreshes and nothing else happens, there is still first n courses shown.

**Comment by rafaelpbaptista** [comment]
Up

**Comment by janisfiss** [comment]
We have experienced the same problem.

**Comment by SubjectXXX** [comment]
Too bad dev went inactive, it was really nice theme.
Up..

**Comment by SubjectXXX** [comment]
After some more pondering, Moodle core setting can set number of items in left sidebar, setting it high enough avoids showing not working More.. link.
    Dashboard -> Site administration -> Appearance -> Navigation -> navcourselimit

**Comment by raramuridesign** [comment]
@SubjectXXX is this still an issue your side after updating the navlimit? or is there anything else to take note of?
