### ISSUE TITLE
Desabilitar foto do professor em course card?

### ISSUE THREAD

**Issue by glaubermenezes** [willianmano/moodle-theme_moove#121]
Percebi que a atualização do Thema, passou a publicar a foto do professor na apresentação do curso (course card).

Como desabilitar este recurso?!

**Comment by ricpelo** [comment]
Or, at least, reduce the size. The professor photo is too big!
![2018-09-14-204003_1280x1005_scrot](https://user-images.githubusercontent.com/616169/45568940-6114f480-b85e-11e8-9c89-258fba82410b.png)

**Comment by glaubermenezes** [comment]
O meu ainda ficou pior.

![image](https://user-images.githubusercontent.com/43275397/45901726-586e7200-bdba-11e8-9a77-64ecf9891ee7.png)

**Comment by willianmano** [comment]
@glaubermenezes @ricpelo De fato a versão mais nova do moodle mudou alguns seletores css. Eu resolvi o problema na versão mais atual do tema disponível para o Moodle 3.6
