### ISSUE TITLE
Insufficient width for calendar event modal

### ISSUE THREAD

**Issue by danielneis** [willianmano/moodle-theme_moove#122]
No arquivo:

scss/moove/_responsive.scss

Tem a definiçao:
  8 @media (min-width: 576px) {
  9   .modal-dialog {
 10     max-width: 540px;
 11   }
 12 }

Esse tamanho não é suficiente para o elemento de data de duração do calendário, por exemplo.
Sugestão é colocar esse valor em 50% ou um outro valor variável.

**Comment by rafaelpbaptista** [comment]
Up

**Comment by SubjectXXX** [comment]
Would help if ticket would be in english. Maybe some other user would try to help solve the problem..

**Comment by willianmano** [comment]
@danielneis Eu mudei para 50%. Infelizmente não sei como simular isso, da uma testada ai pra ver se agora está bom. Valeu.
