### ISSUE TITLE
Protect login form from CSRF attacks

### ISSUE THREAD

**Issue by Mihailoff** [willianmano/moodle-theme_moove#123]
Hello @willianmano Moove has a login form on the homepage that is vulnerable to CSRF attacks (https://www.owasp.org/index.php/Cross-Site_Request_Forgery_(CSRF)_Prevention_Cheat_Sheet).

Possible remedy https://docs.moodle.org/dev/Security:Cross-site_request_forgery

**Comment by willianmano** [comment]
@Mihailoff thanks for reporting. I already solved this issue. @SubjectXXX
