### ISSUE TITLE
Problem with Javascript security

### ISSUE THREAD

**Issue by gigadep** [willianmano/moodle-theme_moove#128]
Hello willian Mano,
When I use this theme with javascript security in tests, I can't see the block on the right with the timer and the number of questions during the test.

**Comment by hmgp** [comment]
Hi! Any solution to this case?
I can confirm this happens and add another situation, with browser security if you have "Block concurrent connections" configured, in a review state you cannot unblock an attempt, which is a major problem. Students get stuck and loose the attempt. 

Is there a solution to this?

Thank you.
