### ISSUE TITLE
Not Compatible with 3.3.2

### ISSUE THREAD

**Issue by janeofalltrades** [willianmano/moodle-theme_moove#13]
I upgraded my staging site to 3.3.2 today. Upon attempting to select the Moove theme plugin in 3.3.2 I received the following error:

> Error reading from database

My webhosting company had to roll back the upgrade in order to solve the issue.

**Comment by willianmano** [comment]
@janeofalltrades I made a bunch of updates. Please, test the new version.

**Comment by Sardorjon** [comment]
I have also latest version of moodle, could you help me install moove.

**Comment by willianmano** [comment]
@Sardorjon have you solved this issue? You can talk directly with me via gTalk. My email is willianmanoaraujo@gmail.com
