### ISSUE TITLE
Problemas ao logar com o tema habilitado

### ISSUE THREAD

**Issue by tatianilima** [willianmano/moodle-theme_moove#130]
Bom dia! 

Primeiramente parabéns pelo ótimo trabalho! Estou enfrentando um problema quando habilito o tema moove. Quando eu seleciono qualquer outro tema o login funciona, porém quando ativo o tema Moove o login e senha deixa de funcionar.
Com o tema Moove eu recebo a mensagem: "Nome de usuário ou senha errados. Por favor tente outra vez."
Com os outros temas o login e senha funcionam e acessam normalmente.
Estou utlizando o moodle 3.4

Grata
Tatiani

**Comment by willianmano** [comment]
@tatianilima Isso foi resolvido para a versão 3.5 do Moodle. Foi uma atualização feita por eles que eu tive de adaptar no tema. Lembrando que eu só dou suporte para as versões mais recentes do tema, portanto este problema está sanado para o Moodle 3.5 e superiores,
