### ISSUE TITLE
Login box not align after oauth login button appear

### ISSUE THREAD

**Issue by hafriz** [willianmano/moodle-theme_moove#134]
Hi,

any idea how to make the two box login instruction align? it seems not align between two boxes
![image](https://user-images.githubusercontent.com/1394343/50570217-d7ad1200-0dbb-11e9-9219-0d3948459f12.png)

**Comment by willianmano** [comment]
@hafriz Please, send your moodle and theme versions when reporting an issue.

**Comment by hafriz** [comment]
> @hafriz Please, send your moodle and theme versions when reporting an issue.

hi, i'm using moodle 3.5 with moove version 2.3.9
