### ISSUE TITLE
Password not recognised

### ISSUE THREAD

**Issue by ashtonej** [willianmano/moodle-theme_moove#135]
I am using moodle 3.4.6+

I installed Moove version 2017111300

I logged out of moodle and then tried to log in again. Moove did not recognised guest access or my admin password. I requested a pw reset. The reset email came and I entered a new PW then logged out again. When I tried to log in again, the password was not recognised again.

Eventually I went back to the Boost theme and now everything works fine.

What did I do wrong? Did I install the wrong Moove version?

**Comment by SubjectXXX** [comment]
You didnt do anything wrong. Theme wasnt updated for latest Moodles security updates regarding login tokens and stuff. 

For now, workaround is, to add this line
$CFG->disablelogintoken = true;
to you config.php file

**Comment by hrpatel** [comment]
FYI, this commit (latest version) fixes the login token issue:

https://github.com/willianmano/moodle-theme_moove/commit/7aeedd8afe712f9773dfa322d119a33a2609751c
