### ISSUE TITLE
Custom menu items are too close when using Moove theme

### ISSUE THREAD

**Issue by Lior79** [willianmano/moodle-theme_moove#137]
When using the Moove theme, the Custom items (header menu) of the site are too close (can't set a space between them):
![image](https://user-images.githubusercontent.com/6652995/51347233-33f47f00-1aa8-11e9-9ded-fb5ed82dd105.png)

Vs boost theme:
![image](https://user-images.githubusercontent.com/6652995/51347302-5eded300-1aa8-11e9-86ee-143f282fd795.png)

**Comment by willianmano** [comment]
@Lior79 solved. Thanks for report this.
