### ISSUE TITLE
Cannot add any element to course - button is not work (or active as link)

### ISSUE THREAD

**Issue by dngv** [willianmano/moodle-theme_moove#14]
#![image](https://user-images.githubusercontent.com/32137822/30653793-bafc6e82-9e34-11e7-879d-97db52440b73.png)
![image](https://user-images.githubusercontent.com/32137822/30653950-36115c54-9e35-11e7-9b00-e7b7337e5819.png)
Moodle 3.3.2+ (Build: 20170915)
PHP 7.0, Mysql

**Comment by willianmano** [comment]
@dngv This is not a problem of the theme. But, I made a bunch of updates. Please, test the new version.
