### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by Gorillab1scuit** [willianmano/moodle-theme_moove#141]
I'm missing a lot of basic icons for gears and such... not a super problem for regular users but is still a little confusing on the admin side.

<img width="176" alt="moove_icons_missing" src="https://user-images.githubusercontent.com/36890827/52490054-e0022500-2b91-11e9-9bd0-1883c1f8f3b1.png">

**Comment by willianmano** [comment]
This is probably a conflict with BBB. I solved it. Thanks for report this.
