### ISSUE TITLE
Line break on the home page

### ISSUE THREAD

**Issue by Alandette** [willianmano/moodle-theme_moove#149]
Hello William
I request your collaboration to resolve a detail in the design of the home page.

We are showing only the login box and the background image, we are not using any other option such as marketing.

The problem is that between the background image and the footer there is a line break that affects the design, you can see in the following image.

![image](https://user-images.githubusercontent.com/25472104/53430950-8d13d480-39bd-11e9-8821-3e37b181faab.png)

We have reviewed the templates but we have not located the code that generates that line break, do you have any idea where we can locate the code to eliminate it?

Thank you.

Edwin González

**Comment by willianmano** [comment]
@Alandette this is veeery strange, but the theme doesnt print this line break, this is a moodle problem.
