### ISSUE TITLE
Quiz navigation blocking content on mobile

### ISSUE THREAD

**Issue by diontoradan** [willianmano/moodle-theme_moove#15]
version 1.4.1 : the quiz navigation block still blocking the page, so the student cannot see the questions in mobile (sm / xs), i solve this by adding col-xs-12 and col-sm-12 (through jquery) otherwise it won't work (firefox, chrome).

```
$('body#page-mod-quiz-attempt #page-content div.col-md-3').addClass('col-xs-12 col-sm-12');
$('body#page-mod-quiz-summary #page-content div.col-md-3').addClass('col-xs-12 col-sm-12');
$('body#page-mod-quiz-review #page-content div.col-md-3').addClass('col-xs-12 col-sm-12');
```

**Comment by sebastianxrc** [comment]
Hi, 
Could you tell me where did you add that code?, in which file.

Thanks

**Comment by willianmano** [comment]
@diontoradan @sebastianxrc That was saved on version 1.4.8. Please, update your themes.
