### ISSUE TITLE
Remove section 0 from single section page

### ISSUE THREAD

**Issue by alandete** [willianmano/moodle-theme_moove#150]
Hello William.

I'm trying to hide section 0 in the secondary sections and show it only on the main page of the course, unfortunately I have not managed to locate an id or a class that shows up only in the different sections.

Is there a template that is only shown in the secondary sections of the course where I can include an Id or a class?

The idea is to modify the template to include this identifier that allows us to hide the layer with css, or modify the code so that this section is not shown in the secondary sections.

Thank you in advance for your comments.

Edwin González

**Comment by cb526** [comment]
Hi Edwin,
What do you mean by "secondary sections"?

**Comment by TowerX** [comment]
Hello @Alandette,

Did you manage to find a solution to this? If not, can you provide a better description of what you are trying to achieve so we can help you?

Thanks in advance.

**Comment by benutzer-prog** [comment]
Hello @Alandette,

do you mean the section 0 in all courses?

Kind regards,

Ben

**Comment by christopherm00** [comment]
Ben,
Yes when viewing Single Topics in a course section 0 is still showing in every single one.

Any ideas to only have the Topic selected display?

**Comment by benutzer-prog** [comment]
Hi Chris,

which course format are you currently using?

**Comment by christopherm00** [comment]
Ben, 

We're using Topics Format  with one section per page and Section 0 Shows on every section.

Chris

**Comment by christopherm00** [comment]
I was able to resolve this by modifying the function:
`public function print_single_section_page($course, $sections, $mods, $modnames, $modnamesused, $displaysection) {`

located in 

`theme/moove/classes/format_topics_renderer.php`

I commented out the logic in the if statement that starts around line 70 with:
`if ($thissection->summary or !empty($modinfo->sections[0]) or $this->page->user_is_editing()) {`

I have yet to see any other effect other than section 0 no longer being displayed in the single topic format 

Thanks
Chris
