### ISSUE TITLE
Moodle 3.4 Error login

### ISSUE THREAD

**Issue by upiksaleh** [willianmano/moodle-theme_moove#151]
I use moodle 3.4.7. every time I log in, a login error always appears. but if I use another theme it will work.

**Comment by dim912** [comment]
What is the solution for this issue.

I just tried 'moove' theme. But after then, can not login to moodle. My moodle version is 3.3

**Comment by willianmano** [comment]
@dim912 @upiksaleh Update your moodle and the theme. This issue was solved in the newest versions.
