### ISSUE TITLE
Login - Data privacy and policy footer.

### ISSUE THREAD

**Issue by 96Daniel** [willianmano/moodle-theme_moove#154]
The "privacy and policy" footer in the 2nd login page cause a little overflow.

![immagine](https://user-images.githubusercontent.com/47625157/53723196-752dcc00-3e67-11e9-8a53-facac69394ca.jpg)

**Comment by 96Daniel** [comment]
solved with this css: 
![image](https://user-images.githubusercontent.com/47625157/53724654-99d77300-3e6a-11e9-9680-d4b45f57ff17.png)

but then the footer on the rest of thi site turn like this:

![image](https://user-images.githubusercontent.com/47625157/53724698-b2e02400-3e6a-11e9-8d73-d9c0025666cf.png)

**Comment by willianmano** [comment]
@96Daniel solved. thanks
