### ISSUE TITLE
Hide frontpage marketing icon?

### ISSUE THREAD

**Issue by 96Daniel** [willianmano/moodle-theme_moove#155]
There isn't an option to hide 1 or 2 marketing icons on frontpage?

**Comment by willianmano** [comment]
@96Daniel You can only hide all the marketing icons

**Comment by 96Daniel** [comment]
I was able to hide it with this css, if someone need it:

### #page-site-index.notloggedin .frontpage-marketing .col-md-3:first-of-type{
display:none!important;}
