### ISSUE TITLE
Uso do fontawesome 5.x.x

### ISSUE THREAD

**Issue by vulmarjunior** [willianmano/moodle-theme_moove#158]
Seria possível atualizar o fontawesome utilizado no tema?
Pois vi que ele apenas consulta a tabela referente a versão 4.7, e os ícones das versões 5.x.x nem todos conseguem funcionar.
Bom trabalho, continue assim,

**Comment by willianmano** [comment]
@vulmarjunior Isso não depende do tema, mas sim do Moodle atualizar o fontawesome do boost.

**Comment by vulmarjunior** [comment]
Obrigado pela resposta. Achei que dependia do tema.

Atenciosamente

Vulmar Junior

Em qui, 2 de mai de 2019 16:59, Willian Mano <notifications@github.com>
escreveu:
