### ISSUE TITLE
Links presetfiles wrong

### ISSUE THREAD

**Issue by kaltokri** [willianmano/moodle-theme_moove#16]
Hi,
 I really like your theme. Great work and a big thank you for your efforts!

In "_Site administration / Appearance / Themes / Moove / General settings / Additional theme preset files_" there is some help text with links "See **Moove presets** for information" and  "see the **Presets repository** for presets that others have shared". Both links doesn't work. That's a shame because it sounds very interresting to me, but I don't know how to use them.

**Comment by willianmano** [comment]
@kaltokri Thank you for your report. I solved it on the newest theme version. Regards.
