### ISSUE TITLE
#Problem with Cover image

### ISSUE THREAD

**Issue by AudeUniv** [willianmano/moodle-theme_moove#160]
Hi everybody, 
I have a problem in my course. I use Moodle 3.5, theme Moove, and i choose Cover image. 
I have an image (jpg/png) in my course summary files, but, in the header of my course, it doesn't appear.
Can you help me?

Thank you.
Aude

**Comment by willianmano** [comment]
@AudeUniv You just need to enable the option in the theme settings. Try to check if your image has any encode problem.
