### ISSUE TITLE
Weird thing on login screen

### ISSUE THREAD

**Issue by ricpelo** [willianmano/moodle-theme_moove#161]
On login screen, some elements are misplaced:

- The instructions panel is not centered.
- The footer isn't at the bottom of the webpage, and it's partially concealed due to the instructions panel.

You can live test on http://agora.iesdonana.org

![screenshot](https://user-images.githubusercontent.com/616169/56572319-2545c880-65bf-11e9-8b28-cd09ce4b1c1c.png)

**Comment by willianmano** [comment]
@ricpelo This issue was solved in the latest theme versions. Please, update your moodle and your theme code.
