### ISSUE TITLE
Responsividade na tela de notas do curso

### ISSUE THREAD

**Issue by djmarcelomendes** [willianmano/moodle-theme_moove#163]
Hoje a tela de notas fica com a tabela curta, evitando a responsividade quando visualizado em uma tela wide. Segue um exemplo abaixo:
![image](https://user-images.githubusercontent.com/2089619/57164766-1cc16f00-6dc3-11e9-9577-f13177da24ac.png)

Para corrigir esse problema, verifiquei que só incluir 3 itens no CSS e a tabela fica responsiva conforme abaixo:
![image](https://user-images.githubusercontent.com/2089619/57164678-e1bf3b80-6dc2-11e9-8995-5c5ba7e33d5a.png)

Segue a inclusão de CSS sem alterar o atual:
`.path-grade-report-grader #region-main{
   display:initial;
}`
`.path-grade-report-grader .gradeparent table{
  width:100%;
}`
`.path-grade-report-grader .gradeparent .user.cell{
  width:100%;
}`

**Comment by willianmano** [comment]
@djmarcelomendes ow meu querido... qd for assim manda um PR. =)
