### ISSUE TITLE
[Sugestion] Option to remove the main page banner and Login form on Nav Header.

### ISSUE THREAD

**Issue by jonnyso** [willianmano/moodle-theme_moove#164]
Hello, this theme is only getting better ! I would like to remove the banner from the main page, I was going to do it with a custom CSS, however if I remove the element I would also remove the login form. It would be nice if it were possible to have the option to put the login form on the nav header, similar to what adaptable theme does, and also the options to remove the main page banner and change its height.

**Comment by willianmano** [comment]
@jonnyso thanks for your suggestion. The version for moodle 3.8 has now an option to hide the login box.
