### ISSUE TITLE
Frontpage components missing

### ISSUE THREAD

**Issue by fred-cardoso** [willianmano/moodle-theme_moove#168]
Hi @willianmano 

Congratulations on the awesome theme. I have a problem on Moodle version 3.7.

For some reason, I can't get the Marketing boxes, neither the Clients/Partners section near the footer to show up. I tested the slider and it's ok.

I attached the configuration page and the frontpage screenshots (ignore the sidebar bug on the configuration page image)

![config_page](https://user-images.githubusercontent.com/32043667/59789238-72939d00-92c5-11e9-9c65-4f3d7bcc4ec1.png)
![frontpage](https://user-images.githubusercontent.com/32043667/59789239-72939d00-92c5-11e9-9711-0024c0e36e7b.png)

Any idea on how can I debug this situation?

Thank you!

**Comment by willianmano** [comment]
Hi @fred-cardoso these items are visible only for guest users. Its like a landing page.

**Comment by sinabilooee** [comment]
it is not visible 

partners, clients , marketing these are not visible even for guests

**Comment by sinabilooee** [comment]
> Hi @fred-cardoso these items are visible only for guest users. Its like a landing page.

it is not visible

partners, clients , marketing these are not visible even for guests
