### ISSUE TITLE
Guest access to moodle site not working

### ISSUE THREAD

**Issue by TobiasBaeumlin** [willianmano/moodle-theme_moove#170]
Hi
I really like the moove theme for moodle but it turns out that I can't use it for now, because it breaks guest access to my moodle site.

When trying to log in as guest user it shows an error: 'Invalid credentials. Please try again!' (German: Ungültige Anmeldedaten. Versuchen Sie es noch einmal!)

When using the classic or boost theme the same does not happen.

Thanks in advance!
Tobias

**Comment by katialeon** [comment]
Hi Tobias try this
https://github.com/dbnschools/moodle-theme_fordson/issues/58

**Comment by MedinaGitHub** [comment]
i have the same mistake

**Comment by smlavoie** [comment]
Same problem here (with 2 Moodle sites). 
I temporarily enable automatic guest login to circumvent the problem.
Thanks to solve this problem.

**Comment by IamLuksha** [comment]
https://github.com/willianmano/moodle-theme_moove/issues/172

**Comment by svishp** [comment]
> Hi
> I really like the moove theme for moodle but it turns out that I can't use it for now, because it breaks guest access to my moodle site.
> 
> When trying to log in as guest user it shows an error: 'Invalid credentials. Please try again!' (German: Ungültige Anmeldedaten. Versuchen Sie es noch einmal!)
> 
> When using the classic or boost theme the same does not happen.
> 
> Thanks in advance!
> Tobias

Could you solve this? I have the same problem

**Comment by IamLuksha** [comment]
> > Hi
> > I really like the moove theme for moodle but it turns out that I can't use it for now, because it breaks guest access to my moodle site.
> > When trying to log in as guest user it shows an error: 'Invalid credentials. Please try again!' (German: Ungültige Anmeldedaten. Versuchen Sie es noch einmal!)
> > When using the classic or boost theme the same does not happen.
> > Thanks in advance!
> > Tobias
> 
> Could you solve this? I have the same problem

https://github.com/willianmano/moodle-theme_moove/pull/174
