### ISSUE TITLE
Version 3.6.4 - cannot expand navigation menu on mobile

### ISSUE THREAD

**Issue by t-penguino** [willianmano/moodle-theme_moove#175]
- [ ] navigation menu does not open on mobile.

Having the menu text labels available is quite important, at the moment only the icons appear.).

The right-hand side block region can be opened and collapsed, can the navigation menu have the same option when viewing on mobile?

![Moove 3 6 4 - mobile menu](https://user-images.githubusercontent.com/54582660/63770522-49971600-c8cd-11e9-9a5e-9eb7b585f53a.png)

**Comment by willianmano** [comment]
@t-penguino this is the expected behavior.
