### ISSUE TITLE
Firefox language change

### ISSUE THREAD

**Issue by JozefKuco** [willianmano/moodle-theme_moove#176]
Hello @willianmano 

we have problem with language box with Firefox browser. Somehow strings disappear on hover when we are changing language (see .gif below). 

**Browser:** Firefox (only, other browsers looks good without this bug)
**Moove version:** 3.7.0 (2019043000)
**Moodle version:** 3.7.1 (20190708)
_This behaviour also appeared on fresh installation of moodle and moove (again, only Firefox)_

![Untitled Project](https://user-images.githubusercontent.com/42066573/64758995-4e4b0380-d536-11e9-9b9c-dbd0624a91d0.gif)

**Comment by The-F4m3** [comment]
Same issue on our Pages.  
Could not find a pure css fix... jet.

**Comment by The-F4m3** [comment]
A colleague of mine gave me the idea.  
We don't know why, but it works:

```css
.dropdown-item:hover, .dropdown-item:focus {
  height: 100%;
}
```

**Comment by JozefKuco** [comment]
> A colleague of mine gave me the idea.
> We don't know why, but it works:
> 
> ```css
> .dropdown-item:hover, .dropdown-item:focus {
>   height: 100%;
> }
> ```

Dont understand how and why, but it works... thanks for posting this fix. Thanks @The-F4m3 

If it does not interrupt something else, it should be official fix @willianmano

**Comment by TowerX** [comment]
@willianmano I tested the possible fix recommended previously and I cannot find any issues with it. It is working as expected.
