### ISSUE TITLE
Moove theme bug with icon caching

### ISSUE THREAD

**Issue by itsguysmiley** [willianmano/moodle-theme_moove#180]
From the forum thread referenced below:

Moove is references fontawesome icons with 'slicon' that do not show up.

The html code is present, but the icon does not get rendered... there's just nothing there at all.

Example:
`<i class="icon fa slicon-settings fa-fw " aria-hidden="true"></i>`

Produces nothing at all...  I've scoured the forums and there's no reference to this bug... 

From Gareth J Barnard @ Moodle (again from the forum thread referenced below)::

"The Moove theme is using the same icon mapping cache as Boost:

$cache = \cache::make('core', 'fontawesomeiconmapping');
therefore when PAC Boost's icon map is overwritten by Moove's and hence the issue.  It should be using its own cached icon map and returned by 'get_icon_name_map()'.  Plus Moove has not additionally catered for the external AJAX calls too.

For more detailed examples, please see this thread on Moodle:

[https://moodle.org/mod/forum/discuss.php?d=391402#p1578113]

**Comment by willianmano** [comment]
@itsguysmiley Thanks for report this. Could you please test the branch master of the theme and see if the error was completely solved?
