### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by cb526** [willianmano/moodle-theme_moove#182]
Incorrect documentation in Moodle led to problems using LTI when using a custom favicon. See https://tracker.moodle.org/browse/MDL-66272 and https://moodle.org/mod/forum/discuss.php?d=371252#p1516474 for technical info on this. Moove is one of the themes affected by this problem.

"It is necessary to fix those themes that overwrite the favicon() method of the core_renderer class so that the favicon() method always returns a moodle_url object."

Thanks

**Comment by willianmano** [comment]
@cb526 have you tested the theme and catch that error?

**Comment by cb526** [comment]
Hi Willian,
Yes I experienced this on Moodle version 3.6 with Moove theme version 3.6.4.
I am unable to use LTIs authentication on to my Moodle site if I upload a custom favicon. When I remove the favicon, the users are authenticated successfully and can access the content.
Thanks.

**Comment by willianmano** [comment]
@cb526 Thanks for your reply. I just uploaded the code fixing it. This update will be available with the moove for the Moodle 3.8.

**Comment by cb526** [comment]
Thanks Willian. Great theme btw!
