### ISSUE TITLE
Plugin para vídeo aula

### ISSUE THREAD

**Issue by BrunoGiubilei** [willianmano/moodle-theme_moove#183]
gostaria de saber se existe algum plugin com compatibilidade com este tema que faça as seguintes funções ou similiar:

- adiciona video do youtube;
- permite monitorar tempo que o aluno viu o video, se concluiu ou não;

**Comment by willianmano** [comment]
@BrunoGiubilei Não sei. Você pode visualizar no repositório de plugins do Moodle.
