### ISSUE TITLE
Turn Editing On button

### ISSUE THREAD

**Issue by dlove2** [willianmano/moodle-theme_moove#184]
Is there code to add a Submit button on the course page?  I'm using Moove theme 3.7.0 on Moodle 3.7: Requesting the "Turn editing on" button on the course page or the collapsible, left-side, Nav menu.  It feels like backtracking to go from having a course-page button to having to go into the Actions menu to turn it on.  There is still a button in the gradebook.

**Comment by willianmano** [comment]
@dlove2 Moodle removed this button with the Boost Theme, I dont know the real reasons, but I am just following the Moodle recommendations and keep hiding the button.
