### ISSUE TITLE
Tour de usuario

### ISSUE THREAD

**Issue by urielvazquez594** [willianmano/moodle-theme_moove#186]
El tour de usuario se descuadra, no se presenta en medio de la página y tampoco selecciona el bloque.

Saludos

**Comment by t-penguino** [comment]
I am also experiencing this issue. There is also some difficultly when referring to elements that are in a collapsed side panel - any way that it can expand when referenced in a tour?

**Comment by willianmano** [comment]
@urielvazquez594 @t-penguino could you please send an image or describe a detailed scenario?

**Comment by dhackinstitute** [comment]
Hi Willian

First off: Great theme! Thank you. Regarding the user tour issue, I have a couple of images to show you.
![user-tour2](https://user-images.githubusercontent.com/30301025/72227541-144e4480-359e-11ea-968a-ae38927fa7ce.png)
![user-tour1](https://user-images.githubusercontent.com/30301025/72227542-14e6db00-359e-11ea-8077-e1c52385373c.png)

**Comment by erinkmelvin** [comment]
Hi Willian, 

I'm experiencing the same issues with User Tours as mentioned above.  Both the blue box and tacking on to the collapsed right side bar.

**Comment by benutzer-prog** [comment]
Hey Willian,

I'm experiencing the same issues with User Tours as mentioned above. Both the blue box and tacking on to the collapsed right side bar.

**Comment by benutzer-prog** [comment]
Any hints or solutions to that? Thank you very much! Hope you are fine.

**Comment by benutzer-prog** [comment]
Hey everybody,

I found a solution. Change to the scss directory and look for the file "_responsive.scss". In the file you have to change the value ".modal-dialog" from "max-width: 50%;" to "width:100%;". Purge the caches and you are done.

Best regards, 

Ben

**Comment by SimonEckmiller** [comment]
Hi, I´ve tried this. I looked here: html/theme/moove/scss/moove/_responsive.scss

There was only one line with the modal-dialog:
I changed it as intended to width100%

@media (min-width: 576px) {
  .modal-dialog {
    width: 100%;
  }

But Even that I reloaded after clearing complete Cache, my moodle don´t take notice from the change.
With F12 i activated the Developer Tools and there I found:
