### ISSUE TITLE
Long activity names cause the layout to break

### ISSUE THREAD

**Issue by berthelemy** [willianmano/moodle-theme_moove#187]
When viewing an activity page (eg. SCORM Package), the links to the previous and next activities can cause the layout to break.

Steps to reproduce:

- Login as admin
- Create a new course
- Add at least 3 activities in the course, be sure the names are quite long texts.
- Go to an activity and scroll down to reach the `Jump To` drop-down

Expected behaviour:

- The next-link and prev-link hyperlinks should be word-wrapped and not overlap each other or the jump-to dropdown
- The links should have only one direction arrow icon

Actual behaviour

- The next-link and prev-link hyperlinks overlap each other or the jump-to dropdown
- The next link and prev-links have two icons indicating left & right hand direction - one is a angle bracket, the other is a triangle. Only one is needed.

This is identical to the now-closed Moodle Boost issue: https://tracker.moodle.org/browse/MDL-64935

**Comment by willianmano** [comment]
@berthelemy thanks for your reply. I will fix it on the next theme version.
