### ISSUE TITLE
Calendar: detailed month view is not available in Moodle 3.7 and 3.8

### ISSUE THREAD

**Issue by valeriia-s** [willianmano/moodle-theme_moove#189]
Hi Willian,

In Moodle 3.5 and 3.6, detailed month view is available in Calendar.
<img width="1043" alt="Moodle_3 5_calendar" src="https://user-images.githubusercontent.com/29231219/72466088-188c8480-378d-11ea-914a-ff4eb98c7dbd.png">

However, in Moodle 3.7 and 3.8 it's not available anymore. The dates with the events are just highlighted by the brand color. The user needs to click the highlighted date to see the events in the pop-up. The screenshots are attached.
<img width="937" alt="Moodle_3 7_Calendar" src="https://user-images.githubusercontent.com/29231219/72466107-1e826580-378d-11ea-9911-1a6557ec4e6f.png">
<img width="798" alt="Moodle_3 7_Calendar2" src="https://user-images.githubusercontent.com/29231219/72466116-2215ec80-378d-11ea-9ae2-d5e324252807.png">

Would you be able to look into it?

Thank you,
Valeriia

**Comment by mycommonplaces** [comment]
I am having this same issue. As you can see, course assignments, etc., partially show up. When I create site-wide or category-wide events they are missing from the detailed month view entirely. Any help?

<img width="1338" alt="Screen Shot 2020-03-31 at 4 33 05 PM" src="https://user-images.githubusercontent.com/47791675/78077189-88aead80-736d-11ea-8f73-6f934ad40b33.png">
