### ISSUE TITLE
Section/activity names overlap with "Jump to" button in Moove navigation

### ISSUE THREAD

**Issue by valeriia-s** [willianmano/moodle-theme_moove#190]
Hi Willian,

The current course section name and "Jump to" button is positioned on the same line as the previous/next course section or activity links.

This is not bad as long as the section/activity links are short. But when the names of these links are long, or when the screen width is narrow, they overlap with the current course section name and the "Jump to" button (see screenshot). 

<img width="1363" alt="2020-01-20_0910" src="https://user-images.githubusercontent.com/29231219/72745494-bce34200-3b64-11ea-9ab8-32d532b9e55e.png">

Would you be able to change the layout of the theme to fix it? It prevents full use of the navigation tools.

Thank you,
Valeriia

**Comment by willianmano** [comment]
Hi @valeriia-s this was solved in the latest version, available for Moodle 3.8
