### ISSUE TITLE
"Certificates" navigation label

### ISSUE THREAD

**Issue by 96Daniel** [willianmano/moodle-theme_moove#192]
Helo all! Is there a way to hide the certificates label from the navigation?

![image](https://user-images.githubusercontent.com/47625157/75157418-5bd6fd00-5714-11ea-89bb-587bbe73a6c4.png)

**Comment by IsraGitHub** [comment]
Hello! Same problem here, Is there a way to hide it?

**Comment by willianmano** [comment]
@96Daniel and @IsraGitHub add this code in 'Raw initial SCSS' field inside the theme settings:

#nav-drawer .list-group .list-group-item[data-key="certificates"] {display:none}
