### ISSUE TITLE
Container and Container-fluid

### ISSUE THREAD

**Issue by yusufyilmaz** [willianmano/moodle-theme_moove#193]
Thank you for this awesome theme. I think one of the best theme for moodle.

I have a question. Is there anyway to make id="page" class as container rather than container-fluid. On wide screen, it really expands too much and this makes reading hard for the students. I would love to have an option for the page width either fluid or not.
Thank you

With <div id="page" class="container-fluid">
![image](https://user-images.githubusercontent.com/4222204/75366298-88ae2000-588c-11ea-8b5d-0697f54c5f3d.png)

<div id="page" class="container"> PS: in this case there is a padding-top 2rem  for container as well.

![image](https://user-images.githubusercontent.com/4222204/75366444-bb581880-588c-11ea-8323-ba869816f746.png)

**Comment by willianmano** [comment]
Hi @yusufyilmaz thank you for your feedback. About the option. This is not possible.
