### ISSUE TITLE
Section sidebar block no space between page and sidebar

### ISSUE THREAD

**Issue by yusufyilmaz** [willianmano/moodle-theme_moove#194]
Hi there,

I have been having an issue with overlapping sidebar on page content. I am attaching screenshot of the sidebar. When sidebar is open, it overlaps with page content. I think some space between page and sidebar would make look really great.

Currently:
![image](https://user-images.githubusercontent.com/4222204/75366791-4b965d80-588d-11ea-8053-7087f49fcb74.png)

After spacing
![image](https://user-images.githubusercontent.com/4222204/75367016-a2039c00-588d-11ea-8473-bc77b9f5ae21.png)

**Comment by yusufyilmaz** [comment]
Hi snack753,
I was not able to solve the issue. I just tweaked the css for screenshot. It needs to be merged into the theme. I just wanted to report  as an issue. The developer of the theme may not see this as an issue.
Best

**Comment by willianmano** [comment]
Thans @yusufyilmaz for report.
