### ISSUE TITLE
Top footer is not sticking to bottom

### ISSUE THREAD

**Issue by yusufyilmaz** [willianmano/moodle-theme_moove#195]
Hi there,

Thank you for your time and help for consideration my latest issues reported previously. I have a last comment on the visual of footer (footer top, stay in touch section). Is there any way to stick the footer bottom when page is short. I am attaching SS when footer is getting upper when page scroll is short.

Thank you!

![image](https://user-images.githubusercontent.com/4222204/75367393-4259c080-588e-11ea-8aec-5f496cb1df4c.png)

**Comment by TowerX** [comment]
What happens when you minimize the right-sidebar custom block? Did you added custom css globally on the theme?
