### ISSUE TITLE
mixed content warning

### ISSUE THREAD

**Issue by snack753** [willianmano/moodle-theme_moove#198]
Dear Willian,
thanks for this great theme. 
Stumbled upon an issue today with a mixed content warning.
The standard footer background image was loaded over http instead of https. This only appears if you do not define a different background image.
As a workaround I just uploaded the background image into the custom footer image section and the mixed content warning is gone.
You might want to change this in your next build.
Cheers,
Kai

**Comment by willianmano** [comment]
Hi @snack753 this is strange, and seems to be a moodle issue. In the theme, I use a core function to get this image: $OUTPUT->image_url('footer-bg', 'theme')
