### ISSUE TITLE
Please make login and user register page more accessible and mobile-friendly

### ISSUE THREAD

**Issue by karnakitab** [willianmano/moodle-theme_moove#201]
When users go to log in, there is no header menu so that the user can go back to homepage. Same thing for the user creation and password forget page.
Further the user creation page is ugly in mobile devices. The same for Boost theme is way better accessible.
Thanks for the good work.

**Comment by willianmano** [comment]
@karnakitab the login page is fully responsive and mobile-friendly. I agree with the register page. I will work on it today.

**Comment by willianmano** [comment]
Closed with d2b91a4b0e3aa5415004f94b73849f3b2ef2caef

**Comment by karnakitab** [comment]
@willianmano Thanks for the pull. Keep up the good work.
