### ISSUE TITLE
How to arrange menu items in nav bar?

### ISSUE THREAD

**Issue by psonHN** [willianmano/moodle-theme_moove#202]
Hi, 
I want to ask a stupid question. How can I rearrange the menu items in left Nav bar in Moove? I.e. Dashboard --> Home  --> My Courses.

Can I eventually merge Dashboard with My Courses?

Thank you for any help.

**Comment by willianmano** [comment]
@psonHN it is not possible to do it withe the them, try this plugin: https://moodle.org/plugins/local_boostnavigation
