### ISSUE TITLE
Side Bar icons desappears in moove theme

### ISSUE THREAD

**Issue by Roussxx** [willianmano/moodle-theme_moove#203]
Hi,
Experience some problem with side bar that disappeared when clicking on "hamburger" icon (see on pics)

 attached.
Thanks

<img width="102" alt="Capture d’écran 2020-03-26 à 16 28 29" src="https://user-images.githubusercontent.com/46765222/77715265-3b05ff80-6f7f-11ea-95d1-38f1c2958feb.png">
<img width="71" alt="Capture d’écran 2020-03-26 à 16 28 43" src="https://user-images.githubusercontent.com/46765222/77715273-422d0d80-6f7f-11ea-8926-8af2aa97b8e5.png">

**Comment by samuelstj** [comment]
Same problem here. Anyone got a solution?

**Comment by samuelstj** [comment]
Segundo o Willian, já foi resolvido a partir da versão disponível para o moodle 3.8.

Mas ele ajudou com um workaround para não ter que atualizar logo de cara.

**Go to Site administration -> Appearance -> Themes -> Moove -> Advanced**

**On Raw SCSS (theme_moove|scss) insert this code:**

`#nav-drawer[aria-hidden=true] .list-group-item {
display: block;
}`

**Comment by willianmano** [comment]
@Roussxx solved in the lastest versions. Please, update your moove.

**Comment by Roussxx** [comment]
Great thank you !
