### ISSUE TITLE
How to Reduce the size about course list in frontpage

### ISSUE THREAD

**Issue by claudiopardosantos** [willianmano/moodle-theme_moove#212]
Hello, I looking how to reduce the size about the courses in frontpage moove moodle theme
the size for my images is 242x182 pixels

http://clasesonline.ceosolutions.cl/index.php

![Captura de Pantalla 2020-04-11 a la(s) 22 47 50](https://user-images.githubusercontent.com/49456080/79059325-8c341580-7c46-11ea-8b3a-14be4bf6576a.png)

thanks a lot

**Comment by willianmano** [comment]
The blocks are responsive.
