### ISSUE TITLE
version 2.3.9 and moodle 3.5.2+

### ISSUE THREAD

**Issue by Lior79** [willianmano/moodle-theme_moove#213]
Hi,
I installed version 2.3.9 under moodle 2.5.2+
I get the following error in M.S explorer version 11:
Call to undefined method core\session\manager::get_login_token()
I previously had moove 2.3.8 and was working ok.
Please advise,
Regards,
Lior

**Comment by willianmano** [comment]
@Lior79 update your moodle and the theme. This issue was solved in the newest versions.
