### ISSUE TITLE
Compatibilidade do H5P com o Moove

### ISSUE THREAD

**Issue by junior-saraiva** [willianmano/moodle-theme_moove#215]
Estamos com um problema na visualização do H5P no momento da configuração das atividades. Ao adicionar ou editar uma atividade H5P, todo o conteudo fica restrito a uma pequena coluna na esquerda da tela, o restante fica todo em branco do lado direito, conforme pode ser visto na imagem em anexo.

Para constar:
Usando Moodle 3.8.2+ (Build: 20200312) e Moove 3.8.8 2020031800

![Bug_moovie](https://user-images.githubusercontent.com/63818421/79506026-b2bdcc00-800b-11ea-9665-b6f0549bef70.jpeg)

**Comment by willianmano** [comment]
Grande @junior-saraiva . Meu querido, acabei de testar aqui e ta funcionando normalmente. Não consegui simular este comportamento.
