### ISSUE TITLE
Melhorias na responsividade em conteúdo H5P

### ISSUE THREAD

**Issue by junior-saraiva** [willianmano/moodle-theme_moove#216]
Vários alunos relataram não estarem conseguindo realizar a atividade Caça-Palavras feita no H5P porque na tela dos celulares não aparece todo o conteúdo da atividade, mesmo virando o celular na horizontal. 
Nos testes realizados na imagem 1 demostra o problema e na imagem 2 aumentando o tamanho da tela percebe-se que o conteúdo volta a aparecer. 

**Imagem 2:**
![Bug_moovie_Responsividade_2](https://user-images.githubusercontent.com/63818421/79511595-ff0e0980-8015-11ea-9d5d-4e2302510e11.png)

**Imagem 1:**
![Bug_moovie_Responsividade](https://user-images.githubusercontent.com/63818421/79511591-fddcdc80-8015-11ea-87e5-77f6f69507ad.png)

**Comment by willianmano** [comment]
Grande @junior-saraiva . Meu querido, acabei de testar aqui e ta funcionando normalmente. Não consegui simular este comportamento.
