### ISSUE TITLE
Theme Moove não funciona

### ISSUE THREAD

**Issue by MartiusEduardo** [willianmano/moodle-theme_moove#217]
Quando mudo o theme para o Moove, toda a página fica como na imagem abaixo:

![image](https://user-images.githubusercontent.com/35742758/79672586-d159c980-81a9-11ea-9677-2e824e291c1d.png)

Como resolvo esse problema?

**Comment by willianmano** [comment]
Esse é um problema do moodle. Aumente o limite de memória do seu php ou execute o comando do moodle para fazer build do tema. 

`sudo -u www-data /usr/bin/php admin/cli/build_theme_css.php --themes=boost,moove`
