### ISSUE TITLE
matriculacion

### ISSUE THREAD

**Issue by sebastianxrc** [willianmano/moodle-theme_moove#22]
Hola,
He instalado la ultima versión del tema sobre Moodle 3.3.2+ (Build: 20171006) 

Al momento de desplegar la pagina de cursos con la opción de auto-matriculado activada, la foto de la portada del curso aparece expandida ocupando casi toda la pantalla. Si cambio a otro tema, el problemas desaparece. 

Como reproducirlo:
Como administrador : Ir a un curso activar matriculación automática. 
Como estudiante: Navegar al curso, donde se mostrará el detalle y la opción de auto-matricularse.

Link a la imagen:
https://ibb.co/hb1q3w

**Comment by willianmano** [comment]
@sebastianxrc Thank you. I will work on it.

**Comment by willianmano** [comment]
@sebastianxrc I am finishing the version 2 of the theme. I will be lauched with moodle 3.4. I solved that issue in this version.

**Comment by sebastianxrc** [comment]
Great! I saw your theme in moodle early birds.
I ll download it when the new release is ready

Tks!
