### ISSUE TITLE
Error: Component was not valid

### ISSUE THREAD

**Issue by berthelemy** [willianmano/moodle-theme_moove#220]
Hi there,

I'm upgrading Moodle from 3.8 to 3.8.2+

I have replaced the theme/moove directory with the most recent version of Moove.

When I go to the site I get the following error on a blank page:

> Coding error detected, it must be fixed by a programmer: Component was not valid: theme_moove

I've searched elsewhere and can't find anyone else with this issue.

Can you suggest how to debug it?

Thanks,

Mark

**Comment by willianmano** [comment]
@berthelemy this is probably a problem with your directories. Unfortunately, I can't help you.

**Comment by berthelemy** [comment]
Thanks @willianmano - That's fine. It was a problem with the directories. All is sorted.
