### ISSUE TITLE
TinyMCE Editor WYSIWYG not working

### ISSUE THREAD

**Issue by ajaykulkarni01** [willianmano/moodle-theme_moove#221]
I am using the Moove theme with TinyMCE editor on Moodle to create e-learning courses. While editing the text in the editor, the CSS is not visible / not getting applied to content. But when I'm out of the editor, it is actually get applied to the page. I really can't find the reason? It is really frustrating in this way - being not able to see the CSS while editing. Would anyone please help me out????

**Comment by willianmano** [comment]
@ajaykulkarni01 try to test a default theme like boost, if the problem persists so it is a Moodle problem, not a moove issue.

**Comment by ajaykulkarni01** [comment]
@willianmano thank you for the reply. Yes, it works perfectly in boost, snap. But the problem persists when using the Moove theme. Would you please suggest what can be done to resolve this?

**Comment by ajaykulkarni01** [comment]
@willianmano any help in this regards is really appreciated. Thank you.

**Comment by willianmano** [comment]
@ajaykulkarni01 could you please send me the code, screenshot, something to help me?
