### ISSUE TITLE
moodledata not calculated yet.

### ISSUE THREAD

**Issue by xgamesfrozen** [willianmano/moodle-theme_moove#227]
Hi, im working on moodle 3.8.3+, with the last version of theme moove, and i have this problem, already run cron job.
![notcalc](https://user-images.githubusercontent.com/12519539/82134730-243a9700-97d1-11ea-8176-9341ccf8a76a.jpg)

**Comment by willianmano** [comment]
@xgamesfrozen are you using APCu cache storage?

**Comment by Mvfasa** [comment]
Hi, i have the same problem, the task is running ok.

![evidencia1](https://user-images.githubusercontent.com/49371403/83224964-4ffc3c00-a144-11ea-957f-751fea02bffc.png)

**Comment by xgamesfrozen** [comment]
Not using apcu

Obtener Outlook para Android<https://aka.ms/ghei36>
________________________________

**Comment by jpenhos** [comment]
Hey, having the same problem after upgrading moodle to 3.8

**Comment by squid46** [comment]
Off APC (APCu) cache.

**Comment by lukacspeter** [comment]
Hi, just my 2 cents:
This calculation based on Moodle's get_directory_size() function. If you check this function in **\lib\moodlelib.php**, the default/fastest way to get directory size is using **du** executable (defined here: https://YOURSITE/admin/settings.php?section=systempaths ).

If it isnt defined (default it isnt), the function will use the much slower [filesize() ](https://www.php.net/manual/en/function.filesize.php)PHP function. If you check the docs, especially the comments, there are limitations and workarounds to get results over 2GB. Maybe this is the case why 'totalusagereadable' isnt defined on some sites.

You can try it with this code:

`<?php
require('config.php');

//some Moodle security: you have to login first:
require_login();

use cache;

if (!empty($CFG->pathtodu) && is_executable(trim($CFG->pathtodu))) {
	echo "du is defined and executable, so lib\moodlelib.php's get_directory_size() function will use it:<br> ";
} else {
	echo "du isnt defined and/or not executable, so lib\moodlelib.php's get_directory_size() function will use filesize() builtin PHP function:<br>";
}

$totalusage = get_directory_size($CFG->dataroot);
$totalusagereadable = number_format(ceil($totalusage / 1048576));

echo "Size returned from this function: ". $totalusagereadable." GB<BR>";

$cache = cache::make('theme_moove', 'admininfos');

echo "Size stored in Moove's cache: ".$cache->get('totalusagereadable')." GB";
?>`

**Comment by isnanw** [comment]
> Hi, just my 2 cents:
> This calculation based on Moodle's get_directory_size() function. If you check this function in **\lib\moodlelib.php**, the default/fastest way to get directory size is using **du** executable (defined here: https://YOURSITE/admin/settings.php?section=systempaths ).
> 
> If it isnt defined (default it isnt), the function will iterate thru all the dirs with the much slower [filesize() ](https://www.php.net/manual/en/function.filesize.php)PHP function. If you check the docs, especially the comments, there are limitations and workarounds to get results dirs over 2GB. Maybe this is the case why 'totalusagereadable' isnt defined on some sites.
> 
> You can try it with this attached code, just rename back to .php, copy to your Moodle's root dir and call it from a browser:
> [Moove_cache_debug.php.txt](https://github.com/willianmano/moodle-theme_moove/files/4868299/Moove_cache_debug.php.txt)
========================================
du isnt defined and/or not executable, so lib\moodlelib.php's get_directory_size() function will use filesize() builtin PHP function:
Size returned from this function: 18 GB
Size stored in Moove's cache: GB
========================================

what is the next step?

**Comment by isnanw** [comment]
> Hi, just my 2 cents:
> This calculation based on Moodle's get_directory_size() function. If you check this function in **\lib\moodlelib.php**, the default/fastest way to get directory size is using **du** executable (defined here: https://YOURSITE/admin/settings.php?section=systempaths ).
> 
> If it isnt defined (default it isnt), the function will iterate thru all the dirs with the much slower [filesize() ](https://www.php.net/manual/en/function.filesize.php)PHP function. If you check the docs, especially the comments, there are limitations and workarounds to get results dirs over 2GB. Maybe this is the case why 'totalusagereadable' isnt defined on some sites.
> 
> You can try it with this attached code, just rename back to .php, copy to your Moodle's root dir and call it from a browser:
> [Moove_cache_debug.php.txt](https://github.com/willianmano/moodle-theme_moove/files/4868299/Moove_cache_debug.php.txt)

========================================
du isnt defined and/or not executable, so lib\moodlelib.php's get_directory_size() function will use filesize() builtin PHP function:
Size returned from this function: 18 GB
Size stored in Moove's cache: GB
========================================

what is the next step?

**Comment by SubjectXXX** [comment]
Go to admin-> Server -> System paths and fix paths.
