### ISSUE TITLE
I can not see the marketing sections, the slider, the sponsors and the clients spaces in the frontpage

### ISSUE THREAD

**Issue by duiliogabriel** [willianmano/moodle-theme_moove#228]
Hello, my frontpage is showing only the background image and the login form
www.caded.org.ar/Camous/index.php
How can I show the slider, marketing spaces, sponsors logo, etc?
Thank you

**Comment by duiliogabriel** [comment]
www.caded.org.ar/Campus/index.php is the correct url

**Comment by kikearciniegas** [comment]
@duiliogabriel I have the same issue, what settings did you change to correct the behaviour? Cheers.
