### ISSUE TITLE
Modificar Pié de Página

### ISSUE THREAD

**Issue by Alanfermin** [willianmano/moodle-theme_moove#23]
No puedo modificar en el inicio del sitio, en el pié de página:
STAY in TOUCH

Ni tampoco puedo modificar: 

Proudly made with Moodle logo

This theme was developed by conecti.me

Quisiera apoyo para poder modificar esto por favor.

**Comment by willianmano** [comment]
The strings can be translated in lang files. You can modify the templates/footer.mustache file and do what you want.
