### ISSUE TITLE
Mostrar página de login com cursos

### ISSUE THREAD

**Issue by thwierman** [willianmano/moodle-theme_moove#230]
Olá Willian, primeiramente parabéns pelo tema, é fantástico! Prático, versátil e moderno.
Estou com dificuldade (provavelmente deve ser algo simples) para aparecer a tela completa de login (com os cursos e informações de clientes). A tela que aparece é bem simples, só pedindo usuário e senha (magem abaixo), e não consigo alterá-la para a outra, completa do tema. 
Pode me dar uma dica de como alterar? Já procurei aqui nas discussões e na internet e não encontri informações. Muito obrigado!

![Image2](https://user-images.githubusercontent.com/67067713/84925986-1b273900-b0a1-11ea-84e5-4e3e62129392.png)

**Comment by willianmano** [comment]
@thwierman O seu Moodle está configurado para forçar os usuários a fazerem login, por isso direciona para a página de login. 

https://elearning.3rdwavemedia.com/blog/how-to-set-moodles-user-login-page-as-the-sites-landing-page/592/
