### ISSUE TITLE
Largura do curso no formato semanal

### ISSUE THREAD

**Issue by sergiocneto** [willianmano/moodle-theme_moove#233]
Boa tarde,
Estou utilizando o Moove 3.9.02, e alguns professores notaram que, com o curso no formato semanal, a largura disponível da tela não é totalmente preenchida, com o curso ocupando apenas parte do espaço à esquerda. 
Marquei em vermelho, na imagem em anexo, o espaço que está sobrando em branco ao lado dos tópicos do curso.
No formato de tópicos o preenchimento é correto.

![Capturar](https://user-images.githubusercontent.com/67287320/85321250-c3227500-b49a-11ea-9662-d4231140b16f.PNG)

**Comment by squid46** [comment]
https://github.com/willianmano/moodle-theme_moove/issues/231#issue-642960651

**Comment by sergiocneto** [comment]
Boa tarde,
Verificando o problema, no arquivo templates/course_cover.moustache, alterei a class do div com id region-main-box, de col-xs-12 para col-md-12, o que solucionou o problema.

**Comment by willianmano** [comment]
@sergiocneto  I already solved it. Thank you.
