### ISSUE TITLE
Repeated Description in List of Courses on Front Page

### ISSUE THREAD

**Issue by yanus** [willianmano/moodle-theme_moove#234]
Since the last update the course descriptions are shown above the titles and then again below, also pushing down the category and teacher icons:
![image](https://user-images.githubusercontent.com/5475686/85534913-05ba8d80-b612-11ea-8faa-8b08b8a9f8b9.png)

Using Moodle 3.9 (Build: 20200615) and Moove 3.9.03 (Build: 2020062300)

**Comment by MyCupofTICE** [comment]
I have the same problem.

**Comment by yanus** [comment]
As a quick fix, removing/commenting [line 242 in classes/output/core/course_renderer.php](https://github.com/willianmano/moodle-theme_moove/blob/245b00d0e5031128d624a0b7e80e1422747a5d40/classes/output/core/course_renderer.php#L242) gets rid of the first description.

**Comment by MyCupofTICE** [comment]
Thanks for the tip !

**Comment by willianmano** [comment]
@yanus @MyCupofTICE I fixed it in the latest commit. Thanks.
