### ISSUE TITLE
Error with certificates in Postgresql

### ISSUE THREAD

**Issue by sebastiangz** [willianmano/moodle-theme_moove#236]
In the moove/classes/util/certificates.php file in aprox line 104

$sql = 'SELECT sci.code, sci.pathnamehash, sc.name, c.id as courseid, c.fullname, c.shortname

I had to eliminate  ' "simplecertificate" as module' for it to work with a PostgreSQL database. 

Any ideas?

**Comment by willianmano** [comment]
@sebastiangz thanks for reply, i just solved it.
