### ISSUE TITLE
Double information in the course description

### ISSUE THREAD

**Issue by sniperventura** [willianmano/moodle-theme_moove#237]
Hello
I hope you can help me, I find myself using the move theme in Moodle, it's great.
But I have a problem, when a course appears on the main page it appears with repeated or double information, attached image to better clarify the situation.
![01](https://user-images.githubusercontent.com/67473835/85872341-3414a600-b795-11ea-94d6-85575b232555.jpg)
![02](https://user-images.githubusercontent.com/67473835/85872345-34ad3c80-b795-11ea-9509-8088645d5662.jpg)

**Comment by willianmano** [comment]
@sniperventura this was fixed. Please, update your theme.
