### ISSUE TITLE
Admin accounts slow to login

### ISSUE THREAD

**Issue by gpillsbury** [willianmano/moodle-theme_moove#24]
The "dashboard" data that appears when an admin account logs in is nice and colorful, but it significantly slows down the login process on my site (15 GB data, 2670 users, 164 courses, etc.).  Can that feature be added as a setting in the theme preferences?

**Comment by gogrichard** [comment]
With one of my systems (593,354 MB moodledata 32303 users 17174 courses) this theme absolutelly unusable for administrators. (3-10 min to login)
I managed to solve this problem with a scheduled task and db.
Please optimize this fascinating theme, allowing for the bigger sites to use it.
[modified.zip](https://github.com/willianmano/moodle-theme_moove/files/1417863/modified.zip)

**Comment by gpillsbury** [comment]
Tried installing the files in that zip, but couldn't login afterward.  "Error reading from database".

**Comment by gogrichard** [comment]
Sorry for that.
I sent it as an idea, not as a ready to use, completely workedout solution.
In my environment it works fine.

With my .zip of idea I only tried to inspire the developers to solve this problem.

**Comment by willianmano** [comment]
I have this same issue in my environments. I think the best solution is remove this feature, because this calculation of space really takes some time to finish.

**Comment by gogrichard** [comment]
I like this feature. With my modification the moodle's cron do the calculation every hour and nobody notice it. So I think this feature's removal not the best option.

**Comment by willianmano** [comment]
@gogrichard In the implementation I create a cache with this data, and the calculation is updated every hour. But I don't know why this doesn't work in every environments. I tested with two big environments and this approach only worked in one.

**Comment by rpolesi** [comment]
@gpillsbury gostei de sua ideia. se @willianmano puder implementar realmente será interessante.
Eu que tenho apenas 1000 usuários e 5 cursos, concordo que demora bastante para administrador fazer login.

**Comment by rodrigoalineri** [comment]
To solve the problem temporarily and avoid the long loading time, I had to set a fixed value in the file below.

1) edit file: /your-moodle-directory/theme/moove/layout/mydashboard.php
2) comment line: $totalusage = get_directory_size($CFG->dataroot);
3) add line: $totalusage = 1024*1024;
