### ISSUE TITLE
Atualização Moove

### ISSUE THREAD

**Issue by hebertpxx** [willianmano/moodle-theme_moove#241]
Fiz algumas customizações e ajustes para dispositivos móveis via CSS custimizado, será que se eu atualizar o _template_ pra nova versão ele vai ser resetado? Quanto ao CSS nem há tanto problema, tenho um arquivo externo com o conteúdo, mas quanto às configurações (textos, imagens), elas permanecem?

**Comment by willianmano** [comment]
@hebertpxx você não perde nada atualizando. Pode atualizar sem medo.

**Comment by hebertpxx** [comment]
Obrigado, Mano. Esse é o melhor tema gratuito que já vi. Sent from Mail for Windows 10 From: Willian ManoSent: quinta-feira, 16 de julho de 2020 07:31To: willianmano/moodle-theme_mooveCc: hebertpxx; MentionSubject: Re: [willianmano/moodle-theme_moove] Atualização Moove (#241) @hebertpxx você não perde nada atualizando. Pode atualizar sem medo.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
