### ISSUE TITLE
Banner rotativo

### ISSUE THREAD

**Issue by hebertpxx** [willianmano/moodle-theme_moove#243]
O filtro multi-idioma é capaz de traduzir todas as partes do template, exceto os textos adicionados no banner rotativo.

**Comment by TowerX** [comment]
If you are using the multi-language filter (v2) plugin you can manually add the translations on the spots required by using the following code:

`{mlang xx}Content in xx language here{mlang}`

Replace "xx" with the actual language (en, es, eu, et.).

If you are using the default multi-language filter you can manually add translations where you need them by using the following code:

`<span class="multilang" lang=xx">Content goes here</span>`
Replace "xx" with the actual language (en, es, eu, et.).

**How does this work?**
When you switch language, the filter will look for those tags and automatically use the content that matches the language you specified.

This is a lot of manual work but it functions as a workaround if a more permanent solution is needed. 

Hope this helps!

**Comment by hebertpxx** [comment]
Good afternoon.

Yes, I did it, but it doesn't work, see the attachment.


Regards



Enviado do Email <https://go.microsoft.com/fwlink/?LinkId=550986> para
Windows 10



*De: *Jay Torres <notifications@github.com>
*Enviado:*quarta-feira, 22 de julho de 2020 13:33
*Para: *willianmano/moodle-theme_moove
<moodle-theme_moove@noreply.github.com>
*Cc:*hebertpxx <hebert.souzavinha@gmail.com>; Author
<author@noreply.github.com>
*Assunto: *Re: [willianmano/moodle-theme_moove] Banner rotativo (#243)



If you are using the multi-language filter (v2) plugin you can manually add
the translations on the spots required by using the following code:

{mlang xx}Content in xx language here{mlang}

Replace "xx" with the actual language (en, es, eu, et.).

If you are using the default multi-language filter you can manually add
translations where you need them by using the following code:

<span class="multilang" lang=xx">Content goes here</span>
Replace "xx" with the actual language (en, es, eu, et.).

*How does this work?*
When you switch language, the filter will look for those tags and
automatically use the content that matches the language you specified.

This is a lot of manual work but it functions as a workaround if a more
permanent solution is needed.

Hope this helps!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/willianmano/moodle-theme_moove/issues/243#issuecomment-662556243>,
or unsubscribe

**Comment by TowerX** [comment]
@hebertpxx 

I can't see the attachment, please submit again so I can assist you.

**Comment by calbasi** [comment]
Hi, I can confirm this issue: 
multi-language filter (v2) translate fields like:
theme_moove | marketing1heading
but not:
theme_moove | clientstitle
theme_moove | clientssubtitle
theme_moove | slidertitle3
theme_moove | slidercap3

**Comment by calbasi** [comment]
By the way, I suggest to change this issue title to something like:
"Banner strings can not be translated"

**Comment by calbasi** [comment]
By the way, maybe this issue is related to this:
https://github.com/iarenaza/moodle-filter_multilang2/issues/8#issuecomment-276959389

**Comment by calbasi** [comment]
Hi, @pllagn and myself have make a pull request to fix this issue, as well as clients fields not translatable.
