### ISSUE TITLE
Incorrect license and copyright statements in metismenu Javascript

### ISSUE THREAD

**Issue by danmarsden** [willianmano/moodle-theme_moove#244]
It appears that Metismenu was based on an old version of the library here:
https://github.com/onokumus/metismenu

you have added your own copyright and license headers to this file which is incorrect.

This is the sort of thing that once picked up would be a blocker for approval in the plugins db. We're quite sensitive to trademark/copyright issues! :-)

Can you please tidy that up? - typically when you use an upstream unmodified version of a library you would also add a thirdpartylibs.xml file covering the details.

see here for more detail:
https://docs.moodle.org/dev/Plugin_with_third_party_libraries

thanks!

**Comment by willianmano** [comment]
@danmarsden  is MIT not compatible with Moodle license?

**Comment by willianmano** [comment]
@danmarsden I will work on the third party file and fix it as soon as possible. I have a question. I modified the metismenu file to work well with moodle amd modules, how should I document this?

**Comment by danmarsden** [comment]
Yes - MIT is compatible with GPL and code that is licensed under MIT can be included in your plugin, but you cannot add a GPL statement to the metismenu code - changing the existing licesnse from MIT to GPL as you are not the original author.

You probably need to:
* Remove the gpl header and your copyright line from the metismenu.js - you can't change metismenu code from MIT to GPL.
* add the details on the metismenu and license in thirdpartylibs.xml file 

Then typically when including a thirdparty lib file, you drop in a readme.txt file or something similar into the same directory where the lib is stored covering the details on the file - where it came from, who authored it, what license it uses because you don't normally want to modify that lib file all that much so that you can update it based on the upstream version relatively easily.... but because you've heavily modified metismenu from upstream anyway, I'd be inclined to add a comment at the top of the file - pointing at the original Metismenu github repo - maybe even copying the author/copyright/license information from the github readme:
https://github.com/onokumus/metismenu#author
and then under that statement with the original author/copyright / mention of MIT license you could add some comments to say that you have modified the lib to meet the needs of the moove theme.

hope that makes sense! - thanks! :-)

**Comment by danmarsden** [comment]
also - what might not be clear, is that adding a 3rd party lib to the thirdpartylibs.xml file will tell moodles automated code-checker to ignore that file - as it is an external lib and doesn't need to follow Moodle's internal coding guidelines.

**Comment by willianmano** [comment]
@danmarsden thank you for report this. I think everything is ok now.

**Comment by danmarsden** [comment]
awesome!! - thanks for tidyying that all up!! :-)
