### ISSUE TITLE
webfonts included missing license/attribution information

### ISSUE THREAD

**Issue by danmarsden** [willianmano/moodle-theme_moove#246]
The simple-line-icons webfonts included in your plugin are not attributed anywhere - if these came from "GraphicBurger" they have a "GraphicBurger" custom license that doesn't appear compatible with the GPL to me.

particularly this line under prohibitions:

"You do not have the rights to redistribute, resell, lease, license, sublicense or offer 
files downloaded from GraphicBurger to any third party as is or as a separate attachment 
from any of your work"

I suspect this might mean you need to remove these from your plugin.
pinging @mudrd8mz here as well - David did you have any thoughts on this?

thanks!

**Comment by willianmano** [comment]
@danmarsden is MIT not compatible with Moodle license?

**Comment by danmarsden** [comment]
MIT is definitely compatible, but when I searched for simple-line-icons it came up with the GraphicBurger website and a custom license which is definitely not compatible with the GPL.

Have you got a reference url where you can point to the simple line icons font being released under the MIT license?

**Comment by willianmano** [comment]
@danmarsden thank you for report this. I think everything is ok now.

**Comment by mudrd8mz** [comment]
> Have you got a reference url where you can point to the simple line icons font being released under the MIT license?

So my underdstanding is that this reference URL is https://simplelineicons.github.io/ then (see their footer there).
