### ISSUE TITLE
dyslexic font included without attribution/license copyright

### ISSUE THREAD

**Issue by danmarsden** [willianmano/moodle-theme_moove#247]
you should probably drop a readme.txt file into your fonts dir covering the dyslexic font, but you should also include it in the thirdpartylibs.xml file within your plugin.

**Comment by danmarsden** [comment]
- this one does look compatible with gpl, so it's just a matter of making sure you attribute it correctly.

**Comment by willianmano** [comment]
@danmarsden thank you for report this. I think everything is ok now.
