### ISSUE TITLE
Invalid icon system requested '\theme_moove\util\icon_system'

### ISSUE THREAD

**Issue by cmseal** [willianmano/moodle-theme_moove#248]
Hi,

Currently using Moodle 3.8.4+ (20020717000) with Moove 3.8.13 (2020062600) from branch MOODLE_38_STABLE.

We're getting the following popping up once logged in:

```Coding error detected, it must be fixed by a programmer: Invalid icon system requested '\theme_moove\util\icon_system'```

I'm able to close and continue, but going to some pages cause it to come up again. Everything else seems to work fine.

Any assistance or advice would be greatly appreciated!

Many thanks,
Chris

**Comment by willianmano** [comment]
@cmseal thanks for reply this. Please, update your theme.

**Comment by cmseal** [comment]
Thank you, @willianmano for this... Would you be able to add this fix to the ```MOODLE_38_STABLE``` branch at all? It would be greatly appreciated, rather than using ```master```.
