### ISSUE TITLE
"Course updates" information not styled

### ISSUE THREAD

**Issue by gpillsbury** [willianmano/moodle-theme_moove#25]
When it appears, the "Course updates" header is not styled like the other h3's in the blocks region with the class "card-header".  It's not a block though, so I'm not sure how it could be targeted.  Just wanted to point out that it looks strange. See below:

![screenshot-2017-10-27 testing-sandbox participants](https://user-images.githubusercontent.com/1123665/32116623-40185a80-bb00-11e7-81f4-a500f714d39a.png)

**Comment by willianmano** [comment]
Hi @gpillsbury thanks for report this. I solved this issue in the last version. Please update your theme.
