### ISSUE TITLE
Ícone de mensagem

### ISSUE THREAD

**Issue by hebertpxx** [willianmano/moodle-theme_moove#250]
Essa última atualização trouxe uma mudança no ícone de mensagem que o deixou destoante em relação aos demais ícones, ao meu ver, o design dos ícones da barra do cabeçalho estavam melhores antes, se for mudar a Font Awesome seria conveniente mudar a de todos os ícones então. Além dos estilos não estarem compatíveis entre si, ainda o de mensagens ficou desalinhado.

![icones-barra-cabecalho](https://user-images.githubusercontent.com/33330466/87949722-c51d2b00-ca7c-11ea-8bdd-7865805c7607.png)

**Comment by willianmano** [comment]
@hebertpxx sim, estava. mas o pessoal do moodle fez o favor de quebrar os temas filhos e ainda não temos solução de como reverter isso, por isso o ícone voltou ao padrão do moodle. agora é esperar eles resolverem isso ou nos dar uma saída.

**Comment by hebertpxx** [comment]
Ok, entendi, obrigado.

Em seg, 20 de jul de 2020 12:59, Willian Mano <notifications@github.com>
escreveu:
