### ISSUE TITLE
Invalid Parameter Value Detected When Opening Calendar

### ISSUE THREAD

**Issue by Lisa-Touchton-DEV** [willianmano/moodle-theme_moove#254]
![Screenshot (58)](https://user-images.githubusercontent.com/66438510/88061965-34a32100-cb36-11ea-93c3-dc422a5d67ef.png)

Every time I install this theme I keep getting this popup on the calendar. Here is the debugger output for reference:

Missing required key in single structure: year
Error code: invalidparameter
* line 349 of /lib/externallib.php: invalid_parameter_exception thrown
* line 240 of /lib/externallib.php: call to external_api::validate_parameters()
* line 81 of /lib/ajax/service.php: call to external_api::call_external_function()

I changed my theme to boost and the calendar works fine. Currently I'm running moodle 4.0. Is there something on the server side I'm forgetting? Any help would be greatly appreciated.

**Comment by willianmano** [comment]
@Lisa-Touchton-DEV Moodle 4.0 is a beta version. The theme doesn't have support for this version.
