### ISSUE TITLE
Issue with the Activity Icons and Images

### ISSUE THREAD

**Issue by stuartcorns** [willianmano/moodle-theme_moove#256]
Hi, I am havng some issues with the activity icons and some core images. They are not loading.... when I load the image/icon in another page I get the error for 'Image was not found'. I only have this problem when installing the Moove theme. The sidebar/fontawesome icons loaded in with the <i> tag work fine but its the <img> tags that are not working correctly. Can anyone help? been racking my brains.

I can't find much help anywhere. One previous issue people have had is not loading all the icons but that includes all fontawesome too. I have tried some of the tips people have gave, one was to purge the caches. Images are here to help explain

![img1](https://user-images.githubusercontent.com/68976364/88865882-ffb36000-d200-11ea-8489-6db397412b5e.png)
![img2](https://user-images.githubusercontent.com/68976364/88865886-0346e700-d201-11ea-911a-e0d2c66171ce.png)
![img3](https://user-images.githubusercontent.com/68976364/88865892-0510aa80-d201-11ea-8e4a-6c8d3a11c2ed.png)

**Comment by willianmano** [comment]
@stuartcorns this is probably an issue with your moodle.
