### ISSUE TITLE
Changes not getting saved 

### ISSUE THREAD

**Issue by ankitiitj** [willianmano/moodle-theme_moove#258]
Dear William,

We have installed this theme Moove in our Moodle 3.9.1 and is running successfully and we really appreciate your theme. 
One small error is coming when we try to do change in the theme and click on save a change it redirects to a connection error. We tried with different versions 3.8,3.7 but still the same error.
![moove1](https://user-images.githubusercontent.com/69293547/89496403-e8174100-d7d7-11ea-86e1-f64ca6277840.png)
![moove](https://user-images.githubusercontent.com/69293547/89496407-e9e10480-d7d7-11ea-98fd-26400e84be1a.png)

**Comment by ankitiitj** [comment]
Classic and boost themes are working fine.

**Comment by willianmano** [comment]
@ankitiitj this is probably a problem with your moodle, not with the theme.
