### ISSUE TITLE
Filepicker never loading

### ISSUE THREAD

**Issue by paul-tharun** [willianmano/moodle-theme_moove#259]
The file picker on the theme settings page for few fields is never loading and giving this error
http://prntscr.com/tvxaco

console has this error with some mentions of yui-moodlesimple-min.js:
Uncaught TypeError: buttonDeleteFile is null

**Comment by willianmano** [comment]
@paul-tharun this is probably a problem with your moodle not with the theme.

**Comment by paul-tharun** [comment]
@willianmano Do you know of anyway we can fix this?
