### ISSUE TITLE
 Sections are not displayed on the left menu button

### ISSUE THREAD

**Issue by jesusman111** [willianmano/moodle-theme_moove#260]
Hi,
In moodle 3.8.3, sections are not displayed on the left menu button when the dropdown is opened.

Regards

**Comment by willianmano** [comment]
@jesusman111 this only occurs on mobile screens.

**Comment by jesusman111** [comment]
It happens to me on the PC.

I attach a screenshot.

No section item is displayed.

Regards

![cap-08](https://user-images.githubusercontent.com/61394948/90572059-6817b080-e1b3-11ea-9a23-956a1b70ff2f.png)
