### ISSUE TITLE
Book module prevents search box from opening

### ISSUE THREAD

**Issue by berthelemy** [willianmano/moodle-theme_moove#261]
Hi there,
We're using the Moove theme along with the Book plugin, and the Tiles course format.
All works really well, except, when we're viewing a book, it's not possible to open the search box.

Other buttons in the toolbar (language, notifications, profile) work fine.

The search button is showing as clickable, but nothing happens when you click on it. There are no errors showing in the console.

I've not noticed this behaviour on any other activity module. Just the Book.

Thanks,

Mark

**Comment by berthelemy** [comment]
Sorry for the late reply!

I've tested with Boost as shipped with Moodle, and the search box works fine.

So there's something with Moove that isn't working. I'm now using Moodle 3.9.1

**Comment by mcastrok** [comment]
Hi everyone, I am having the same problem as Mark. I am using Moodle 3.10.2 with Moove. Every other activity, plugin, block works fine, only the Book does not allow me to display the search box when I click on the search icon. Clicking on the messages icon doesn't work either. Only the notifications icon works as expected. I have checked the capabilities, the css, even the code, but I don't get the solve the problem.
Mark, could you solve this issue? 

Thanks,

Mariela
