### ISSUE TITLE
I can't add new blocks

### ISSUE THREAD

**Issue by ggporlan** [willianmano/moodle-theme_moove#266]
Hi,

When I click on Add new block, the list of block appears. When I click on the block type I want to add, the page refreshes but block is not there. 

Thank you.

**Comment by adriano515** [comment]
I think this is happening to me or is at least related in version 3.9.2 , adding a block adds it to the sidebar but there's no scrollbar so it can't be seen

**Comment by ggporlan** [comment]
I have discovered that when I add a new block, it appers on the right side in the sidebar.

I you don't see the block, try opening the right side menu and see if the blocks is in the top of the sidebar.
