### ISSUE TITLE
Layout issues with Grid course format

### ISSUE THREAD

**Issue by gpillsbury** [willianmano/moodle-theme_moove#27]
There are two clashes between Moove and the Grid course format.  Not sure which one needs an update to address them, but these problems do not appear in the Collapsed Topics format.
1. Scrollbars in the item description area.  Scrollbars are present even if the Blocks area is hidden.

![grid_scrollbars](https://user-images.githubusercontent.com/1123665/32342639-3c473a94-bfbe-11e7-9260-fbfb237cfa1c.jpg)

2. Blocks area obscures the "close" and "next section" icons when Grid setting "Fit section pop-up to window" is set to "Yes".  The problem exists only when the Blocks area is visible.  If the Blocks area is hidden, there is no problem accessing the icons.  Also, if the Grid fit-to-window setting is "No", there is no issue at all with the icons.

![grid_hidden_close](https://user-images.githubusercontent.com/1123665/32342926-20bbb6a0-bfbf-11e7-8f65-02a0cb37e279.jpg)

**Comment by willianmano** [comment]
@gpillsbury I am finishing the version 2 of the theme. I will be lauched with moodle 3.4. I tested in that version and everything was ok.
