### ISSUE TITLE
Customization for default_course.jpg

### ISSUE THREAD

**Issue by AdrianSanchezLopez** [willianmano/moodle-theme_moove#271]
Hi there! currently, as in 3.9.07 (2020071800), there is no way to customize the **site-wide default course image** that is displayed in all course views.
It would be great to have the ability to customize this image (internally called "**default_course.jpg**") for a custom one that then is apply by default to all newly created courses. Similar to the ability to customize the fav icon, front page images, etc

Thanks for the great plugin!

**Comment by PatLemaire** [comment]
For now, the only way to do this is to modify the file 'default_course.jpg' directly in moove/pix.
Other customizations would be appreciated, like changing 'default_coursesummary.jpg' in the settings 😉

**Comment by TanyaToret** [comment]
Hello ! 
First of all, thanks for the theme moove !
Maybe this issue should be renamed to "Customization for all default resources" ? I agree it would be really great to be able to customize the default course summary image ('default_coursesummary.jpg').
