### ISSUE TITLE
Add option to collapse right hand block panel / side bar

### ISSUE THREAD

**Issue by t-penguino** [willianmano/moodle-theme_moove#276]
I have some **mobile device** users who find it confusing when they are presented with the right-hand side bar when loading a course. The side bar expands by default to cover the main course content.

If would be good to have the option to collapse it as default on **mobile** only, as when on desktop it is advantageous to have it show by default.

Or can someone suggest the CSS needed to do this for mobile?

**Comment by valeriia-s** [comment]
Hi @willianmano I second this request, it would be a great addition to the theme to have a setting that makes the right-hand sidebar collapsed by default.

The main issue is with the view on mobile devices, the sidebar is blocking the main section of the page and on some screens, the arrow icon that collapses the sidebar is not visible at all, here is a screenshot:

![IMG_1409](https://user-images.githubusercontent.com/29231219/102417524-b9447f00-3fb0-11eb-8bef-7e3a17c2968b.png)

Here is how the same page looks on the bigger screen:

![photo_2020-12-16_13-21-04](https://user-images.githubusercontent.com/29231219/102417556-c5c8d780-3fb0-11eb-82ee-939391b862eb.jpg)

**Comment by dlove2** [comment]
Yes, please, @willianmano, please consider this.  First-time mobile users are put off by the issue.
Thank you, 
Donna
