### ISSUE TITLE
Moodle docs footer link

### ISSUE THREAD

**Issue by marysuecan** [willianmano/moodle-theme_moove#277]
Hi there,

In Moodle 3.9 I am used to there being a "moodle docs on this page" link through site pages. I am not seeing this after theme Moove was applied, though this does appear to be part of core moodle. Wondering if the Moove theme ignores these settings? (first image)

Other themes seem to have a setting to control visibility of the moodle docs link (second image) but I am not seeing a similar capability in theme Moove's settings.

![Screen Shot 2020-09-30 at 9 04 47 AM](https://user-images.githubusercontent.com/28152570/94711010-67b71d00-02fc-11eb-8a27-c33ceeb2ab71.png)

![Screen Shot 2020-09-30 at 9 05 57 AM](https://user-images.githubusercontent.com/28152570/94711019-6ab20d80-02fc-11eb-96a4-a65d420b62b1.png)

Just wondering what expected behavior is, and if there are/could be any fixes. Thanks!

Smiles,
Mary

**Comment by JosephKennedy4** [comment]
Wondering the same thing!

**Comment by dlove2** [comment]
Same for Moodle 3.9 using Boost.
