### ISSUE TITLE
Moodle User Tours - weird rendering with Moove

### ISSUE THREAD

**Issue by JosephKennedy4** [willianmano/moodle-theme_moove#279]
A User Tour in Moodle 3.8 produces two unexpected rendering issues.

1. Unlike other themes, a user tour which targets a block does not always "point" directly at the block.  
   a.  If the right drawer is closed, the tour just points to the whole drawer
   b.  If the right drawer is open, but the block is not currently visible, the user tour points to the bottom (or top) of the drawer; if the block is visible, the tour correctly identifies and points to the block.

2.  A tour step which displays in the center of the screen is outlined with a rectangle that is twice the size of the block needed to hold the step's contents.

**Comment by SimonEckmiller** [comment]
I have the same issue with Moodle 3.9.1 and Moove. I tried with Adaptable and Boost Campus, there the user tours work fine.
And i spend a lot of time to research what the Solution could be...

I need help too.

**Comment by SimonEckmiller** [comment]
> 
> 
> A User Tour in Moodle 3.8 produces two unexpected rendering issues.
> 
>     1. Unlike other themes, a user tour which targets a block does not always "point" directly at the block.
>        a.  If the right drawer is closed, the tour just points to the whole drawer
>        b.  If the right drawer is open, but the block is not currently visible, the user tour points to the bottom (or top) of the drawer; if the block is visible, the tour correctly identifies and points to the block.
> 
>     2. A tour step which displays in the center of the screen is outlined with a rectangle that is twice the size of the block needed to hold the step's contents.

Hi, I ve looke a bit further into the Forum and find a kind of soultion here: https://github.com/willianmano/moodle-theme_moove/issues/186

**Comment by JosephKennedy4** [comment]
Thank you, Simon.  That addresses one of the two concerns very nicely!  Now, if anyone knows how to address the second problem (User Tours referencing any block in the right drawer point to the drawer as a whole).....?
