### ISSUE TITLE
Feature: Include setting to collapse left navbar by default

### ISSUE THREAD

**Issue by davidpesce** [willianmano/moodle-theme_moove#280]
Please include an admin-level setting that collapses the left navbar by default.

**Comment by davidpesce** [comment]
To clarify, a user can still expand it if needed. Their session info will retain their preference. Happy to pay for the premium version if this is added.

**Comment by jasimp** [comment]
yes. i am also looking for this option

**Comment by arryola** [comment]
I am looking for this option too
