### ISSUE TITLE
Disable bottom footer

### ISSUE THREAD

**Issue by MBlondin** [willianmano/moodle-theme_moove#281]
Has the feature Disable bottom footer been removed in version 3.10.1 of the theme or has it moved place.

**Comment by pu3atteya** [comment]
Actually, I am having the same issue too. But I am using M3.9.3. I cannot disable the bottom footer too.

**Comment by davidpesce** [comment]
I believe he removed that feature from the community version. You can remove it with CSS.

**Comment by davidpesce** [comment]
Here's the commit: https://github.com/willianmano/moodle-theme_moove/commit/8ba6902d479e4d155eeeec29fa239824b90d199d

**Comment by pu3atteya** [comment]
> I believe he removed that feature from the community version. You can remove it with CSS.

Ah. No wonder. Yes, I have removed it with css. Thanks David 🙂

**Comment by willianmano** [comment]
This option is available only in the premium version. You did not pay anything for this theme, so, keep the credits at least.
