### ISSUE TITLE
Theme broken in moodle 3.10

### ISSUE THREAD

**Issue by proftug4** [willianmano/moodle-theme_moove#282]
Theme is broken in moodle 3.10. Footer and header (accessibility)

**Comment by willianmano** [comment]
@proftug4 thanks for add this. Could you please add some images to illustrate it?

**Comment by proftug4** [comment]
Hi, problem Solved with theme upgrade. Sorry, forgot

A terça, 17/11/2020, 14:42, Willian Mano <notifications@github.com>
escreveu:
