### ISSUE TITLE
codingerror :Invalid icon system requested '\theme_moove\util\icon_system'

### ISSUE THREAD

**Issue by lms-ici-dev** [willianmano/moodle-theme_moove#283]
hai wilian , i try to apply moodle theme after upgrading from 3.5 to 3.10 and its show a notification like this 

![image](https://user-images.githubusercontent.com/72126065/99928787-38151600-2d7d-11eb-91e0-e32449fe7e39.png)

do you have any idea to solve it ?

Regards

**Comment by willianmano** [comment]
@lms-ici-dev this was solved in the newest versions, please update your theme.
