### ISSUE TITLE
Add "LICENSE.MD"

### ISSUE THREAD

**Issue by MGradenko** [willianmano/moodle-theme_moove#285]
I would love to use Moove, however, without a license, the Moodle theme/plugin is "All Rights Reserved" and thus not available for use (or modification and redistribution) without expressed permission by the author (copyright holder). Without a license that allows continued use, those using Moove would be subject to any changes in use or permissions required by the copyright holder. Licensing also helps the Moove user-community to contribute back to the project (plugin/theme).

Github recommends using an open source software license for publically available repositories where the copyright holder allows use, modification, and redistribution, see, "[Licensing a repository](https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/licensing-a-repository)."

Thank you for your consideration.

**Comment by willianmano** [comment]
@MGradenko thank you for your observations. I added the file.
