### ISSUE TITLE
Argument 1 passed to theme_boost

### ISSUE THREAD

**Issue by menrf** [willianmano/moodle-theme_moove#287]
Hi! After upgrading to Moodle to version 3.10 and updating the theme, I can't log in to course management.
**Error:** Argument 1 passed to theme_boost\output\core_course\management\renderer::category_listing() must be an instance of coursecat or null, instance of core_course_category given, called in [dirroot]/course/management.php on line 501

**Comment by ftbarata** [comment]
Hi @menrf  I have the same error. I saw you saying that's caching, so I went to moodledata/cache and removed everything within cache, but it didn't solve the problem yet. How did you exactly solved?
