### ISSUE TITLE
how can add custom font to this theme?

### ISSUE THREAD

**Issue by smb-sh** [willianmano/moodle-theme_moove#288]
Please explain in full...

**Comment by Guneee** [comment]
Most stupid almost uneditable theme I ever seen so please choose another one. I'm trying to find header css for like a day or two!

Change to different theme so that maybe you can have solution maybe elegance.

**Comment by willianmano** [comment]
@Guneee thank you for your fucking stupid comment. Don't like it? just not use it your son of a bitch! You did not pay anything to use, so don't fuck the efforts of others. What have you made to help open source? Your piece of shit.

**Comment by willianmano** [comment]
@smb-sh you need to add the font in mustache/inc_start.mustache and then configure css to the new font in scss/moove/_general.scss
