### ISSUE TITLE
moove theme add contact button error "Missing required key in single structure: userid"

### ISSUE THREAD

**Issue by tronghoang-hqt** [willianmano/moodle-theme_moove#289]
![image](https://user-images.githubusercontent.com/58417594/103871101-35893880-50ff-11eb-880b-68de4148b04e.png)

**Comment by tronghoang-hqt** [comment]
Please help me.

**Comment by willianmano** [comment]
@tronghoang-hqt thanks for reply. I just solved it and now is available on 3.10 version.
