### ISSUE TITLE
Https in login theme

### ISSUE THREAD

**Issue by jdlcruz** [willianmano/moodle-theme_moove#29]
Good morning.
I have installed your theme in moodle. I have https implemented on my platform, but the main page of your theme does not appear as such.
How could you make the login of the main page of your topic have the https ?.

Thank you very much.

**Comment by willianmano** [comment]
Hi @jdlcruz , it works with boost? I have a lot of environments with HTTPS without problem.
https://ava2.uemanet.uema.br/
https://idiomas.uemanet.uema.br/
https://tecnicos.uemanet.uema.br/

**Comment by jdlcruz** [comment]
Hi @willianmano , yes, with "boost" I have https, but with the theme "moove" I am not activated.
Any recommendation?.
Thank you

**Comment by willianmano** [comment]
@jdlcruz Can you send me your environment link? We can also talk in google hangout, my email is willianmanoaraujo@gmail.com

**Comment by jdlcruz** [comment]
Hi @willianmano.

Sorry for my late response.
I have been very busy and it has been impossible for me. Finally, fix the error by updating the platform and implementing the new version of the theme.

Now I have a problem with the tours.

Thank you.
