### ISSUE TITLE
Moove theme and Google Analytics Tracking Code Update

### ISSUE THREAD

**Issue by Maddalena8** [willianmano/moodle-theme_moove#291]
In this Moodle theme, I found a section where it is possibile to enter the Google Analytics code in the format  [UA-XXXXX-Y] in order to track the platform activity. Recently, however, Google Analytics has been updated to a new version (GA4) and some things have been changed and among these also the Tracking code which is no longer in the format required by this theme. 
Will it be possible to have a theme update to fix this or is there another solution?

**Comment by t-penguino** [comment]
Thanks for the information that the GA4 code is not compatible, I will hold off from upgrading the analytics code for our GA account.

**Comment by willianmano** [comment]
Hi @Maddalena8 , thank you for report this.

Fixed in commit #3a3ccc5
