### ISSUE TITLE
Mobile and tablet responsive-ness

### ISSUE THREAD

**Issue by arryola** [willianmano/moodle-theme_moove#297]
Hi There,

I love the theme its very minimalist but it is not responsive for mobile and tablet users. First i am wondering if i can auto-hide both the left and right navigation bars because it just squishes the middle the moment its loaded. This is especially apparent for tablet users. 

Is there a way to do this via css? or perhaps customise the core theme files and set it as a custom mobile theme for moodle to load? 

pictures as attached.

Default view:
![mobile default view](https://user-images.githubusercontent.com/78449713/108292147-61b4d080-71f8-11eb-9c71-2d40ec3741d7.PNG)

Preferred view:
![mobile preferred view](https://user-images.githubusercontent.com/78449713/108292159-67aab180-71f8-11eb-892c-b2380614a342.PNG)

If this is available as a premium feature i am happy to subscribe. thank you very much in advance!

**Comment by willianmano** [comment]
@arryola first, its very unfair say that the theme is not responsive.

The theme has a setting where you can add any custom css.
