### ISSUE TITLE
Fatal error: Class 'admin_setting_scsscode' not found in .../moodle/theme/moove/settings.php on line 95

### ISSUE THREAD

**Issue by giselebrugger** [willianmano/moodle-theme_moove#3]
Hello Mano, 
Error found after installing : 
Fatal error: Class 'admin_setting_scsscode' not found in .../moodle/theme/moove/settings.php on line 95

blank page in : moodle/admin/index.php?cache=1

moodle version: 
$version  = 2016120500.03;            
$release  = '3.2+ (Build: 20161222)'; // Human-friendly version name

moove version: 1.0.4 (2017051100)Moodle 3.2
Release date: segunda, 15 Mai 2017, 13:26

**Comment by JuliaRietveld** [comment]
I have the same problem. No matter if I pull these themes (boost and bootstrapbased) from Moodle_31 or Moodle_34.
