### ISSUE TITLE
Orange footer with moodle logo

### ISSUE THREAD

**Issue by Ankit-OPCE** [willianmano/moodle-theme_moove#302]
Hi!
Unable to find any theme setting to remove the orange footer with moodle logo on all pages. Please guide.

![moodle footer](https://user-images.githubusercontent.com/80698506/111171360-dea25280-85ca-11eb-9ed7-78c8e5890bfb.png)

**Comment by willianmano** [comment]
@Ankit-OPCE now this options is available only in the premium version
