### ISSUE TITLE
Language string dont work in moove theme

### ISSUE THREAD

**Issue by ahmadsaadkhan** [willianmano/moodle-theme_moove#309]
Hello we have a two languages in our Moodle system en and ar.
The string which I have setup for English are working correctly  in theme/moove/lang/en/theme_moove 

but the strings for Arabic are not working correctly it not picking the string from Arabic strings file, it is picking it from somewhere else and I don't know where.

Same path for Arabic  theme/moove/lang/ar/theme_moove 
String name is also same in both files. 
eg.  $string['stringname'] = 'abcxyz'

I am using 
Moodle  version 3.9.5
Moove version 3.9.08
Php version 7.2.3

**Comment by ahmadsaadkhan** [comment]
?????????????????????????

**Comment by willianmano** [comment]
@ahmadsaadkhan this is not a theme issues, you are doing something wrong, maybe the name of the lang directory.
