### ISSUE TITLE
enable_read_only_sessions error with Moove on 3.11

### ISSUE THREAD

**Issue by izendegi** [willianmano/moodle-theme_moove#313]
We've detected that, if [the read_only_sessions config ](https://docs.moodle.org/311/en/Session_handling#Read_only_sessions) is enabled in the config.php, Moodle throws this error when using the Moove theme:

`error/The session caches can not be in the session store when enable_read_only_sessions is enabled. Please map all session mode caches to be outside of the default session store before enabling this features. Found these definitions in the session: core/coursecat`

It happens to us on the latest Moodle release (3.11+ (Build: 20210611)) with Moove 3.11.02

**Comment by lazydaisy** [comment]
Its strange how these things seem to happen, every now and again. One wonders if there is an error in Moodle itself.
Its ages since I have done any coding, so sorry I can't help but I am sure someone may be able to help fix the problem.

Cheers
Mary

**Comment by willianmano** [comment]
@izendegi please, detail how can I simulate the same behavior in my environment. Wich settings you are using and what pages are affected.
