### ISSUE TITLE
Login with google on startpage

### ISSUE THREAD

**Issue by patrickschaerer** [willianmano/moodle-theme_moove#32]
I really like the look of this theme, but I have a little issue.
On the startpage there is the login-window, which is really nice to have there. But when I try to login with google oauth2, I get the error "A required parameter (sesskey) was missing".
When I login without google it works fine. When I login with google on the login-page(mysite.com/moodle/login/index.php) it works fine as well.
How can I fix that?
or if that is not possible how can I remove the login-window on the start page?

**Comment by patrickschaerer** [comment]
Ok I removed the login-box on the template frontpageguest.mustache

But mabe you could help me fix the problem because I liked the feature to have a login box on the startpage

**Comment by giselebrugger** [comment]
I have the same problem:
In login moove theme with facebook login link is 
`https://giselebrugger.com/moodle/auth/oauth2/login.php?id=2&amp;wantsurl=%2F&amp;sesskey=Qtk3DJVr2T`

In login moodle (https://giselebrugger.com/moodle/login/index.php)  with facebook login is
`https://giselebrugger.com/moodle/auth/oauth2/login.php?id=2&wantsurl=https%3A%2F%2Fgiselebrugger.com%2Fmoodle%2Fauth%2Foauth2%2Flogin.php%3Fid%3D2%26amp%3Bwantsurl%3D%252F%26amp%3Bsesskey%3DQtk3DJVr2T&sesskey=Qtk3DJVr2T`

see after id=2& in moove theme have  : amp; 
and **parameter wantsurl is empty**

**Comment by willianmano** [comment]
Hi @giselebrugger @patrickschaerer thannk you for share this.
I solved that issue on the last version. Please update your theme and let me know if it works.

**Comment by patrickschaerer** [comment]
it works! Thanks

**Comment by giselebrugger** [comment]
Thank you a lot... 
Are you The Flash? :)
