### ISSUE TITLE
Tooltip responsive

### ISSUE THREAD

**Issue by pacomanval** [willianmano/moodle-theme_moove#320]
Hi, in Moove version 3.11.05 Moodle 3.11 (Build: 20210517), the tooltip of the restricted badge, not showing properly.

<img width="1334" alt="Captura de Pantalla 2021-07-01 a la(s) 17 18 06" src="https://user-images.githubusercontent.com/78818214/124195729-a5fe8a00-da90-11eb-8da5-fb50b8df0412.png">

**Comment by willianmano** [comment]
Sorry, I only support the current major version of Moodle, which is 4.0.
