### ISSUE TITLE
Disabling viewparticipants for students disarranges sidebar items and shows a bunch of errors

### ISSUE THREAD

**Issue by msr930** [willianmano/moodle-theme_moove#321]
I have disabled viewparticipants for students in site administration (moodle 3.10.1+ , moove version 2020110900); the section participants is correctly hidden for students in sidebar but course sections is moved to the end of the sidebar, while it was the first element in sidebar before hiding participants and throws a bunch of warnings at the top of the course page if debugging switched on:

Navigation node add_before: Reference node not found participants, options: badgesview grades 7 8 9 10 11 12 13 14 15 16 17 18 19 20 myhome home calendar privatefiles mycourses
line 962 of /lib/navigationlib.php: call to debugging()
line 4096 of /lib/navigationlib.php: call to navigation_node_collection->add()
line 402 of /theme/moove/lib.php: call to flat_navigation->add()
line 284 of /theme/moove/lib.php: call to theme_moove_add_coursesections_to_navigation()
line 73 of /theme/moove/layout/course.php: call to theme_moove_extend_flat_navigation()
line 1374 of /lib/outputrenderers.php: call to include()
line 1304 of /lib/outputrenderers.php: call to core_renderer->render_page_layout()
line 253 of /course/view.php: call to core_renderer->header()

**Comment by willianmano** [comment]
Sorry, I only support the current major version of Moodle, which is 4.0.
