### ISSUE TITLE
Database error 

### ISSUE THREAD

**Issue by pellix** [willianmano/moodle-theme_moove#322]
Hello, we are experiencing a problem with some users: they can not access to our Moodle. I attach a snapshot where you can see the stack trace.

We are using PostgreSQL 11 and Moodle 3.11. Boost theme is working fine.

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/468523/125272838-94c54100-e30c-11eb-90de-6eb6efe935e9.png)

Thank you!

**Comment by pellix** [comment]
Hello, as a workaround we modified the theme_moove_delete_menuitems() function from lib.php:

[...]
if (is_numeric($child->key)) {
                                        if (!theme_moove_is_course_available_to_display_in_navbar($child->key)) {
                                                $item->children->remove($child->key);
                                        }
                                }
[...]

By adding this check we avoid the error and the theme is usable, but we still don't understand why is getting a non-integer value into $child->key.

Thanks,

Oriol

**Comment by izendegi** [comment]
Hi there,

We have this same issue and the workaround proposed by @pellix works for us.

We have Moodle 3.11.1 with the latest version of Moove (3.11.05 2021052100) over PostgreSQL 12.

**Comment by willianmano** [comment]
@pellix thank you for your reply. This issue was solved in moodle 3.11 branch.
