### ISSUE TITLE
All course section is selected 

### ISSUE THREAD

**Issue by Matchikins** [willianmano/moodle-theme_moove#326]
in the course section it's painting all the items with the hover

**Comment by jasimp** [comment]
yes i am facing the same issue that with left navigation menu drawer open
Its ok with drawer closed, but all sections not visible as its is not scrolling

**Comment by Matchikins** [comment]
HI  jasimp . I solved adding these css lines in:  Site administration/Appearance/Moove/
Advanced/Raw SCSS
change the  background-color change the color to your preference

#nav-drawer .list-group .list-group-item a:hover {
    color: #fff;
    background-color:#ff7b0e;
}

#nav-drawer .list-group .list-group-item{
 
    background-color:#15355c;
}
.progress .progress-bar {
 
    background-color: #ff7b0e;
color: black;
    font-weight:bolder;
    font-family:-webkit-pictograph;

   
}
.pgr-img{
color:red;

}

**Comment by jasimp** [comment]
Thank you  Matchikins for the css solution
Its solved the drawer opened section visibility issue. Still i have the issue  with drawer closed as it showing first few sections only. its not supporting  responsiveness

**Comment by jasimp** [comment]
i enhanced the css little bit and the below code looks much better as per my theme color combination

#nav-drawer .list-group-item .list-group-item-action a:hover{
background-color: #03484d;
}
#nav-drawer .list-group-item .list-group-item-action .active{
background-color: #0599a4;
}

the drawer closed section visibility issue also found a solution by css by changing the height to 400-600px but need to check different devices

**Comment by willianmano** [comment]
Sorry, I only support the current major version of Moodle, which is 4.0.
