### ISSUE TITLE
Some users cannot login - Moove 3.11.05 + Moodle 3.11.2

### ISSUE THREAD

**Issue by erickmelo** [willianmano/moodle-theme_moove#328]
We are facing a problem with the template for some users who cannot log into moodle. The problem started to occur after we updated our environment to the latest version of Moodle and Moove.

Environment:
- Moodle: 3.11.2
- Moove: 3.11.05

To identify the root of the problem, we switched the template to Boost and the problem disappeared. Users are now able to authenticate themselves. This seems to us an indication that the problem is in fact associated with moove.

Follow the stacktrace

```
Debug info: ERROR: invalid input syntax for type bigint: "courseindexpage"
SELECT * FROM mdl_course WHERE id = $1
[array (
0 => 'courseindexpage',
)]
Error code: dmlreadexception
Stack trace:

    line 486 of /lib/dml/moodle_database.php: dml_read_exception thrown
    line 329 of /lib/dml/pgsql_native_moodle_database.php: call to moodle_database->query_end()
    line 977 of /lib/dml/pgsql_native_moodle_database.php: call to pgsql_native_moodle_database->query_end()
    line 1671 of /lib/dml/moodle_database.php: call to pgsql_native_moodle_database->get_records_sql()
    line 1643 of /lib/dml/moodle_database.php: call to moodle_database->get_record_sql()
    line 1622 of /lib/dml/moodle_database.php: call to moodle_database->get_record_select()
    line 390 of /theme/moove/lib.php: call to moodle_database->get_record()
    line 372 of /theme/moove/lib.php: call to theme_moove_is_course_available_to_display_in_navbar()
    line 282 of /theme/moove/lib.php: call to theme_moove_delete_menuitems()
    line 70 of /theme/moove/layout/columns2.php: call to theme_moove_extend_flat_navigation()
    line 1396 of /lib/outputrenderers.php: call to include()
    line 1326 of /lib/outputrenderers.php: call to core_renderer->render_page_layout()
    line 1950 of /lib/setuplib.php: call to core_renderer->header()
    line 2807 of /lib/weblib.php: call to bootstrap_renderer->__call()
    line 93 of /course/loginas.php: call to notice()
```

**Comment by Al3xBRx** [comment]
Olá Erick!

O desenvolvedor do tema Moove, Willian Mano Araújo,  já atualizou o código fonte aqui no Git, mas ainda não atualizou no repositório do Moodle.org.
Estava com o mesmo problema que você. O erro acontecia com usuários que estavam inscritos em mais de 10 cursos. Mas, esse problema foi solucionado despois que atualizei minha aplicação para a última versão que está disponível aqui no Git.

`<hr>`

Hi Erick!

The developer of the Moove theme, Willian Mano Araújo, has updated the source code here on Git, but he hasn't updated it in the Moodle.org repository yet.
I had the same problem as you. The error occurred with users who were enrolled in more than 10 courses. But, this issue was fixed after I updated my application to the latest version which is available here on Git.

**Comment by sebastiangz** [comment]
The version fix that you mentioned makes changes in what files?

**Comment by willianmano** [comment]
Sorry, I only support the current major version of Moodle, which is 4.0.

**Comment by dasistwas** [comment]
@erickmelo you can replace the file theme/moove/lib.php with the one attached (extract it from the zip). I added a line, that should fix the problem. It is a quick fix, there might be more elegant solutions but it works.

[lib.zip](https://github.com/willianmano/moodle-theme_moove/files/8920743/lib.zip)
:

From line 370:
```
        if ($item->key === 'mycourses') {
            foreach ($item->children as $key => $child) {
                if ($child->key == "courseindexpage") {
                        break;
                }
                if (!theme_moove_is_course_available_to_display_in_navbar($child->key)) {
                    $item->children->remove($child->key);
                }
            }
        }

```
New code:
```
                if ($child->key == "courseindexpage") {
                        break;
                }
```
Maybe better solution:
```

                if (!is_int($child->key)) {
                        break;
                }
```
