### ISSUE TITLE
404 error for emoji category in emoji picker of massaging box

### ISSUE THREAD

**Issue by mojtaba82** [willianmano/moodle-theme_moove#329]
In moodle 3.11.2 and moove 3.11.05 I have these 404 errors
https://mysite/theme/image.php/moove/core/1628893047/i/emojicategorypeoplebody 404
https://mysite/theme/image.php/moove/core/1628893047/i/emojicategorysmileysemotion 404
Actully in messaging in emoji picker these two category emoji is based on image and another category emojies are based on font-awesome

**Comment by azmatksa** [comment]
Hi I'm facing same issue, if we disable the emoji picker from the Advanced settings then it will be disapperaed!

**Comment by willianmano** [comment]
Sorry, I only support the current major version of Moodle, which is 4.0.
