### ISSUE TITLE
Settings menu (cog) missing in activities

### ISSUE THREAD

**Issue by marmaou** [willianmano/moodle-theme_moove#330]
Settings menu (cog) is messing in activities, such as, forum, assignments, quiz, book, etc, if course does not appear in "My active courses" list.

Users (teachers, admins) do not see settings menu (cog) for courses that are not active.
Menu appears when reverting to Boost theme or by changing course start or end dates.

Moodle version 3.11.2+ (Build: 20210812)
Moove version 3.11.05

**Comment by marmaou** [comment]
For admin users only if enrolled as teachers to such a course.

**Comment by izendegi** [comment]
Hi,

We've experienced that same issue and the proposed patch fixes it, thank you @marmaou !
