### ISSUE TITLE
Question: course topics format

### ISSUE THREAD

**Issue by VOOM108** [willianmano/moodle-theme_moove#333]
Moodle 3.9.8 Moove Premium

The course topics format shows as a grid format without further options. I need the regular topics format with sections in full width. 

If it is being replaced by Moove I wonder why not add the grid format as an additional option and leave the regular topics format as it is.  

Now I might need to change 150 courses to another course format (that displays similar to the default topics format like the flexible sections format) because the topics format has been changed. Is there any other way?

**Comment by VOOM108** [comment]
Sorry, did not see the option "blank issue" and cannot delete the label "bug" any more...

**Comment by willianmano** [comment]
Sorry, I only support the current major version of Moodle, which is 4.0.
