### ISSUE TITLE
Question: cannot activate licence

### ISSUE THREAD

**Issue by VOOM108** [willianmano/moodle-theme_moove#334]
We bought Premium but when saving the page with the licence key, it keeps saying the licence is not valid (red badge and persistent red alert box). Does the activation-process use any unusual port?

**Comment by bts0004** [comment]
We're having the exact same problem and haven't been able to move past it. Were you able to resolve it @VOOM108?

**Comment by willianmano** [comment]
I am closing this because here are the place to report issues related to the free version of the plugin.
