### ISSUE TITLE
Appearance / Additional HTML

### ISSUE THREAD

**Issue by anisj** [willianmano/moodle-theme_moove#338]
Hi All,

Kindly, after adding code to "Additional HTML" it is not shown on front page.

Moodle 3.11.2+
Moove 3.11.05

thank you.
Anis

**Comment by tiagojulianoferreira** [comment]
Make sure you don't include this HTML in the HEAD section. In many cases you will want additional HTML to load after the site content so adding it to the Before BODY is closed field may be the best option.

**Comment by willianmano** [comment]
Sorry, I only support the current major version of Moodle, which is 4.0.
