### ISSUE TITLE
Custom menu is missing in mobile view.

### ISSUE THREAD

**Issue by michael-milette** [willianmano/moodle-theme_moove#339]
**Description**
The custom menu which appears at the top of the screen in desktop view is completely missing when viewed on a mobile device.

**To Reproduce**

1. Go to Site Administration > Appearance > Theme Settings
2. Scroll down to the **Custom menu items** field and add the following:

```
Home|/?redirect=0
All courses|/course/
Course search|/course/search.php
Top level|https://someurl.xyz/toplevel.html
-Second level A|https://someurl.xyz/level2a.html
-###
-Second level B|https://someurl.xyz/level2b.html
FAQ|https://someurl.xyz/faq
Contact us|/https://someurl.xyz/contact.html
```

3. Save and then refresh the page to ensure the changes to the top menu are visible.
4. Narrow the browser to the size of a mobile device.
5. Notice that the content of the side menu is nowhere to be found, either in the web page or in the side navigation drawer.

**Expected behavior**
I expected the top custom menu to be visible somewhere when viewed on a mobile device, ideally included in the side navigation drawer - which is where people would traditionally expect to find the menu it on most websites IMHO (unlike Boost which inserts it in the footer of the page).

**Environment**
 - Moodle version: 3.11+ (Build: 20210527)
 - Moove version: 3.11.05 (Build: 2021052100)
 - Browser: Chrome

Let me know if you have any questions.

Best regards,

Michael

**Comment by SimonAwiti** [comment]
Hello, did you find a solution to this?

**Comment by michael-milette** [comment]
Unfortunately I ended up going with a different theme that had better support for mobile devices.
