### ISSUE TITLE
"My courses" link is not having "href" attribute

### ISSUE THREAD

**Issue by sreepathy** [willianmano/moodle-theme_moove#34]
Hi,
Your moove theme is absolutely nice. A big thank you for your efforts!
I have installed it in my moodle 3.4 (PHP 7.1/Mysql 5.7.13 X64/Windows 2012 R2 Std). But I am facing a few issues. Your help is highly appreciated (I am a newbie to moodle. Pardon me)
 
2. When I am logging in as a student /teacher, the "My Courses" link on the left panel is not having "href" attribute. Hence the option is not working. 

Please help.

**Comment by willianmano** [comment]
@sreepathy This is the Moodle's default behavior.
