### ISSUE TITLE
Keyboard tabbing goes into language selection menu and user menu when not open

### ISSUE THREAD

**Issue by michael-milette** [willianmano/moodle-theme_moove#340]
**Description**
When using a keyboard to tab through the page, the focus goes into the language menu and the user menu in the top menu even though these menus are not open. As a result, the focus indicators temporarily disappear. **This is an accessibility issue.**

**To Reproduce**

1. Go to Site Administration > Language Packs
2. Add a language or two to the default language pack already installed.
3. Using exclusively a keyboard, tab through the page. When you get to the globe, pressing tab one more time causes the the focus indicator box disappears.
4. Keep pressing the tab key until the focus indicator re-appears.
5. Continue to press the tab key repeatedly and notice that the same thing happens when you get to the user menu.

**Expected behavior**
I expected the same behaviour to occur as it does if you are tabbing through the custom menu. If the dropdown menu is not open, tabbing should continue directly to the adjacent menu item, not go into invisible dropdown menus.

**Environment**
 - Moodle version: 3.11+ (Build: 20210527)
 - Moove version: 3.11.05 (Build: 2021052100)
 - Browser: Chrome

Let me know if you have any questions.

Best regards,

Michael

**Comment by willianmano** [comment]
Sorry, I only support the current major version of Moodle, which is 4.0.
