### ISSUE TITLE
Allow scrolling through my courses dropdown

### ISSUE THREAD

**Issue by tessa-fabry** [willianmano/moodle-theme_moove#342]
**Is your feature request related to a problem? Please describe.**

Allow scrolling through 'my courses' dropdown while side drawer is collapsed:

If a user is enrolled in a lot of courses, the 'my courses' dropdown that pops out when you hover on the icon while the side drawer is collapsed cuts off at the bottom of the browser window and there is no way to scroll to see all the courses. 

**Describe the solution you'd like**

When you hover over this dropdown it should scroll through the list of courses. 

-this would mean changing the height of the dropdown from auto to either be a fixed height or cut off at the bottom of the browser window. At them moment it is height: auto, so there's no scroll option because technically there's no overflow.

**Describe alternatives you've considered**
Another option could be to allow the entire side drawer to scroll while collapsed.

**Additional context**
![Screenshot from 2021-11-05 13-26-41](https://user-images.githubusercontent.com/76080108/140448172-63b05baf-506e-4e49-82eb-fbf81543b8ea.png)

**Comment by willianmano** [comment]
Sorry, I only support the current major version of Moodle, which is 4.0.
