### ISSUE TITLE
Google Analytics Vs Matomo

### ISSUE THREAD

**Issue by jmd87fr** [willianmano/moodle-theme_moove#345]
**Describe the solution you'd like**

Hi William, 
I dont like to use Google Analytics. I love Matomo (Piwix)  https://matomo.org/ 
How can use my matomo ID in advanced setting instead of  Google ID?  

Bests

_Thank you for your hard work with the 4.0_  ;-)

**Comment by tiagojulianoferreira** [comment]
Hi! I haven't tried Motomo yet but I think the logic is similar to Google Analytics, so in that case you can copy Matomo's tracking scripts to the HEAD section of the Moodle site.

This is quite simple to do using additionalhtmlhead in Site administration/Appearance/Additional HTML

**Comment by jmd87fr** [comment]
oops Tiago I forgot to said 'Thank you' ;-) 
I close

**Comment by willianmano** [comment]
Sorry, I only support the current major version of Moodle, which is 4.0.
