### ISSUE TITLE
Erro 404 nas fotos de usuários

### ISSUE THREAD

**Issue by sergiocneto** [willianmano/moodle-theme_moove#347]
Moodle 3.11.4+ (Build: 20211230)
theme_moove | 3.11.052021052100

Após atualização do Moodle e do tema Moove, não estão mais aparecendo as fotos da maioria dos usuários, dando erro 404. De alguns ainda aparece, mas da maioria não.

Um exemplo de imagem que dá erro 404: (...)/pluginfile.php/66567/user/icon/moove/f1?rev=807041

O caminho das imagens que funcionam é parecido, não consegui identificar um padrão.

**Comment by willianmano** [comment]
Sorry, I only support the current major version of Moodle, which is 4.0.
