### ISSUE TITLE
Error - configuration icon of any activity is not displayed

### ISSUE THREAD

**Issue by diegomejia071** [willianmano/moodle-theme_moove#348]
Hi,

![image](https://user-images.githubusercontent.com/21009904/149841119-ba7feb7e-53a8-4fdc-9396-f0cc0cfa33ea.png)

I have a problem with Moodle version 3.11.4 and Moove theme version 3.11.05.

When assigning a user with the teacher role with editing permission, they cannot see the gear or the configuration icon within the activities, it disappears immediately this role is assigned.

But when I assign the user the role of teacher with editing permission, the configuration icon of any activity is not displayed.

![image](https://user-images.githubusercontent.com/21009904/149841176-f221e87f-e740-4210-9603-9beebd1db54b.png)

**Comment by willianmano** [comment]
Sorry, I only support the current major version of Moodle, which is 4.0.
