### ISSUE TITLE
Accessibility bar isn't visible on the home page

### ISSUE THREAD

**Issue by webstarspro** [willianmano/moodle-theme_moove#349]
I'm building a website for disabled people. I need to use an accessibility bar.
It must be visible all the time automatically enabled for everyone, not manually enabled.

How to do this?
I can't find any option.

I see that this bar is visible only after logging in. It's useless.

If any person with disability enters into my website - he/she must see an accessibility bar, in order to change the font or contrast.

**Comment by willianmano** [comment]
Sorry, I only support the current major version of Moodle, which is 4.0.

**Comment by webstarspro** [comment]
In January, when I asked - there were no 4 version but your theme existed.
Why are you asking after 6 months?

**Comment by willianmano** [comment]
@webstarspro because I do not receive any money or investment to keep the project, so, I am sorry because I was not available.

**Comment by webstarspro** [comment]
If you do not receive any money or investment to keep the project - I would consider to close this project.
Even if your theme if free of charge - it's publicly available and people always will expect support and changes.
6 months ago I was ready to pay for your service....but no one replied.
I paid to another person. We modified your scripts.

Accessibility bar is visible only after logging in. It's completely useless.
If someone has problem with eyes and seeing - the acccesibility bar must be visible at the main page.
