### ISSUE TITLE
Strings for marketing spots

### ISSUE THREAD

**Issue by syedhameed** [willianmano/moodle-theme_moove#35]
Hello @willianmano, The strings for the marketing spot url's for different number don't match together.

$string['marketing2url'] = 'Marketing1 URL';
$string['marketing2urldesc'] = 'Enter Marketing1 URL';

$string['marketing3url'] = 'Marketing1 URL';
$string['marketing3urldesc'] = 'Enter Marketing1 URL';

$string['marketing4url'] = 'Marketing1 URL';
$string['marketing4urldesc'] = 'Enter Marketing1 URL';

Thanks Hameed

**Comment by willianmano** [comment]
Thanks @syedhameed for reply this.
