### ISSUE TITLE
";" in login page

### ISSUE THREAD

**Issue by omder1** [willianmano/moodle-theme_moove#350]
in login page, i have ";" in the top 
help please ! 

![image](https://user-images.githubusercontent.com/25952721/153747643-cd2f0b80-3ef0-4ed3-bc08-bc0d342186fb.png)

**Comment by omder1** [comment]
pour éliminé cette erreur il faut supprimer le code Google analytique N4 sur les paramètres avancés de thème moove

**Comment by tiagojulianoferreira** [comment]
Nice! Your issue helped me get around this and keep track of metrics. What I did was include the script directly in the HEAD section of the moodle site.

```
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-XXXXXXXX"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-XXXXXXXX');
</script>

```

**Comment by willianmano** [comment]
Sorry, I only support the current major version of Moodle, which is 4.0.
