### ISSUE TITLE
Bootstrap Card Decks aren't fully responsive on the dashboard.

### ISSUE THREAD

**Issue by tim1mw** [willianmano/moodle-theme_moove#353]
**Describe the bug**
Bootstrap card decks within blocks in the main part of the dashboard never display with more than 2 columns, regardless of the number of cards or width of the screen. This causes some very elongated blocks on widescreen monitors, including in the standard Course Overview and Recently accessed courses blocks. The Moodle site I maintain also has a custom block that make use of card decks, which adapt perfectly with Boost, but didn't render well with Moove, to the extent that this bug was a show-stopper for deployment of the Moove theme.

**To Reproduce**
Add the Course Overview and/or Recently accessed courses blocks to the Dashboard, ensure you are testing with a user that is registered for more than two courses. Resize the window to varying sizes, the card deck in these blocks will not adapt to the larger screen size by adding columns.

**Expected behaviour**
The number of columns will adapt to the screen size, as they do when using the standard Boost theme.

**Your environment (please complete the following information):**
 - Moodle version: 3.9.12 (Build: 20220117)
 - Moove version 3.9.08/2020071900
 - Browser Firefox

**Proposed Fix**

Putting the following CSS into the Advanced>Raw SCSS box allows for three and four column card desks, (although there may be a better way to do this and the min-width may need some tweaking):

```
@media (min-width: 576px) {
      .pagelayout-mydashboard .card-deck .card {
    flex-basis: calc(100% - .5rem);
  }
}

@media (min-width: 850px) {
      .pagelayout-mydashboard .card-deck .card {
    flex-basis: calc(100% - .5rem);
  }
}

@media (min-width: 1100px) {
      .pagelayout-mydashboard .card-deck .card {
    flex-basis: calc(50% - .5rem);
  }
}

@media (min-width: 1350px) {
      .pagelayout-mydashboard .card-deck .card {
    flex-basis: calc(33.33% - .5rem);
  }
}

@media (min-width: 1600px) {
      .pagelayout-mydashboard .card-deck .card {
    flex-basis: calc(25% - .5rem);
  }
}
```
Ideally these styles need to be sensitive to the width of the main block region, rather than just the width of the browser window, since the right hand block column can be hidden. However, the magic incantation of CSS needed to achieve that is escaping me.

**Comment by willianmano** [comment]
@tim1mw you can create a PR with the code.

**Comment by willianmano** [comment]
Sorry, I only support the current major version of Moodle, which is 4.0.
