### ISSUE TITLE
Moove Theme: Home Page Image

### ISSUE THREAD

**Issue by JoaoFerreira1969** [willianmano/moodle-theme_moove#354]
![Imagem frontal do Moove](https://user-images.githubusercontent.com/102545482/160461251-e831b1d7-0c81-4e6a-acc5-0498b85e39c1.jpg)
Please do not interpret it as a complaint, more as a comment for the product to be improved, nothing more than that.

I can't find in the configuration structure the image change of the home page where the user logs in, because within the configuration structure there is a place to replace the footer image. As you can see in the photo, only the logo and images already established by Moove appear on the home page. Also no option to change colors where it has the description "PROUDLY MADE WITH MOODLE", could have a color selection option, to match the colors of the page logo. In my case it is a gold background and the description is black or vise e versa, since this icon at the bottom of the page cannot be removed as before. Could allow the change of color, at least, I agree with the fixation of the developers' information after all and a way to publicize your work.
Link to post with answer suggesting it is recommended to you: https://moodle.org/mod/forum/discuss.php?d=432213
Congratulations on the work done, thank you in advance.
**Your environment (please complete the following information):**
 - Moodle version: [e.g.Moodle 3.11+ (Build: 20210527)]

**Comment by willianmano** [comment]
Sorry, I only support the current major version of Moodle, which is 4.0.
