### ISSUE TITLE
Moove sugestão rede sociais.

### ISSUE THREAD

**Issue by JoaoFerreira1969** [willianmano/moodle-theme_moove#355]
Há mais uma sugestão para melhorar o Moove e ele fica top.
E sobre as redes sociais, se pudesse deixar os ícones abertos para que o usuário escolhesse qual rede utilizar .
 Exemplo: Sou da área de professor na área de gestão financeira, meus alunos estão no linkedin, telegram, GETTR, Twitter, WhatsApp e outras.
Como eu falei é só mais uma sugestão de aperfeiçoamento de uma ferramenta que já é muito boa, mas saber como é que é sempre podemos melhorar o está bom, pois tecnologia e como a mente humana não tem limite para explorar e aperfeiçoar.

**Comment by willianmano** [comment]
O problema de deixar abertas as redes é que não possuem ícones dela na biblioteca de ícones que o moodle usa, mas a idéia é boa sim. Muito obrigado por colaborar.
