### ISSUE TITLE
Remove title from section 0 

### ISSUE THREAD

**Issue by ajaykulkarni01** [willianmano/moodle-theme_moove#356]
Hello, I want to remove the title of the section 0. If I use following CSS:

#page-course-view-topics .course-content .section .sectionname {
    display: none !important;
}

it works But it also removes all the topics titles. I just want to remove the section 0 title. Can you please help?

FYI - I'm using Topics Format with one section per page.

**Comment by willianmano** [comment]
Sorry, I only support the current major version of Moodle, which is 4.0.
