### ISSUE TITLE
Moove creates a database error for users with too much courses

### ISSUE THREAD

**Issue by ralfhilg** [willianmano/moodle-theme_moove#358]
Users who are enrolled in too many courses get a database error  when logging in. I.e. when 'Course limit navcourselimit' is set to 10 (default) and a user has more than 10 courses s/he can't login. Its required to set the number of courses higher. This is an unexpected behaviour.  Can you please check and change. 
Tested with moodle 3.11.

**Comment by willianmano** [comment]
Sorry, I only support the current major version of Moodle, which is 4.0.
