### ISSUE TITLE
"Total Users" count on dashboard includes deleted users

### ISSUE THREAD

**Issue by XavierClarke** [willianmano/moodle-theme_moove#36]
The "Total Users" count on the dashboard includes deleted users.  Technically, the count is correct but a little misleading when one browses their list of users.  Since there is currently no way to see deleted users in the Moodle UI, wouldn't it be better to exclude deleted users from the "Total Users" count?

**Comment by willianmano** [comment]
@XavierClarke Thanks for this warning. May I need to remove the suspended accounts counting too?

**Comment by XavierClarke** [comment]
That's a good question.  I was wondering about that too.  One solution could be to break out the counts by having "Active Users", "Suspended Users", and "Deleted Users" counts.  I would assume that "active" would only include non-deleted, non-suspended users (minus the guest account).  In that way, it would match the default list of users when browsing a list of users.

**Comment by XavierClarke** [comment]
Making the minimal changes to your current layout, maybe the User count block could look something like: 

10 (7/2/1)
Total Users (Active/Suspended/Deleted)


By the way, I really like your theme.  Nice job!

**Comment by willianmano** [comment]
@XavierClarke I was thinking in something like this. My concern it's about to have too much information in a small place. I think active/deactive(suspended/deleted) is a better approach.

**Comment by XavierClarke** [comment]
@willianmano I agree that it is a lot of information in a very small space.

Since there is no way to see or count deleted users using the Moodle UI, you could probably ignore them.  So it would probably be fine just to show Active and Suspended counts.  That would match what an admin would see if they browsed/counted the list users in Moodle UI.  Of course you would probably want to exclude the guest account also, which I think you are already doing.  Another suggestion, since there is limited space, would be just to show a count of Active users instead of the Total users.

**Comment by willianmano** [comment]
Hi @XavierClarke thank you very much for your advices and sorry for my late reply. I updated the theme and in this new version I removed the count of removed users and added the suspend counting. See the attached image.
![screenshot from 2017-12-13 18-10-42](https://user-images.githubusercontent.com/233643/33962645-04062bca-e031-11e7-8200-f642610a4c34.png)

**Comment by willianmano** [comment]
Hi @XavierClarke thank you very much for your advices and sorry for my late reply. I updated the theme and in this new version I removed the count of removed users and added the suspend counting. See the attached image.
![screenshot from 2017-12-13 18-12-14](https://user-images.githubusercontent.com/233643/33962703-2d5042b8-e031-11e7-8ee3-6200cf83de65.png)

**Comment by XavierClarke** [comment]
@willianmano  Awesome!  I look forward to installing the new version.

**Comment by XavierClarke** [comment]
@willianmano 
I just installed the latest build and there is one small issue.  **It looks like you are not excluding deleted users from your "Suspended" count.**

Here's are the "Active" and "Suspended" queries that I used to test the counts:

```
--
--Active Users
--
SELECT 
	count(*) "Active Users"
FROM
	mdl_user
WHERE 
	deleted = 0
	AND suspended = 0
	AND username <> 'guest';

--
--Suspended Users
--
SELECT 
	count(*) "Suspended Users"
FROM 
	mdl_user
WHERE 
	deleted = 0
	AND suspended = 1
	AND username <> 'guest';

```
