### ISSUE TITLE
 Topic display error

### ISSUE THREAD

**Issue by luisandoval** [willianmano/moodle-theme_moove#360]
**Describe the bug**
The error occurs when viewing the topics of each course these are displayed in the form of a list despite the fact that the MOOVE topic is selected. Test clean Moodle installations with MOOVE on multiple servers (with different features) but the same thing is still happening.

**To Reproduce**
---

**Expected behavior**
Activate the grids when viewing each of the topics 

**Screenshots**
![MOOVE_ISSUE](https://user-images.githubusercontent.com/6148582/166718487-ae7a4aef-2c26-46b2-beb8-9913503f34b9.png)

**Your environment (please complete the following information):**
 - Moodle version: Moodle 3.11.6+ (Build: 20220429)
 - Moove version: 3.11.05 (Build: 2021052100)
 - Browser: Vivaldi, Google Chrome, Microsoft Edge, [FireFox]

**Additional context**
This issue started to occur since moodle version me 3.11.6 and persists in 3.11.6+

**Comment by willianmano** [comment]
Sorry, I only support the current major version of Moodle, which is 4.0.
