### ISSUE TITLE
Navegation in admin page

### ISSUE THREAD

**Issue by proftug4** [willianmano/moodle-theme_moove#361]
**Describe the bug**
No navegation in admin panel/page

**To Reproduce**
Go to site administration

**Expected behavior**
Show option to navigate trough the menu

**Screenshots**
![image](https://user-images.githubusercontent.com/20543813/169042140-885c3c4d-f8bc-4a27-aa98-8249416a4455.png)

**Your environment (please complete the following information):**
 - Moodle version:4.0.1 (Build: 20220509)]
 - Moove version 3.11.05 (Build: 2021052100)
 - Browser:  Edge

**Comment by security-companion** [comment]
@proftug4 Check my Pull request #362 to see if it solves your problem.

**Comment by proftug4** [comment]
> 

will check and report

**Comment by proftug4** [comment]
![image](https://user-images.githubusercontent.com/20543813/170999289-49345a5f-2937-4e16-8fed-c6ae1e368fb2.png)
Working

**Comment by willianmano** [comment]
Use the version for moodle 4.0.
