### ISSUE TITLE
Class 'theme_moove\output\core\lang_string' not found 

### ISSUE THREAD

**Issue by szygmon** [willianmano/moodle-theme_moove#363]
At page _mymoodle.com/?redirect=0_ with category of course (home page moodle) was error:
Exception - Class 'theme_moove\output\core\lang_string' not found

[Więcej informacji o tym błędzie](http://docs.moodle.org/400/pl/error/moodle/generalexceptionmessage)

**Your environment (please complete the following information):**
 - Moodle version: 4.0 (Build: 20220419
 - Moove version: main from GitHub 23.05.2022 
 - Browser Chrome

**Comment by angar321** [comment]
I received this same error and was able to resolve it by adding \ in front of lang_string on line 96 of /theme/moove/classes/output/core/course_renderer.php

I got the idea from the second post on this thread: https://moodle.org/mod/forum/discuss.php?d=364190

Sorry but I have never used github, so hopefully somebody else can submit the change here, or whatever else is needed.

**Comment by willianmano** [comment]
Use the version for moodle 4.0
