### ISSUE TITLE
`Login page background` setting is ignored

### ISSUE THREAD

**Issue by mmn6d6d6e** [willianmano/moodle-theme_moove#366]
**Describe the bug**
On ```Site administration > Appearance > Themes > Moove``` there is setting to configure ```Login page background```.
But whatever image uploaded it still shows default image.

**To Reproduce**
1. Go to ```Site administration > Appearance > Themes > Moove```
2. Scroll to ```Login page background```
3. Upload new images. Then click ```Save changes```
4. Logout > go to front page. Still uses default image.

**Expected behavior**
It should use the uploaded image.

**Your environment (please complete the following information):**
 - Moodle version: 3.11.7+ (Build: 20220610)
 - Moove version: 3.11.05 (2021052100)
 - Ms Edge

**Additional context**
Tried on fresh installation. The result still the same.

**Comment by willianmano** [comment]
Sorry, I only support the current major version of Moodle, which is 4.0.
