### ISSUE TITLE
Some questions ;-) 

### ISSUE THREAD

**Issue by jmd87fr** [willianmano/moodle-theme_moove#368]
Hello
A very good job : theme Moove for Moodle 4.0 👍

Some questions please : 

- how can I change the texts 'Contact us' and 'Follow us' in french language?
- Do you you dropped the accessibility buton? :-( 
- No more text in the 'sliderimage' ?
- How change text (in french) in the 'numbersfrontpage' ? 
- I don't understand this numbers ? it's not that I have on my site?  How can I change them? (if it is possible ;) )

Thank you a lot Wiliam

**Comment by willianmano** [comment]
@jmd87fr 

- Languages strings need to be translated on Moodle Lang site: https://lang.moodle.org
- No, the button was moved to the user menu, top right side.
- No
- Languages strings need to be translated on Moodle Lang site: https://lang.moodle.org
- These numbers are getting from your sites, directly from the database.
