### ISSUE TITLE
Missing breadcrumb thread for some forum 

### ISSUE THREAD

**Issue by Cbarneron1** [willianmano/moodle-theme_moove#369]
Hey 
I have a problem with my Moodle and your theme. 
We don’t have a breadcrumb and a parameter icon for different forums and discussions with some users, but for others, we have breadcrumb threads.
 Where did it come from?

 - Moodle Version: 3.11.6 (Version: 20220314)
 - Moove version: 3.11.05 ( Version:2021052100)
 - Browser: chrome , firefox
![Thème_boost](https://user-images.githubusercontent.com/97873397/174807876-0d69ebb7-a785-4980-b20d-f9ab012fdda2.png)
![Thème_moove](https://user-images.githubusercontent.com/97873397/174807879-db7f439e-31cb-47d6-b29b-bdf3f401118a.png)

We don’t have this problem with other themes like boost
Could you provide a solution to our problem, I attach the example capture
Thank you

**Comment by willianmano** [comment]
I only suppor most Moodle's version, in this case, moodle 4.
