### ISSUE TITLE
Dashboard's Suspended user count should exclude delete users

### ISSUE THREAD

**Issue by XavierClarke** [willianmano/moodle-theme_moove#37]
@willianmano 
_Looks like I responded too late to the previous issue,  I just copied and pasted my previous post here._

I just installed the latest build and there is one small issue.  **It looks like you are not excluding deleted users from your "Suspended" count.**  I just happened to notice it because I have deleted users that were suspended and they were showing up in the "Suspended" count.

In mydashboard.php, this small change is needed:

From
`$totalsuspendedusers = $DB->count_records('user', array('suspended' => 1));`
to
`$totalsuspendedusers = $DB->count_records('user', array('deleted' => 0, 'suspended' => 1));`

**Comment by willianmano** [comment]
@XavierClarke thank you again. I made this change and will upload to moodle.org in the next release.
