### ISSUE TITLE
Course custom fields

### ISSUE THREAD

**Issue by jmd87fr** [willianmano/moodle-theme_moove#370]
Hello Willian, 
How are you ?

In the course setting I use : 
- Course custom fields
- Role renaming (manager= 'Responsable de formation' and teacher='Formateur')

On the home page, in the Course cards : 
I don't show : 
- course customs fields
- names of role 'Manageur' ,'Formateur'
I show : 
- avatar + first name+ last name of people who have a role
  
I attached 2 screenshot from home page

Bests Regards

**Comment by willianmano** [comment]
@jmd87fr thank you for reporting this. I just added a commit with the solution for this issue.

**Comment by jmd87fr** [comment]
Hello William,
thank you :-)

I installed your last package : see attached screenshot

- I don't like the gray back groud :-(  see grey.jpg file attached  

> you can stay in with with text in bold (like in boost see bold.jpg file attached 
- the role names are not display (course > setting > role renaming see grey.jpg file attached 


A another small stuff : the rate of course conpletion : 

- OK on my courses pages
- NOK (no tranlation) on home page  see home.jpg attached file


![grey](https://user-images.githubusercontent.com/5038301/175787145-16fd94f5-0824-4346-bba9-b4cc55ae6b36.jpg)

![bold](https://user-images.githubusercontent.com/5038301/175787144-6efa6ec9-837a-4f05-8d9c-aca9423a34fb.jpg)

![home](https://user-images.githubusercontent.com/5038301/175787146-ae7c3f56-5b8f-424f-b796-a17321e073a9.jpg)

I send via AMOS all strings for french language...  ;-) 

Best regards

**Comment by willianmano** [comment]
@jmd87fr Take a look on the new improvements.

<img width="376" alt="Captura de Tela 2022-07-01 às 14 43 09" src="https://user-images.githubusercontent.com/233643/176945053-4255d720-a4ae-4fb5-9c60-850e4bb1c6bb.png">
