### ISSUE TITLE
Botão "Modificar perfil"

### ISSUE THREAD

**Issue by jrneo** [willianmano/moodle-theme_moove#371]
**Erro ao clicar no botão "Modificar perfil"**

**To Reproduce**
1. Faça o logon '...'
2. Clique no seu nome '....'
3. Clique no link "Perfil" '....'
4. Clique no botão "Modificar perfil"
5. Veja o erro

**Expected behavior**
Espera-se que a tela de perfil seja apresentada para a alteração.

**Screenshots**
A captura de tela em anexo demonstra o erro.

**Your environment (please complete the following information):**
 - Moodle version: [e.g.Moodle [4.0.1+ (Build: 20220617)]
 - Moove version [e.g. Moove 4.0.4 (Build: 2022062002)]
 - Browser Chrome e Firefox

**Additional context**
Ao clicar no botão "Preferências", o link "Modificar perfil" funciona normalmente.
![erro moove](https://user-images.githubusercontent.com/4430212/175953524-6898348f-7b1a-47b3-bde5-0b3da041c1d2.jpg)

**Comment by willianmano** [comment]
@jrneo obrigado por reportar. Você poderia por favor habilitar o debug e enviar o print com a mensagem de erro mais detalhada?

**Comment by jrneo** [comment]
Olá Mano, tudo bem?
O debug não apresentou erros. Veja o vídeo:
https://www.loom.com/share/4df1205daaed49578dd928d2c1639a9a
Acredito que seja algo relacionado com permissões.

**Comment by willianmano** [comment]
@jrneo Obrigado por reportar o erro, acabei de resolvê-lo.
