### ISSUE TITLE
Settings menu unavailable at activity level when out of course date

### ISSUE THREAD

**Issue by sioc** [willianmano/moodle-theme_moove#372]
Go to any course and adjust beginning or end date so that it's "unavailable".

As an editing teacher, go to any activity (I checked announcement forum and quiz). The gear icon to the settings menu is not displayed.

![image](https://user-images.githubusercontent.com/98491947/176010863-c6e197fc-ad46-47f0-bb6e-fe0fc10d7a2d.png)

 - Moodle version: 3.11.7
 - Moove version: 3.11.05 (2021052100)
 - Browser: Firefox and Chrome

**Comment by willianmano** [comment]
@sioc thanks for report this, but we only support the version for the most recent Moodle, in this case, Moodle 4.0.
