### ISSUE TITLE
Loose of language setting

### ISSUE THREAD

**Issue by jmd87fr** [willianmano/moodle-theme_moove#373]
Hi Willian,

someting strange: 

My moodle is in french language. 

1. I put the language setting : english
3. my site is in english 
4. I go to the home page 
5. I visit a course
6. I loose the language setting and the site is in french language. 
7. I go to the home page
8. I have the language setting:  english: the site is in english.

**Comment by willianmano** [comment]
@jmd87fr I was not able to reproduce it here. =/

**Comment by jmd87fr** [comment]
Very stange!

with :
moodle Moodle 4.0.1+ (Build: 20220701)
Firefox 102.0 (64 bits) 
Opera Version :88.0.4412.53
Brave Version 1.40.109 Chromium: 103.0.5060.66

The same bug :-(
I'll ask the french community on moodle.org and I'll keep you informed (patience our moodlemoot start 6 of july ;-)
