### ISSUE TITLE
Links to Courses Not Available On User Profile Page 

### ISSUE THREAD

**Issue by DownesAyr** [willianmano/moodle-theme_moove#376]
Hello again, I'm afraid I've noticed a difference in 4.0 for a user's profile page where instead of clicking on one of their courses listed there it just takes you to the user view within that course and no way to then navigate to the course itself nor is the navigation bar at the top the one you usually get in the course context but only the top site wide header.
![image](https://user-images.githubusercontent.com/22812156/178004623-6d397d2c-1652-4f51-bb1c-85f4b2957f7b.png)

Hope this makes sense.

The other slight issue I noticed was difficulty navigating from a course in the breadcrumbs directly back to its category. You can only navigate back to its categories' parent category. This is unless you are on a part of the course e.g. the Grader page which then magically includes the link to the course's category within the breadcrumb.
![image](https://user-images.githubusercontent.com/22812156/178005362-9fa682ea-933d-4643-8b61-30654ed2a14f.png)

![image](https://user-images.githubusercontent.com/22812156/178005503-5f41d3fa-aad9-4b92-a53b-98870715fd3e.png)

Hope you can shed some light on these.

Joe

**Comment by willianmano** [comment]
@DownesAyr thank you for reporting this. The theme doesn't remove any link. This is Moodle's default behavior. I advise you to open an issue on Moodle Tracker Site. I can't do anything to solve that. Sorry.
