### ISSUE TITLE
User tours do not work

### ISSUE THREAD

**Issue by jdlcruz** [willianmano/moodle-theme_moove#38]
Hi @willianmano.

I am trying to execute the visits for the user, but they do not work.
I do not know exactly if the subject would have anything to do with that.

Thank you very much.

**Comment by benutzer-prog** [comment]
Hey everybody,

I found a solution. Change to the scss directory and look for the file "_responsive.scss". In the file you have to change the value ".modal-dialog" from "max-width: 50%;" to "width:100%;". Purge the caches and you are done.

Best regards,

Ben
