### ISSUE TITLE
Improve category section in the front page with block , description and image

### ISSUE THREAD

**Issue by JoyMajumdar2001** [willianmano/moodle-theme_moove#387]
In moove theme the category section looks like this given below
![moov](https://user-images.githubusercontent.com/63878173/187143177-317fe00f-33a8-468f-b509-66efb6dbb824.png)
But customise it as like this given below
![Untitled](https://user-images.githubusercontent.com/63878173/187143356-e413c144-7cf8-4799-973e-3133e9246d53.png)

**Comment by willianmano** [comment]
@JoyMajumdar2001 This is a really awesome feature, but unfortunately Moodle categories don't have images. =/
