### ISSUE TITLE
Actions menu not available to Teacher inside activities

### ISSUE THREAD

**Issue by cborn** [willianmano/moodle-theme_moove#388]
We are experiencing an issue where the editing teacher cannot view the Actions menu inside any activities or resources on their course.  The site admin can view this menu, but the editing teacher cannot.  This is only happening when the teacher chooses the Moove theme on their course.
<img width="1085" alt="Screen Shot 2022-08-31 at 8 34 41 PM" src="https://user-images.githubusercontent.com/1149264/187813614-fc5d3e10-8973-41e4-9d5e-375dd41f4160.png">

I have been able to replicate this issue on a local MAMP install of Moodle 3.11.8 and 3.11.9.  With absolutely no other customization other than changing the course theme to Moove, Teachers cannot see the Actions menu and in some plugins this means they cannot access settings or pages they need.

**Comment by willianmano** [comment]
@cborn Thanks for reporting this, but I only support the most recent version of Moodle, in this case, we are on Moodle 4.0.

**Comment by cborn** [comment]
I can appreciate that you are only supporting the latest version.  I have been attempting to fix this on my own, but am not having and luck yet.  If you happen to have pointers, I would happily fix it and submit a pull request.  It's not simply a CSS error, the div for the Actions menu is simply not generated.

**Comment by davidherney** [comment]
Hi @cborn ...

It is solved unchecking the option "Show my course categories" in Site administration > Appearance > Navigation.

It's for a error in the theme_moove_delete_menuitems functions.

Saludos
