### ISSUE TITLE
Progress bar on sections

### ISSUE THREAD

**Issue by adri1177** [willianmano/moodle-theme_moove#389]
In the last version, progress bar on section has been removed, are you planning to add it again? 
Having something like what we had in previous versions would be great.
See here an old picture of the theme with the progress bar for the sections.

[Old version picture](https://user-images.githubusercontent.com/22454226/50542662-8cf78400-0b88-11e9-972e-67e56652f0a3.jpg)

**Comment by willianmano** [comment]
@adri1177 unfortunately it is not possible to have it back. This new Moodle 4.0 doesn't allow themes to change this content area. =/
