### ISSUE TITLE
Navigation is not responsive 

### ISSUE THREAD

**Issue by haihoang202** [willianmano/moodle-theme_moove#39]
Hello:
Thank for creating such an awesome theme. 
However, when I use mobile device, the theme is not responsive: the navigation bar overlapped the main content. 
Would you be able to have a look ?

**Comment by b-visible** [comment]
I've had the same issue and the following SCSS should help. 

/* Nav Bar Fix icons */

header.navbar .usermenu {
    height: 70px;
}

header.navbar div.menubar {
    display: list-item;
}

header.navbar ul.navbar-nav .popover-region .popover-region-toggle,
header.navbar ul.navbar-nav .popover-region i.icon-envelope,
header.navbar ul.navbar-nav .popover-region .popover-region-toggle, 
header.navbar ul.navbar-nav .popover-region i.icon-bell {
    line-height: 70px;
}

.usermenu .login {
    display: block;
}

.usermenu .login {
    padding-top: 18px;
}

/* ###### --- For Mobile --- ###### */


/* hide the banner text on mobile devices */
@media (max-width: 925px) {
	#page-site-index.notloggedin #page-header #loginbox #intro, #page-site-index.notloggedin #page-header #loginbox #boxForm{
		display: none;
	}
	#page-site-index.notloggedin div#page-header {
    	min-height: 400px;
    }
}

@media (max-width: 850px) {

	.card-block, #page-enrol-users #filterform, .userprofile .profile_tree section, .yui-skin-sam .yui-layout.path-mod-chat-gui_ajax .yui-layout-unit-right, .yui-skin-sam .yui-layout.path-mod-chat-gui_ajax .yui-layout-unit-bottom, .yui-skin-sam .yui-layout.path-mod-chat-gui_ajax #chat-messages .chat-message.course-theme, .well {
    	padding: .25rem;
	}

	.course-content ul.section {
    	margin: 0;
	}
}


@media (max-width: 698px) {
	#page-site-index.notloggedin div#page-header {
    	min-height: 300px;
    }
}

@media (max-width: 544px) {
	#page-site-index.notloggedin div#page-header {
    	min-height: 280px;
    }
}

@media (max-width: 420px) {
	#page-site-index.notloggedin div#page-header {
    	min-height: 240px;
    }
}

/* ### Navigation ### */

@media (max-width: 991px) {
	
	.navbar-nav.hidden-md-down.navbar-custom-menu {
    	display: inline-block !important;
	}
	
	.nav-item.drawer-toggle a.hidden-sm-down {
    	display: inline-block !important;
	}

	.navbar-nav .nav-item {
		display: none;
	}

	.nav-item.drawer-toggle {
    	display: block;
	}

	body.drawer-open-left .navbar-nav .nav-item {
		display: inline-block;

	}

}

@media (max-width: 900px) {

	body.drawer-open-left #page {
    	margin-top: 140px;
	}
	
	body.drawer-open-left header.navbar {
   		min-height: 140px;
   	}
   	
   	body.drawer-open-left #page-wrapper #nav-drawer, body.drawer-open-left [data-region="drawer"] {
    	display: block;
    	position: fixed;
    	padding: 20px 20px;
    	width: 285px;
    	top: 140px;
    	height: calc(100% - 140px);
    }
	
	ul.navbar-nav.hidden-md-down.navbar-custom-menu {
    	margin-bottom: 0.2rem;
	}

	header.navbar ul.navbar-nav li, header.navbar ul.navbar-nav .nav-item {
		line-height: 35px;
    	max-height: 35px;
	}

	header.navbar ul.navbar-nav .popover-region .popover-region-toggle, header.navbar ul.navbar-nav .popover-region .lang-menu {
    	line-height: 35px;
    	max-height: 35px;
	}
}

@media (max-width: 767px) {

	#page-wrapper #nav-drawer{
		display: none;	
	}
}

**Comment by leandrojcaetano** [comment]
It works. Thanks,

**Comment by soodkritika** [comment]
I have added the above css in styles.scss file but it does not work for me. My navigation drawer is still overlapping the main content.
