### ISSUE TITLE
Filters for frontpage items

### ISSUE THREAD

**Issue by stefan-weber-think-modular** [willianmano/moodle-theme_moove#390]
Filters like multilang are not working for frontpage items (marketingboxes, FAQ)

**Reproduce**
In Moove settings for Frontpage, enter a marketingcontent with multilang text filters, eg
{mlang en}Englisch text{mlang}{mlang fr}French text{mlang}{mlang other}Other text{mlang}

**Expected behavior**
Filters should be applied and only the selected language should be displayed.

**Your environment (please complete the following information):**
 - Moodle version: Moodle 4.0.3 (Build: 20220822)
 - Moove version 4.0.5 (2022062005)

**Possible solution**
Change the output in /classes/util/settings.php, eg from

`$templatecontext['marketingcontent'] = $this->marketingcontent;`

to

`$templatecontext['marketingcontent'] = format_text($this->marketingcontent);`

This needs to be done for all text output settings.

**Comment by willianmano** [comment]
@stefan-weber-think-modular  This is already implemented. Thanks for reply

**Comment by stefan-weber-think-modular** [comment]
@willianmano please also fix it for FAQ - /classes/util/settings.php starting at line 221, change from

```
$templatecontext['faq'][] = [
                    'id' => $i,
                    'question' => $this->$faqquestion,
                    'answer' => $this->$faqanswer
                ];
```

to 

```
$templatecontext['faq'][] = [
                    'id' => $i,
                    'question' => format_text($this->$faqquestion),
                    'answer' => format_text($this->$faqanswer)
                ];
```

**Comment by willianmano** [comment]
@stefan-weber-think-modular Thanks for reporting. I fixed it.
