### ISSUE TITLE
Insertion of copyright

### ISSUE THREAD

**Issue by leandrosor** [willianmano/moodle-theme_moove#396]
Hello,

Help us poor mortals who don't know how to put copyrights in the footer.
A field with the option to choose the color of the footer, the text and the logo.

[Image](https://ibb.co/w4b5KVg)

Thanks.

**Comment by willianmano** [comment]
@leandrosor you need to change the source code. The premium version has an option to hide this orange copyright footer.

**Comment by leandrosor** [comment]
I already have the premium theme. I understand your point of not providing a feature to change the copyrights in the footer.

With much suffering I found the image of your logo (svg). The next step will be to find the string and code to change the orange color. I'll get there lol...

Congratulations on the success of your project!
