### ISSUE TITLE
Navbar color setting is gone.

### ISSUE THREAD

**Issue by Izguy** [willianmano/moodle-theme_moove#397]
**Describe the bug**
Hi i Updated the Plugin an the setting "navbar color" is gone. Now it stays plain white.
Is there a way to fix this?

Moodleverstion 4.05
Moove version 4.0.7 (2022062007)

greetings and keep up the good work

**Comment by willianmano** [comment]
You can change the secondary menu navbar, the main navbar is white and there is no setting to change it.

**Comment by Izguy** [comment]
there was an option in the previous version called "navbarheadercolor" is there a way to replicate it in the new version?
