### ISSUE TITLE
Identificación basada en Email

### ISSUE THREAD

**Issue by sebastianxcf** [willianmano/moodle-theme_moove#4]
HI,
Whe try to crate a new user using  identification based in email, the password link that allows to enter the pass is not working. Does not allow to enter anything.

![selection_103](https://cloud.githubusercontent.com/assets/23262528/26225363/1eea260c-3c27-11e7-9de7-b32a70973eee.jpg)

Using moodle 3.3

**Comment by willianmano** [comment]
Hey @sebastianxcf this is a boost and moodle 3.2+ feature. You need to click in the link to reveal the input text. If even clicking on the link the input still invisible, please, send me an output of your browser console.

**Comment by sebastianxcf** [comment]
I'm clicking on the link yes, and is not visible.  In the console I have nothing, any error.

**Comment by willianmano** [comment]
Hi @sebastianxcf , i've found the error and i'm already working on it.
