### ISSUE TITLE
Moove theme - Showing the course image at the top of the course page

### ISSUE THREAD

**Issue by acquaalta** [willianmano/moodle-theme_moove#402]
At least in Moove 2.8.8 (2018090200) there was an option to show the course image at the top of the course page, above the course topics and content. That could be achieved in that version by editing the course settings and adding an image to the "Course summary files" field.

Lately we installed version 4.1.1 (2022112801) of the theme on Moodle 4, and we noticed that the course image doesn't appear at the top, or anywhere else inside the course.  Adding an image to the "Course image" (The new name of "Course summary files") field in course settings only affects the appearance of the course in the courses list, outside of the course itself.

I'm actually not sure it's a bug, but maybe an intended change in how the theme looks. Even if that's the point, is this feature something you could consider to re-add to the theme, since some people like it very much? :-)
If this disappearance of the feature is something that is forced by Moodle core because of UX considerations, it would be nice to know.

Thanks a lot for this wonderful theme :-)

**Comment by willianmano** [comment]
This is not available anymore. Unfortunately, moodle only offers one image on the course page and this image is terrible when used as a course image and a top course image.

**Comment by acquaalta** [comment]
Thanks for the answer :-)
