### ISSUE TITLE
Informações de "outros campos" 

### ISSUE THREAD

**Issue by VipichConsultoria** [willianmano/moodle-theme_moove#403]
Informações de outros campos "campos adicionais do cadastro de usuario"
Não aparece no user/profile.php ao ser efetuada a consulta pelo administrador

![image](https://user-images.githubusercontent.com/121632020/209985965-14028554-a0fd-4e75-aefc-350fd4bebf21.png)

**Comment by willianmano** [comment]
@VipichConsultoria Obrigado por reportar.
