### ISSUE TITLE
user details not displayed on profile page also cannot add blocks to profile

### ISSUE THREAD

**Issue by fmido88** [willianmano/moodle-theme_moove#404]
after using moove theme, I realized that the full user information is not shown in the profile page, when I switch to boost (or any other theme), it appears normally
also, I cannot add or edit blocks on profile page, and the block drawer disappear on it

1. Go to 'any user profile page'
2. No details except for email, county & city
3. Click on 'edit mode on'
4. nothing happen

Expect to add blocks to profile page and be able to view user data without click edit each time
 

 - Moodle version: [e.g.Moodle 4.1+ ]
 - Moove version [e.g. Moove 4.1.1 (Build: 2022112801)]
 - Browser [any]

**Additional context**
I tried to configure it from /theme/moove/layout/mypuplic.php but I couldn't cause I'm not that good at coding
thanks in advance

**Comment by willianmano** [comment]
@fmido88 Thank you for reporting this.
