### ISSUE TITLE
Secondary nav-menu links takes a second line at moblie browser

### ISSUE THREAD

**Issue by fmido88** [willianmano/moodle-theme_moove#408]
Secondary navigation menu takes a second line 
I tried to fix this using custom css but I couldn't

**To Reproduce**
Open some wide page (like users list) from mobile device
Secondary navigation menu misbehave 

**Screenshots**
![Screenshot_2023-01-31-02-21-30-582-edit_com android chrome](https://user-images.githubusercontent.com/122031508/215627138-1da900ca-6ab4-4212-92f1-56d19bfd1fee.jpg)
.

** environment**
 - Moodle version: [4.1+]
 - Moove version [e.g. Moove 4.1.1 (Build: 2022112801)]
 - Browser [chrome mobile]

**Comment by ConnorGiles1996** [comment]
Just to add to this, I experienced this just now too without seeing this bug.  @willianmano 

If you change your browser back to web sizes and then back to mobile it fixes the issue. I'd imagine this was an unforeseen bug as you say and there just needs to be a way that it ensures the correct styling is seen on first load.
