### ISSUE TITLE
aria-required-parent

### ISSUE THREAD

**Issue by 0kee** [willianmano/moodle-theme_moove#409]
Hoping to use the Moove theme but I'm concerned about the aria errors that came up on our test site. Is there a fix or workaround for this? Details below. 
Thanks

Title: WCAG 1.3.1: Ensures elements with an ARIA role that require parent roles are contained by them (div[data-course-id="53"])
Tags: Accessibility, WCAG 1.3.1, aria-required-parent

Issue: Ensures elements with an ARIA role that require parent roles are contained by them (aria-required-parent - https://accessibilityinsights.io/info-examples/web/aria-required-parent)

Target application: 

Element path: div[data-course-id="53"]

Snippet: <div class="card dashboard-card" role="listitem" data-region="course-content" data-course-id="53">

How to fix: 
Fix any of the following:
  Required ARIA parents role not present: list, group

Environment: Microsoft Edge version 109.0.1518.61

====

This accessibility issue was found using Accessibility Insights for Web 2.36.1 (axe-core 4.4.1), a tool that helps find and fix accessibility issues. Get more information & download this tool at http://aka.ms/AccessibilityInsights.

**Comment by willianmano** [comment]
@0kee Thanks for reporting this, but this is a Moodle issue, not a theme issue. You can run your test using Boost and will receive the same results.
