### ISSUE TITLE
Breadcrumbs position in Moodle 4.1 / Moove 4.1.1 is wrong on some pages

### ISSUE THREAD

**Issue by stemiwe** [willianmano/moodle-theme_moove#413]
**Describe the bug**
On some pages, the breadcrumb position has shifted. It used to work in Moodle 4.0 / Moove 4.0.7, but now it looks like this, for example on /theme/index.php:
![image](https://user-images.githubusercontent.com/13886080/221818339-4b51c6d8-f2e7-44f8-bb74-0653118b6879.png)

It seems that the navigation bar ends up in the wrong flexbox:
![image](https://user-images.githubusercontent.com/13886080/221819629-8841630b-0570-4392-b8f2-4d1fbadeab8b.png)

**To Reproduce**
Go to /theme/index.php and look at the breadcrumbs

**Expected behavior**
Breadcrumbs used to look correct in Moodle 4.0 / Moove 4.0.7:
![image](https://user-images.githubusercontent.com/13886080/221818725-88bcd3b3-34ec-49c6-9eb1-4cc88a96b7e3.png)

The navigation bar there is in the first flexbox of the header:
![image](https://user-images.githubusercontent.com/13886080/221819389-cee67efa-e75e-4c2a-9ef1-697b9bc94de0.png)

**Your environment (please complete the following information):**
 - Moodle version: Moodle 4.1.1+ (Build: 20230224)
 - Moove version 4.1.1 [Build: 2022112801]

**Comment by willianmano** [comment]
@stemiwe I only support the most recent moodle version
