### ISSUE TITLE
Navegation not working for questionaries

### ISSUE THREAD

**Issue by sebastianxrc** [willianmano/moodle-theme_moove#42]
Hi,
I updates the last theme for moodle 3.4 and the navegation is not showing up for questionaries.
It[s working great for other types of activities.
I tried in the boots theme and works ok for questionaries.

Thanks!

**Comment by sebastianxcf** [comment]
Any sugestion how to fix this  ? :) 
I can do it and do a pull request. 

Thanks!

**Comment by willianmano** [comment]
@sebastianxrc @sebastianxcf I made a test here and everything is ok.

But if you found something you can send a PR.

![captura de tela de 2018-03-23 08-19-06](https://user-images.githubusercontent.com/233643/37826655-12ec9c92-2e73-11e8-960b-4963b943575b.png)
