### ISSUE TITLE
Error reading from database for a specific user only

### ISSUE THREAD

**Issue by julioaze** [willianmano/moodle-theme_moove#420]
**Describe the bug**
Error reading from database for a specific user only

**To Reproduce**
1. Set  Moove theme
2. Log in with a specific user

**Expected behavior**
User log in and navigate on the site

**Screenshots**
![Screenshot from 2021-07-08 09-20-34](https://user-images.githubusercontent.com/5478007/233126847-1570ba60-9416-4b90-9376-32e2b945ae34.png)

**Your environment (please complete the following information):**
- Moodle 3.11.13+ (Build: 20230414)
- Moove Thme 3.11.05 - 2021052100

**Additional context**
We encountered a weird concern today, a user encounters the error "Error reading from [database](https://moodle.org/mod/glossary/showentry.php?eid=15&displayformat=dictionary)" everytime he logs in. As per the user ever since the other day this has been the case for him.

We just recently upgraded our Moodle to version 3.11, the other day.  From my end, I can access and log in to the site without any errors and there are no other reports from other users.
Using any other theme, like the classic one, the problem doesn't happen.
The Moove theme is our default, so we need to troubleshoot.
Greetings

**Comment by willianmano** [comment]
@julioaze i was not able to reproduce it
