### ISSUE TITLE
In Course Category view, course tiles/cards don't show any change in appearance when marked as hidden

### ISSUE THREAD

**Issue by bollycanuk** [willianmano/moodle-theme_moove#424]
**Describe the bug**
In the tile/card view of courses, courses that are marked as hidden have no distinguishing indicators (e.g. grayed background, icon, etc) 

**To Reproduce**
1. Go to a course category view
2. Click on any course, go into settings and hide it. Save and return to Course category view
3. Notice that the course card appearance has not changed in any way.
4. Viewing the course on the Manage Courses and Categories page in System Administration **does** show the course name with gray text and the "eye" icon has a line through it.

**Expected behavior**
In the standard Boost theme and many others, the course title or course card background is dimmed or has a gray background.

**Screenshots**

**Your environment (please complete the following information):**
 - Moodle version:  4.2+ (Build: 20230602)
 - Moove version: 4.2.1 2023051000
 - Browser: Chrome, Firefox, Safari, Brave, Edge

**Additional context**

**Comment by willianmano** [comment]
@bollycanuk thank you for report this bug.
