### ISSUE TITLE
Student viewing course page before they are enrolled - the course image shows top left corner of image, not center of image

### ISSUE THREAD

**Issue by davefoord** [willianmano/moodle-theme_moove#425]
**Describe the bug**
When a course has a course image attached, any item which shows the image will crop the image focussing on the center of the image. However, if a student follows a link to a course onto which they are not yet enrolled - this shows the course image, but it crops to the top left corner of the image, which looks really odd.

**To Reproduce**
1. Create a course with a large image attached as the course image. Do not enrol your test student onto the course
2. Log in as the test student
3. Visit the course page

**Expected behavior**
Course image should crop to the center of the image, as happens on things like the dashboard, my courses etc.

**Your environment (please complete the following information):**
 - Moodle version: Moodle 4.1.4+ (Build: 20230623)
 - Moove version: 4.1.1 (2022112801)
 - Browser: Firefox

**Comment by davefoord** [comment]
Has anyone looked at this issue yet? I am assuming that it will be a relatively easy fix - and would be very useful.

**Comment by willianmano** [comment]
@davefoord  I added your code. Thank you.
