### ISSUE TITLE
Wrong display of the course on Opera

### ISSUE THREAD

**Issue by jmd87fr** [willianmano/moodle-theme_moove#427]
Hello,
I had installed the Stripe payement enrollement (with paypal too)  
When I want to enroll me I have this display. 

![image](https://github.com/willianmano/moodle-theme_moove/assets/5038301/3d4d9b5a-9bdf-417e-863f-1fed66eeca93)

Try it ;-) (need account) https://fael.formations-digitales.fr/enrol/index.php?id=95

Moodle : 4.2 (Build: 20230424)
Moove : 4.2.1 2023051000

Thank you for your help :-)

**Comment by willianmano** [comment]
@jmd87fr it seams to be a problem with stripe
