### ISSUE TITLE
Drag-Drop resources impossible on FrontPage

### ISSUE THREAD

**Issue by PatLemaire** [willianmano/moodle-theme_moove#429]
**Description of the bug**
Impossible to drag-drop resources to move them on FrontPage.

**HowTo reproduce**
1. Go to the frontpage
2. Click on 'Edit mode' to allow changes
3. Grab the arrows-cross icon to move a resource by dragging it.
4. Mouse cursor changes to a strange sign and refuse to drop the target.

**Expected behavior**
In FrontPage, you should Drag'n Drop resources to reorder them. It works on any course but not in FrontPage.

**Screenshots**
More than screenshots, I post a video (GIF format). Hope this would help to understand.
![foGnuWGJaG](https://github.com/willianmano/moodle-theme_moove/assets/8931218/2e19912b-d47b-4eef-bf02-8cd4efa469f0)

**My environment :**
 - Moodle version: Moodle 4.1.4+ (Build: 20230728)
 - Moove version: 4.1.1 (2022112801)
 - Browser:  Firefox 108.0.1 ; Chrome 116.0.5845.96

**Additional context**
Old method for moving (one click on move icon, then click on target area) is still working.
No additional block on FrontPage.

**Comment by willianmano** [comment]
Check your environment, this is not a moove issue.
