### ISSUE TITLE
Timer and Navigation not working in Quiz

### ISSUE THREAD

**Issue by arulantran** [willianmano/moodle-theme_moove#43]
I have updated Moodle 3.4 with Moov theme.
But while attending quiz timer and navigation not displayed on the quiz page and auto submission after test duration also not working.
Kindly help me to solve it.

**Comment by willianmano** [comment]
I made a test here and everything is ok.
![captura de tela de 2018-03-23 08-19-06](https://user-images.githubusercontent.com/233643/37826625-ed888d76-2e72-11e8-9c69-efa5b417f5bc.png)

**Comment by gigadep** [comment]
I think it's the same problem than mine (see #128).

**Comment by zienil** [comment]
Same problem with me, im using Moodle 3.6.1 with moove theme.
The quiz is using option Browser security : Full screen pop-up with some JavaScript security.
I can't see the timer and quiz number on the right block of the page.

![2019-03-19_10-53-14](https://user-images.githubusercontent.com/7897466/54577174-ba402980-4a35-11e9-9e8b-18cf49232e4f.png)

**Comment by hmgp** [comment]
> @arulantran I made a test here and everything is ok.
> ![captura de tela de 2018-03-23 08-19-06](https://user-images.githubusercontent.com/233643/37826625-ed888d76-2e72-11e8-9c69-efa5b417f5bc.png)

If you enable "Browser security" you get the problem. Is there a solution to this?
