### ISSUE TITLE
Missing user profile fields

### ISSUE THREAD

**Issue by PugMlam** [willianmano/moodle-theme_moove#432]
**Describe the bug**
Missing user profile fields. After the last update (Moodle version 4.1.4+ (Build: 20230707)) the profile user page no longer show it all those fields.

**To Reproduce**
1. Go to /user/profile/index.php,  
2. Click on Create a new profile field, fill all the required info, save it. 
3. Now go and edit your profile info, save and update. 
4. See error / The data from the user profile fields is no visible. not even in the source code.

**Your environment (please complete the following information):**
 - Moodle version 4.1.4+ (Build: 20230707)
 - Moove | 4.1.1 2022112801
 
 - Browser [Brave, Edge, Chrome. ]

**Additional context**
All the info is visible in the previous version of this theme. (3.9, 3.10) this issue only happens in the new version. 
![Immagine 2023-09-07 103203](https://github.com/willianmano/moodle-theme_moove/assets/120378364/6ea5d9cd-1502-463e-8019-7f487e94373d)

**Comment by willianmano** [comment]
@PugMlam Update your theme. I only support the most recent version of Moodle, currently 4.2.
