### ISSUE TITLE
Moodle 4.3

### ISSUE THREAD

**Issue by jmd87fr** [willianmano/moodle-theme_moove#435]
Hi Wilian,
all are good for you?

I've updated Moodle to 4.3
I have a white screen
my host says: 
PHP Fatal error: Declaration of theme_moove\output\core_renderer::supportemail(array $customattribs = []): string must be compatible with core_renderer::supportemail(array $customattribs = [], bool $embed = false): string in /home/jmd87fr/public_html/fael/theme/moove/classes/output/core_renderer.php on line 225

I rename the moodle/theme/moove folder
I access my Moodle 
I can't update Moove: 
<- https://moodle.org/plugins/download.php/30143/theme_moove_moodle43_2023100900.zip
 ->  ... Erreur

I can't install Moove again: White page ... 

Do you have some idea ?

**Comment by willianmano** [comment]
Hi @jmd87fr I already fixed this, please update your theme. Thank you.

**Comment by jmd87fr** [comment]
that's my problem: I can't do it! :-(

**Comment by jmd87fr** [comment]
> Hi @jmd87fr I already fixed this, please update your theme. Thank you.

@willianmano  that's my problem: I can't do it! :-(

**Comment by jmd87fr** [comment]
@willianmano I re-install with the .zip  It's OK .... ouf
