### ISSUE TITLE
Email used in the support form called from the theme footer, is not the supportemail but the admin email

### ISSUE THREAD

**Issue by kordan** [willianmano/moodle-theme_moove#438]
**Describe the bug**
Using the button "Contact site support" from the footer of the theme (when enabled, of course) I arrive to a form where the used email is not the supportemail but admin email.

**To Reproduce**
1. Write a dummy email to $CFG->supportemail
2. Go to the footer of the theme page
3. Click on "Contact site support" button
4. Compare the email in the form with $CFG->supportemail.

**Expected behavior**
The expectation is to have $CFG->supportemail in the form and not the admin email.

**Your environment (please complete the following information):**
 - Moodle version: 4.1.6+ (Build: 20231020)
 - Moove version: 2022112801
 - Browser: mac firefox 118

**Comment by willianmano** [comment]
The email present on the form is the email of the user who is submitting it.
