### ISSUE TITLE
Activate Moove Premium

### ISSUE THREAD

**Issue by JeffFinistere** [willianmano/moodle-theme_moove#439]
Hello, We cannot activate the Moove Prenium theme despite purchasing a license key.
To activate, the Moove theme must point to a specific server.

Sincerely

**Comment by willianmano** [comment]
Hello @JeffFinistere 

First of all, thank you for your purchase.

Here are some requirements.
A. Your site needs to have external internet access. Moodle makes a request to PluginStore site to validate the license. If your site has any internet block, firewall block, or restrictions, it can block the activation process.
B. You need to choose the theme as default. You can do it on Site Administration > Appearance > Theme selector

If everything is okay, try to do the following steps:

1. Put any text in the license field
2. Click save
3. Put the right license key
4. Click save

PS: A license key is limited to one Moodle site. You can not use a license key on more than one site.

**Comment by JeffFinistere** [comment]
Thank you for this information, we will look into all of this.
