### ISSUE TITLE
Custom footer

### ISSUE THREAD

**Issue by Alanfermin** [willianmano/moodle-theme_moove#44]
I can't modify the footer. I was only able to delete the default text in the following way:

In the directory: public_html/**aulavirtual**/theme/moove/templates file footer.mustache

**Your virtual classroom name **

In file footer.mustache i deleted the line 27 "<h2>{{#str}}stayintouch, theme_moove{{/str}}</h2>"

And i deleted from line 98 to 105

 "<div class="madewithmoodle">
            <p>{{#str}}madewitmoodle, theme_moove{{/str}}</p>
            <a href="https://moodle.org"><img src="{{output.get_pix_image_url_base}}/moodle-logo-white.png" alt="Moodle logo"></a>
        </div>

        <div class="madeby">
            <p>{{#str}}madeby, theme_moove{{/str}} <a href="http://conecti.me">conecti.me</a></p>
        </div>"

Also the linea 111 "{{{ output.standard_footer_html }}"

But I couldn't find the file to modify the footer and not delete it. And I want to know how I can find it, so I can modify it instead of eliminating it

**Comment by Anapadro** [comment]
Hi,
Any advance about how to do it? I have the same problem...

**Comment by Frossard** [comment]
I have changed it too. The path is the same, `footer.mustache`, but i only commented the code and works. Here is my code:

```
<footer id="page-footer" class="p-y-1">
    <div class="container">
      <div class="row">
        <div class="col-md-6" style="color: #fff; float: left; font-size: 16px; padding: 24px 0;">Credibility, flexible schedules and convenience for you to study.</div>
        <div class="col-md-6 text-right"><img src="{{output.get_pix_image_url_base}}/logofooter.png" alt="Logo UVV"></div>
      </div>


        <!--div id="course-footer">{{{ output.course_footer }}}</div>

        {{# output.page_doc_link }}
            <p class="helplink">{{{ output.page_doc_link }}}</p>
        {{/ output.page_doc_link }}

        <div class="madewithmoodle">
            <p>{{#str}}madewitmoodle, theme_moove{{/str}}</p>
            <a href="https://moodle.org"><img src="{{output.get_pix_image_url_base}}/moodle-logo-white.png" alt="Moodle logo"></a>
        </div>

        <div class="madeby">
            <p>{{#str}}madeby, theme_moove{{/str}} <a href="http://conecti.me">conecti.me</a></p>
        </div>

        <nav class="nav navbar-nav hidden-lg-up">
            {{# output.custom_menu_flat }}
                <ul class="list-unstyled p-t-1">
                    {{> theme_moove/custom_menu_footer }}
                </ul>
            {{/ output.custom_menu_flat }}
        </nav>
        {{{ output.standard_footer_html }}} -->
        {{{ output.standard_end_of_body_html }}}
    </div>
</footer>
```

**Comment by willianmano** [comment]
@Alanfermin @Anapadro you have full control of your source code. You can edit the footer as you wish. Edit the file footer.mustache and be happy :)

What you really want to do?
