### ISSUE TITLE
Assistance needed in Navbar 

### ISSUE THREAD

**Issue by Shanmugavadivelu7** [willianmano/moodle-theme_moove#442]
Hi, I am currently using moove version 4.1. Here I would like to change the color of entire Navbar(primary) which is initailly white to a dark colour like violet. 
Can someone give me an idea on where to change my edit my css code.  where do I have to change in navbar.css or is there anyother files that obviously i am missing. 
Thanks :)

**Comment by johnt1838** [comment]
Hello there, you can customize the scss file of the navbar (theme>moove>_navbar.scss)
add something like this in 
`.navbar.fixed-top {
    background-color: #YOUR_COLOR!important;
`
