### ISSUE TITLE
Inconsistent Display of Coursecard

### ISSUE THREAD

**Issue by Silas-Frischknecht** [willianmano/moodle-theme_moove#443]
**Describe the bug**
The design of the coursecard is slightly different in the enrolmentview vs. the course index
Specifically (marked in Screenshots:
red: the selrenrolment icon moves and loses its background, making it sometimes hard to see
orange: the course image is scaled differently - although i only tried with the autmatically generated Images.
green: sizing and spacing of customfields changes

**To Reproduce**
1. Go to '/course/index.php'
2. Click on course with activated self enrolment, the user is not yet enrolled in

**Expected behavior**
I Expected the two tiles to look close to identical

**Screenshots**
![image](https://github.com/willianmano/moodle-theme_moove/assets/153749338/a9cb18f0-5c08-4216-9439-50db64b657bb)
![image](https://github.com/willianmano/moodle-theme_moove/assets/153749338/d056a823-e6da-403f-878a-dffce16a21a0)

**Your environment (please complete the following information):**
 - Moodle version: Moodle 4.2.2 (Build: 20230814)]
 - Moove version: Moove 4.2.1 (Build: 2023051000)
 - Browser: Chrome 120.0.6099.110; Edge 120.0.2210.7

**Comment by johnt1838** [comment]
Hello, can you provide more details about the issue
Which option should be kept ? The course/index.php one or the enrol/index.php... one ?

**Comment by Silas-Frischknecht** [comment]
Thanks for reaching out. i think the course/index.php one is a more readable design, i'd therefore prefer that.
