### ISSUE TITLE
Hidden items being counted towards course completion percentage

### ISSUE THREAD

**Issue by alexfoffano** [willianmano/moodle-theme_moove#449]
**Describe the bug**
Restricted and hidden items and activities are being counted towards course completion percentage. I just updated my Moodle from 3.11 to 4.1 and I've noticed this. I've been using the Moove theme for a long time and it used to disconsider these hidden activities.

**To Reproduce**
1. Create a new course
2. Create two activities
3. Mark one activity as done
4. Make the other as hidden
5. See the course completion percentage, it is 50%

**Expected behavior**
I believe the course completion percentage should count only the visible activities.

**Your environment (please complete the following information):**
 - Moodle version: 4.1.8+ (Build: 20240125)
 - Moove version: 4.1.1 2022112801
 - Browser: Chrome

**Comment by willianmano** [comment]
@alexfoffano Thanks for reply this, but this is a Moodle issue, as we use moodle core API to get the course progress.
