### ISSUE TITLE
How to edit login page and principal page.

### ISSUE THREAD

**Issue by rayltonsales** [willianmano/moodle-theme_moove#45]
Hi Willian, I installed your theme and it's very good, congrats!

I only have two questions:

How can I edit the login page and principal page? 
I tried to find something on the internet but, no success.

Regards.

**Comment by willianmano** [comment]
You can edit theses pages editing the pages below:

login page: [your_moodle_folder]/themes/moove/templates/core/login.mustache

principal page for guest users: [your_moodle_folder]/themes/moove/templates/frontpage_guest.mustache

principal page for loggeding users: [your_moodle_folder]/themes/moove/templates/frontpage.mustache
