### ISSUE TITLE
API documentation not showing when Moove is enabled

### ISSUE THREAD

**Issue by CarlosArceLopera** [willianmano/moodle-theme_moove#454]
**Describe the bug**
When using branch MOODLE_401_STABLE  and accessing admin/webservice/documentation.php in Chrome the site hangs and the page loading wheel spins endlessly. Eventually, Chrome prompts the user to wait or kill the tab. It is not a problem with any other theme (Boost).

**To Reproduce**
1. Go to 'admin/webservice/documentation.php' when moove is enabled and in branch 401
2. See error

**Expected behavior**
The issue is only for Chrome. Firefox works fine.

**Your environment (please complete the following information):**
 - Moodle version: 4.1.9+ (Build: 20240409)
 - Moove version: Moove 4.1.1 (Build: 2022112801)]
 - Browser [Chrome]

**Comment by willianmano** [comment]
@CarlosArceLopera this error does not exist in the most recent versions.
