### ISSUE TITLE
Troble with 4.4 

### ISSUE THREAD

**Issue by jmd87fr** [willianmano/moodle-theme_moove#457]
Hi @willianmano 
I just install on moodle 4.4 your new version : 4.4.0 (2024042200)  (Good job to give it one day after!)
**Describe the bug**
No acces to front page (connected)

![image](https://github.com/willianmano/moodle-theme_moove/assets/5038301/3572b22b-6875-40c7-aa77-16ef26f0861a)

I turn on boost :-( 

PS you can see:  I stop to change the footer ;-) 

Thanks

**Comment by willianmano** [comment]
@jmd87fr thank you for reply this.
