### ISSUE TITLE
error code

### ISSUE THREAD

**Issue by Paulogool** [willianmano/moodle-theme_moove#46]
Hi,
a small mistake in this line:

https://github.com/willianmano/moodle-theme_moove/blob/cfb3009db00afe81df3590738a812002fb99ca84/templates/flat_navigation.mustache#L75
Resolved by replacing "javascrpit" with "javascript":
` <a class="m-l-{{get_indent}}" href="javascript:void(0);"> `

**Comment by willianmano** [comment]
@Paulogool thank you.
