### ISSUE TITLE
Current Moove Premium version number?

### ISSUE THREAD

**Issue by UniWarwickGrahamWilmott** [willianmano/moodle-theme_moove#460]
**Describe the bug**
https://pluginstore.conecti.me/plugins/theme_moove lists the latest version of premium as "Version 4.4.21", yet when downloaded the version is "4.3.25" (2023101025).

Can you please confirm if this is the current/latest version (for Moodle 4.4)?

**To Reproduce**
1. Go to https://pluginstore.conecti.me/plugins/theme_moove
2. Download latest version

**Expected behavior**
I'm not 100% sure how your version numbers work, but I was expecting 4.4.x as the latest version.

**Screenshots**
N/A

**Your environment (please complete the following information):**
 - Moodle version: Version 4.4 (Build: 20240422)
 - Moove version: 4.3.25 2023101025
 - Browser: Chrome

**Additional context**
Not sure if this is the best way to contact you - sorry.

**Comment by willianmano** [comment]
@UniWarwickGrahamWilmott sorry, I made a mistake in premium but it was solved.
