### ISSUE TITLE
No button to send mail with the local_mail extension in the student's profile

### ISSUE THREAD

**Issue by rmartinezgc** [willianmano/moodle-theme_moove#463]
Good morning.

**Describe the bug**
After upgrading Moodle to version 4.3.3+ (Build: 20240409), the local_mail extension to version 2.9 (2024031800) and the theme moove to version 4.3.3 (2023100903), the send email button of the local_mail extension is no longer displayed in the participant's profile. In other themes such as Trema 4.4.0.0 (2024042200), it still looks correct.

Moodle is running on an nginx server with php 8.1
Why does this happen?
Thank you.
Regards.

**To Reproduce**
1. Log in as administrator or manager
2. Access a student's profile
3. The local_mail extension button to send an email is not displayed. Depending on the version, this button is displayed next to the Send Message and Add Contact buttons or below all student information. For example, with the Trema theme, you see next to the buttons I have just discussed

**Expected behavior**
Display the button to send mails with the local_mail extension.

**Screenshots**
1. Button with Trema.png
![Button with Trema](https://github.com/willianmano/moodle-theme_moove/assets/3283956/7ae3a074-ec4c-4605-982d-c0794672fe4e)
2. No button with Moove.png: Mail send button should be displayed somewhere
![No button with Moove](https://github.com/willianmano/moodle-theme_moove/assets/3283956/80a0eb32-3c12-4e82-90e3-5be9c8a09714)

**Your environment (please complete the following information):**
 - Moodle version: 4.3.3+ (Build: 20240409)
 - Moove version: 4.3.3 (2023100903)
 - Local mail version: 2.9 (2024031800)
 - Browser: Any, not relevant

**Comment by rmartinezgc** [comment]
Have you guys been able to check something?

**Comment by willianmano** [comment]
@rmartinezgc fixed! Thanks for reporting this.
