### ISSUE TITLE
Course cards content not dimmed issue in .../course/index.php

### ISSUE THREAD

**Issue by GoranFuru** [willianmano/moodle-theme_moove#466]
**Describe the bug**
When browsing categories an courses in .../course/index.php the course card content is "dimmed" as expected when expanding a catecory by clicking the "arrow" to the left of the category title. (The category & courses in that category are set as hiddan).

BUT when clicking the category title you land on pages .../course/index.php?categoryid=No. In all the "category pages" the course card content is not "dimmed". The links to the course pages in the course cards are shown in "Brand color" and as dimmed.

The expexted behaviour is that all hidden categories an courses should be dimmed regardless if you expand a category with the arrow or if you click on the category link. This is the behaviour in other themes and also in Boost in Moodle core.

Please fix this. 
![Dimmed courses 1](https://github.com/willianmano/moodle-theme_moove/assets/29913663/45b59d17-c1a5-4e13-bdca-36bca93f6df5)
![Not dimmed courses 1](https://github.com/willianmano/moodle-theme_moove/assets/29913663/5fcd7564-f6d5-4957-ac76-f3806b57bfd5)

**Comment by christopherm00** [comment]
This is causing issues for us as well - can confirm this is effecting the latest version as of 08/20/2024
Thank you

**Comment by GoranFuru** [comment]
Hi.
In Moodle 4.1.1+ we have the latest theme installed (Official version 2022112801 from Moodle plugins) and the issue is still there.
In Moodle 4.4+ it seems to work as expected. Theme version installed: 2024042300.

**Comment by willianmano** [comment]
@GoranFuru @christopherm00 Fixed. Thanks for reporting this.

**Comment by GoranFuru** [comment]
Hi.
Thanks for the fix. Will you post a new official version in Moodle plugins for this fix. I think that would be god thing todo because a lot of hosting providers jumps between LTS-versions so they/we need continuous updates in Moodle plugins for LTS versions e.g. 4.1+ until Moodle 4.5 LTS is released.

Current version in Moodle plugins is:
4.1.1 (2022112801)
Moodle 4.1
Released: onsdag, 30 november 2022, 10:09
***@***.***

Kind regards,
Göran
_______________________________________________

***@***.***
Göran Furu
Learning and Performance Consultant
***@***.******@***.***>
Mobile +46 70 686 95 64
www.maincon.se<http://www.maincon.se>


Från: Willian Mano ***@***.***>
Skickat: den 11 september 2024 03:23
Till: willianmano/moodle-theme_moove ***@***.***>
Kopia: Göran Furu ***@***.***>; Mention ***@***.***>
Ämne: Re: [willianmano/moodle-theme_moove] Course cards content not dimmed issue in .../course/index.php (Issue #466)

Du får inte e-post ofta från ***@***.******@***.***>. Se varför det här är viktigt.<https://aka.ms/LearnAboutSenderIdentification>

Closed #466<https://github.com/willianmano/moodle-theme_moove/issues/466> as completed via 17dc475<https://github.com/willianmano/moodle-theme_moove/commit/17dc475ace991e924aed5e57667396418c6ac258>.

**Comment by willianmano** [comment]
Hi, @GoranFuru I only support the most recent Moodle version, currently 4.4. This fix was applied for this version and it is available on moodle.org site.

Once the fix is on moodle 4.4, it will be on 4.5 too.
