### ISSUE TITLE
Not interpretable address

### ISSUE THREAD

**Issue by robbl71** [willianmano/moodle-theme_moove#47]
Hello, I have just created 2 courses as "editing teacher", as can be seen in the following snapshot
![immagine](https://user-images.githubusercontent.com/35632130/35184981-e888451a-fdfc-11e7-9e70-b1c337cdac5a.png).
If I click on My courses a blank page appears with the text: 
Not interpretable address. This is one of the protocols (javascrpit) is not associated with any program or is not accepted in this context.
Additional software must be installed to open this address.
I tried using mozilla firefox quantum and with microsoft edge with the same result.

**Comment by Frossard** [comment]
In my instance this button "My courses" is not clickable. Is just a level item for the courses enrolleds of the user.

**Comment by willianmano** [comment]
@Frossard you are right, the item my courses is not clickable. This link comes from Moodle itself and it's not changed in the theme.
