### ISSUE TITLE
Missing communication icon for courses

### ISSUE THREAD

**Issue by mona-shakiba** [willianmano/moodle-theme_moove#470]
**Describe the bug**

**To Reproduce**
1. Enable communication providers from Administration->Development->Experimental->Experimental settings
2. Configure Matrix from Administration->Plugins->Communication->Martix
3. Enable coummunication with Matrix for as specific course from course->More->Communication->set Matrix
4. After the room is created, I cannot see the communication icon which should be above  the question icon.

here is the css:
```
            <div data-region="footer-container-popover">
                <button class="btn btn-icon bg-secondary icon-no-margin btn-footer-popover" data-action="footer-popover" aria-label="Show footer" data-original-title="" title="">
                    <i class="icon fa fa-question fa-fw " aria-hidden="true"></i>
                </button>
            </div>
```
            
In boost theme, the icon is shown and the css looks like this:
```
            <div data-region="footer-container-popover">
                    <button onclick="window.open('https://app.element.io/#/room/!qYtCxoiGbOZokwqtIp:matrix.example.com', '_blank', 'noreferrer')" class="btn btn-icon bg-primary text-white icon-no-margin btn-footer-communication" aria-label="Chat to course participants">
                        <i class="icon fa fa-comments-o fa-fw " aria-hidden="true"></i>
                    </button>
                <button class="btn btn-icon bg-secondary icon-no-margin btn-footer-popover" data-action="footer-popover" aria-label="Show footer" data-original-title="" title="">
                    <i class="icon fa fa-question fa-fw " aria-hidden="true"></i>
                </button>
            </div>   
```         

**Expected behavior**
I expect to see the communication icon.

**Screenshots**
![image](https://github.com/user-attachments/assets/2b6ad024-8fbc-4d25-a2a0-eccc43493e53)

**Your environment (please complete the following information):**
 - Moodle version: [e.g.Moodle 4.4.1+ (Build: 20240719)]
 - Moove version [e.g. Moove 4.4.1 (Build: 2024042300)]
 - Browser [chrome]

**Additional context**
I tested on moodle  4.3.3+ (Build: 20240409) and moove 4.3.3+ (Build:2023100903)

**Comment by willianmano** [comment]
@mona-shakiba Fixed! Thanks for reporting this.
