### ISSUE TITLE
loginpasswordtoggle not supported

### ISSUE THREAD

**Issue by leonstr** [willianmano/moodle-theme_moove#474]
**Describe the bug**
Moodle 4.4 added the ability to show the password in plain text on the login form ([MDL-79769](https://tracker.moodle.org/browse/MDL-79769)). With Moove this feature does not work.

**To Reproduce**

1. Install Moove.
2. Change _Password visibility toggle_ to "Enabled" (under _Site administration_ > _Plugins_ > _Authentication_ > _Manage authentication_.
3. Log out of Moodle.
4. Click _Log in_.

**Expected behavior**
A button appears in the password field with an eye icon. Clicking this shows the password text.

**Screenshots**

Screenshot showing the expected button (from theme_boost):
![loginpasswordtoggle](https://github.com/user-attachments/assets/3ecb338e-98f3-45c1-b999-e22edd941d70)

**Your environment (please complete the following information):**
 - Moodle 4.4.3+ (Build: 20240907).
 - Moove 2024042300.
 - Firefox 129.0.

**Comment by willianmano** [comment]
@leonstr Fixed! Thanks for reporting this.
