### ISSUE TITLE
Missing features from Moodle 4.4

### ISSUE THREAD

**Issue by VerNovo** [willianmano/moodle-theme_moove#476]
# I found 2 missing features added in Moodle 4.4.
1. Missing colapse all button at the top of left navbar
2. Missing returning feature of indentation. Activity can be moved slightly to right/left "under" another activity, that should also be projected to left navbar.

**Comment by willianmano** [comment]
@VerNovo Fixed! Thanks for reporting this.

**Comment by VerNovo** [comment]
Hi, first point is fixed thank you very much, but there is also the second one. I'm gonna provide picture from sandbox to explain better. 
![m404-feature-2](https://github.com/user-attachments/assets/d69e33c7-de4d-4b3a-9583-95a3c11f0aeb)
