### ISSUE TITLE
Categories on mobile 

### ISSUE THREAD

**Issue by jmd87fr** [willianmano/moodle-theme_moove#478]
**Describe the bug**
The textes are in bad display

**To Reproduce**
1. Take your mobile phone
2. Go to fael.formations-digitales.fr 
3. Scrolling donc
4. Clik on Inteligence artificielle 
5. See error 😉

**Expected behavior**

**Screenshots**

**Your environment (please complete the following information):**
 - Moodle version: 4.3
 - Moove version update
 - Browser mobile firefox
![Screenshot_20240914-093043_DuckDuckGo](https://github.com/user-attachments/assets/0e80aacc-8269-40ff-bb34-d53d4a52416f)

**Additional context**

**Comment by willianmano** [comment]
@jmd87fr This issue was solved on Moove for Moodle 4.4

**Comment by jmd87fr** [comment]
Hi @willianmano 
My moodle : 4.4.1+ (Build: 20240614)
I'll up to Moodle 4.4.3+ (Build: 20240910) | Version 2024042203.03 and I'll come back ;-) 
Thank you
