### ISSUE TITLE
Add "Course" link to navigation bar while inside activities. 

### ISSUE THREAD

**Issue by lindnaug** [willianmano/moodle-theme_moove#482]
Teachers and students LOVE the "Course" link in the floating navigation bar in Moove. They use it when then want to return from somewhere else to the course home page. However, when teachers and students open an activity or a resource (syllabus, forum, etc), the "Course" link disappears. So the teacher and students have to be trained to look elsewhere (breadcrumbs) to find the name of the course. 

**Describe the solution you'd like**
We would LOVE to have "Course" stay on the floating navigation bar, all the time. This would maintain consistency and save time and reduce frustration. 

**Describe alternatives you've considered**
We try to educate people but they are still confused and frustrated. 

Thank you Willian!

![Screenshot 2024-12-18 at 12 41 59 PM](https://github.com/user-attachments/assets/9e5b972f-f536-42cd-96d8-0318df6f8124)

**Comment by willianmano** [comment]
@lindnaug Thank you, this is definitely a good feature!

**Comment by lindnaug** [comment]
Hi Willian!
Is this fix only applied to the Moodle 4.5 Moove release or can we get it
for our Moodle 4.4 instance?
Very grateful! And nice work!
Nathan


If you would like to meet with me, you may schedule a remote 30-min session
here:

   - Request a 30 minute remote screensharing meeting
   <https://calendly.com/lindn/30minremote> (I'll call you and email a
   screenshare link at the start of the meeting)


++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

*Dig into Zoom with our new Zoom Resources Guide!
<http://go.augsburg.edu/zresources>*

Augsburg Information Technology staff will never ask you for your Augnet
password.


Nathan Lind, he/him/his
Academic Liaison For Computing (LFC) for Faculty and Staff in Social Work,
Education, Nursing, Health-Physical Education, Religion, Youth Studies,
Philosophy
Augsburg University
612-330-1469
http://inside.augsburg.edu/it/

WE ARE CALLED | AUGGIES

**Comment by willianmano** [comment]
@lindnaug done.

**Comment by lindnaug** [comment]
Wonderful! Although when I download the Moove for Moodle 4.4 just now, the
Version.php file shows the same version as from months ago:
// This is the named version.
$plugin->release = '4.4.24';

If you would like to meet with me, you may schedule a remote 30-min session
here:

   - Request a 30 minute remote screensharing meeting
   <https://calendly.com/lindn/30minremote> (I'll call you and email a
   screenshare link at the start of the meeting)


++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

*Dig into Zoom with our new Zoom Resources Guide!
<http://go.augsburg.edu/zresources>*

Augsburg Information Technology staff will never ask you for your Augnet
password.


Nathan Lind, he/him/his
Academic Liaison For Computing (LFC) for Faculty and Staff in Social Work,
Education, Nursing, Health-Physical Education, Religion, Youth Studies,
Philosophy
Augsburg University
612-330-1469
http://inside.augsburg.edu/it/

WE ARE CALLED | AUGGIES

**Comment by lindnaug** [comment]
Also, the upgrade.txt says "* Release for Moodle 4.1"

If you would like to meet with me, you may schedule a remote 30-min session
here:

   - Request a 30 minute remote screensharing meeting
   <https://calendly.com/lindn/30minremote> (I'll call you and email a
   screenshare link at the start of the meeting)


++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

*Dig into Zoom with our new Zoom Resources Guide!
<http://go.augsburg.edu/zresources>*

Augsburg Information Technology staff will never ask you for your Augnet
password.


Nathan Lind, he/him/his
Academic Liaison For Computing (LFC) for Faculty and Staff in Social Work,
Education, Nursing, Health-Physical Education, Religion, Youth Studies,
Philosophy
Augsburg University
612-330-1469
http://inside.augsburg.edu/it/

WE ARE CALLED | AUGGIES

**Comment by willianmano** [comment]
@lindnaug, I only support the version that is compatible with Moodle's most recent version. Download the code from github and it will work for your moodle 4.4

**Comment by lindnaug** [comment]
Thank you, I will do that.

If you would like to meet with me, you may schedule a remote 30-min session
here:

   - Request a 30 minute remote screensharing meeting
   <https://calendly.com/lindn/30minremote> (I'll call you and email a
   screenshare link at the start of the meeting)


++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

*Dig into Zoom with our new Zoom Resources Guide!
<http://go.augsburg.edu/zresources>*

Augsburg Information Technology staff will never ask you for your Augnet
password.


Nathan Lind, he/him/his
Academic Liaison For Computing (LFC) for Faculty and Staff in Social Work,
Education, Nursing, Health-Physical Education, Religion, Youth Studies,
Philosophy
Augsburg University
612-330-1469
http://inside.augsburg.edu/it/

WE ARE CALLED | AUGGIES
