### ISSUE TITLE
Activity names cut off in Grader Report

### ISSUE THREAD

**Issue by lindnaug** [willianmano/moodle-theme_moove#483]
**Describe the bug**
When scrolling down in a course's Grader Report, the row of activity names and category names is half cut-off at the top. 

**To Reproduce**
Video of the issue: https://www.loom.com/share/fa25ab61f36740df95cd6810e4845275
Video showing the issue does not happen in Boost: https://www.loom.com/share/66fd9f54b0fd48dd927b7537f8c1f13f

**Expected behavior**
As in Boost, activity names should be visible when scrolling down. 

**Screenshots**

**Your environment (please complete the following information):**
 - Moodle version: Moodle 4.4
 - Moove version 
 - 
Moove Premiumtheme_moove | 4.4.242024082420

 - Browser - Brave [Version 1.73.101 Chromium: 131.0.6778.139 (Official Build) (arm64)](https://brave.com/latest/) on MacOS

**Additional context**
Let us know if this happens in your instance of Moove too? Thank you!!!!

**Comment by willianmano** [comment]
@lindnaug thank you for reporting this.
