### ISSUE TITLE
Help tooltip outside screen display

### ISSUE THREAD

**Issue by jrm-unamur** [willianmano/moodle-theme_moove#5]
Hi there,

"Your progress" help tooltip in course home page displays to the right of "?" icon and thus outside the screen display.

Regards

**Comment by willianmano** [comment]
@jrm-unamur Can you attach an image of this?

**Comment by jrm-unamur** [comment]
Hey,
After some digging, the problem comes from boost theme where every "help-icon" tooltip has a data-placement="right" (for ltr languages) --> see help_icon.mustache in boost templates folder
![capture d ecran 2017-06-13 a 08 13 32](https://user-images.githubusercontent.com/4832513/27068498-b2a1ad46-5010-11e7-9894-56e6a23838ab.png)

**Comment by willianmano** [comment]
@jrm-unamur the issues was solved by @leofreitas . Thanks guys.
