### ISSUE TITLE
Progress bar ignores Label Modules

### ISSUE THREAD

**Issue by alexfoffano** [willianmano/moodle-theme_moove#51]
When you mark a Label Module as complete, it changes the Course Progress, but it doesn't change the Discipline Progress.

![progress bar moove](https://user-images.githubusercontent.com/36538142/36309647-a7db260c-130c-11e8-8be0-e4c29c4c0146.png)

**Comment by willianmano** [comment]
Oi @alexfoffano , eu já havi percebido isso mas não tinha entrado como prioridade. Vou adicionar na lista para fazer. Obrigado por reportar.

**Comment by willianmano** [comment]
@alexfoffano solved.
