### ISSUE TITLE
Orange footer displays when disabled

### ISSUE THREAD

**Issue by sean1746** [willianmano/moodle-theme_moove#56]
The orange footer displays on the 'forgot password' page at /login/forgot_password.php even when it has been disabled in the theme settings. The normal footer does not display correctly on this page either – it displays the footer heading, but not the contact links.

![screen shot 2018-03-23 at 16 20 14](https://user-images.githubusercontent.com/37707292/37841020-84aa1538-2eb6-11e8-9d37-a5115e9e57ad.png)

**Comment by willianmano** [comment]
@sean1746 thank you for report.
