### ISSUE TITLE
ul class="teachers"

### ISSUE THREAD

**Issue by winnidat** [willianmano/moodle-theme_moove#58]
Hello Willian,
can you please change padding-left to 2 rem instead of 1 because the bullet-points in the course cards now appear outside of the card.
Kindest regards,
Thomas

**Comment by willianmano** [comment]
@winnidat thank you.

**Comment by Razzo1987** [comment]
Hi,
sorry for reopen.
instead of change padding I suggest to change the div class:
```
<div class="card-block">...</div>
<div class="teachers card-footer" id="###"><span>Teacher: <a href="...">Teacher Name</a></span></div>
```

![course](https://user-images.githubusercontent.com/906604/38092603-05bed5e4-3369-11e8-97f4-cb742d42c0f4.PNG)

I post the source code tomorrow when I can connect with FTP
