### ISSUE TITLE
Nav bar (barra de Menu) no carga los iconos

### ISSUE THREAD

**Issue by AqibMuhammad** [willianmano/moodle-theme_moove#6]
Hola,
He instalado esta plantilla en mi Moodle, pero el problema que tengo es que no carga los iconos de menu.

Imagen : https://ibb.co/kk2sk5

Version de Moodle : 3.2

Gracias

**Comment by willianmano** [comment]
@AqibMuhammad This is a problem with your environment. I other case i recomend to use always the most recent plugin verion. Thank you for use the theme. Regards.
