### ISSUE TITLE
Footer troubles

### ISSUE THREAD

**Issue by jmd87fr** [willianmano/moodle-theme_moove#71]
Hi Willian,
very nice theme !! I love it :-) 

In the mysite.com/user/policy.php the footer stay with the orange layout (I did turn off in admin setting) 
Could you help me ?

**Comment by willianmano** [comment]
Duplicated of issue #56 . I already solved that in the commit https://github.com/willianmano/moodle-theme_moove/commit/0372104fdc8d96cf64af02b26ea1617ddf3d866b
