### ISSUE TITLE
Login page

### ISSUE THREAD

**Issue by jmd87fr** [willianmano/moodle-theme_moove#72]
Hi Willian
1) How can I change the picture bacground in the /login/index.php ? 
2) It seems to me in 
`administration>Plugins>Authentication>Manage>authentication>auth_instructions ` 
the changes (new text) dont work (?)

Some help?
Hope to read you

**Comment by willianmano** [comment]
Duplicated issue of #65. I already solved that in the commit 23f3282

It will be delivered in the next theme's version. You can also download the code from here(github) and update your theme.
