### ISSUE TITLE
setting "Default home page for users" to "site" -> wrong icon

### ISSUE THREAD

**Issue by winnidat** [willianmano/moodle-theme_moove#74]
Hallo,
if you set the defaulthomepage to site, the navigation bar icons for both dashboard and homepage have the same ("home") icon.
Both have data-key attribute set to "home".
Best regards,
Thomas

**Comment by willianmano** [comment]
Hi @winnidat this is a Moodle bug, I am tryed to fix that in theme without success.

**Comment by winnidat** [comment]
ah ok thank you.
#nav-drawer .list-group .list-group-item[data-key="home"]:nth-child(2) a:before {
    content: "\e007";
}
i use this as a workaround
