### ISSUE TITLE
Need to move login instructions

### ISSUE THREAD

**Issue by Gorillab1scuit** [willianmano/moodle-theme_moove#75]
I have required login, so users will hit the auth page.  On the auth page, I have an instruction box that is now below the login box and a nice themed color box to the left of the login prompt.

Is there a way to get the instructions inside the orange?
<img width="778" alt="screenshot_1" src="https://user-images.githubusercontent.com/36890827/38266022-93a19556-3745-11e8-870b-68eb1f23393b.png">

Thanks in advance...

**Comment by willianmano** [comment]
@Gorillab1scuit I made some changes, look. When we have a oauth authentication enabled the login will be like this: 
![captura de tela de 2018-04-04 09-23-13](https://user-images.githubusercontent.com/233643/38307407-0ca4f854-37ea-11e8-9917-13ebb39c0cb2.png)

And without the oauth authentication like this:
![captura de tela de 2018-04-04 09-23-24](https://user-images.githubusercontent.com/233643/38307424-1a58be2c-37ea-11e8-9163-d16e4339176d.png)

These changes will be available in the next verion in moodle.org, but you can download the code from here(github) and update your theme.

**Comment by Gorillab1scuit** [comment]
Thanks!  I'll give it a shot

~ Matt
347.416.NERD
get Gmail @ http://mail.google.com

**Comment by Gorillab1scuit** [comment]
So it worked... need to really limit the instructions as the boxes don't resize.  Also, I'm seeing the icons for the accounts not working anymore... is this related to the new theme?
![image](https://user-images.githubusercontent.com/36890827/38401304-eac76b9c-3922-11e8-94e7-501eddba08e9.png)

![image](https://user-images.githubusercontent.com/36890827/38401311-fd6b03da-3922-11e8-9e7d-6fc252c85a1e.png)
