### ISSUE TITLE
Mail template

### ISSUE THREAD

**Issue by jmd87fr** [willianmano/moodle-theme_moove#77]
Hi Willian

I would like to have the text in french Do you know how fix that ? where they are the strings ? Do you know the files ? 
I can change in admin>language> language customisazion but I don't know the name of files

Thanks

**Comment by willianmano** [comment]
@jmd87fr I don't know If you can do it when you're using the most recent code from the github. I think that the strings are mapped only when I put it in the moodle.org. The official channel to translate the moodle plugins strings is the AMOS https://lang.moodle.org/?lang=pt_br
