### ISSUE TITLE
border radius in login page

### ISSUE THREAD

**Issue by Razzo1987** [willianmano/moodle-theme_moove#79]
Hi,
I suggest to set a different border radius for instructions block on login when it used on small devices:
![login](https://user-images.githubusercontent.com/906604/38427793-80bc9fa4-39ba-11e8-8746-6ac82225781a.PNG)
ONLY ON SMALL AND XMALL:
border-top-right-radius: 10px;
border-bottom-left-radius: 0;

**Comment by willianmano** [comment]
@Razzo1987 Fixed.
