### ISSUE TITLE
Issue with Course view in version 2.3.0 (Coding error)

### ISSUE THREAD

**Issue by k-holland** [willianmano/moodle-theme_moove#83]
Hi there, just installed the latest Moove theme, version 2.3.0, added a course, and the URL /course/view.php?id=2 is giving the following error:

Coding error detected, it must be fixed by a programmer: page layout file [dirroot]/theme/moove/layout/course.php does not contain the main content placeholder, please include "<?php echo $OUTPUT->main_content() ?>" in theme layout file.

Thanks in advance, Karen

**Comment by willianmano** [comment]
I tested here and everything is ok. Which moodle version are you using?

**Comment by relecand** [comment]
Can't also reproduce.
