### ISSUE TITLE
Slider ovals are not aligned

### ISSUE THREAD

**Issue by epcotton** [willianmano/moodle-theme_moove#84]
![image](https://user-images.githubusercontent.com/38703311/39209066-b59fb8d4-47d2-11e8-8729-bd2b8dc69881.png)
The ovals for the slider look misaligned.

**Comment by willianmano** [comment]
@epcotton could you send me the images and texts used in the slide, or the link of your site with the slide?

**Comment by epcotton** [comment]
Sure...the image shows the ovals above, and you can see it in context on our dev server here: https://moodle-dev.learningally.org/
