### ISSUE TITLE
Duplicate home icons in left nav drawer

### ISSUE THREAD

**Issue by crhcdc** [willianmano/moodle-theme_moove#86]
When choosing the site home as the default home page for all users the Site Home and Dashboard icons are both a house but the Dashboard should be the speedometer icon.  It appears both are being assigned the data-type "home" rather than one being "myhome" as it is when the default order is used and the Dashboard element gets the "myhome" data-type.  It does sort them correctly by placing the Site Home link at the top and above the normally default Dashboard link, but the icons are incorrect.  If there is an easy way to fix this in the code files I'm willing to try anything.

It looks like this:
![image](https://user-images.githubusercontent.com/38916376/39528518-4c850f4a-4df2-11e8-8777-3efc32988f08.png)

Thank you!

**Comment by willianmano** [comment]
It is a Moodle issue. I already opened a thread in the tracker with the solution. You can help voting in the thread. https://tracker.moodle.org/browse/MDL-62345
