### ISSUE TITLE
Extending Moove

### ISSUE THREAD

**Issue by systemovich** [willianmano/moodle-theme_moove#91]
I followed the https://docs.moodle.org/dev/Creating_a_theme_based_on_boost tutorial. Instead of basing my custom theme on Boost, I based it on Moove. After the "Theme specific files" section, in the "Ready set go" section, the tutorial says that the theme is now ready to be installed. I installed the theme, and selected it as the theme for my Moodle instance (v3.5.0), but I get the following error:

> Sorry, the requested file could not be found

With debugging messages displayed, I also get this stack trace:

> Debug info: core/block
> Error code: filenotfound
> Stack trace:
> line 125 of /lib/classes/output/mustache_template_finder.php: moodle_exception thrown
> line 54 of /lib/classes/output/mustache_filesystem_loader.php: call to core\output\mustache_template_finder::get_template_filepath()
> line 99 of /lib/mustache/src/Mustache/Loader/FilesystemLoader.php: call to core\output\mustache_filesystem_loader->getFileName()
> line 82 of /lib/mustache/src/Mustache/Loader/FilesystemLoader.php: call to Mustache_Loader_FilesystemLoader->loadFile()
> line 657 of /lib/mustache/src/Mustache/Engine.php: call to Mustache_Loader_FilesystemLoader->load()
> line 170 of /lib/outputrenderers.php: call to Mustache_Engine->loadTemplate()
> line 350 of /theme/boost/classes/output/core_renderer.php: call to renderer_base->render_from_template()
> line 1768 of /lib/outputrenderers.php: call to theme_boost\output\core_renderer->block()
> line 3924 of /lib/outputrenderers.php: call to core_renderer->blocks_for_region()
> line 40 of /theme/moove/layout/columns2.php: call to core_renderer->blocks()
> line 1272 of /lib/outputrenderers.php: call to include()
> line 1202 of /lib/outputrenderers.php: call to core_renderer->render_page_layout()
> line 51 of /theme/index.php: call to core_renderer->header()

When I base my theme on Boost, it works properly. My theme can be found at https://github.com/systemovich/moodle-theme-custom. What is the minimum code I have to add to get it to work?

**Comment by Muneera-Salah** [comment]
Hi,,
 I faced same problem when I Try create custom theme based on  moove

Try this solution  
edit config.php

`$THEME->parents = ['moove','boost'];
`
and version.php

```
$plugin->dependencies = [
    'theme_boost' => 2017051500,
    'theme_moove' => 2018042000
];
```

**Comment by systemovich** [comment]
Thank you, @Muneera-Salah . I will try that.

**Comment by systemovich** [comment]
@Muneera-Salah, that worked. Thanks very much!
