### ISSUE TITLE
Bugs in 2.3.2

### ISSUE THREAD

**Issue by sean1746** [willianmano/moodle-theme_moove#93]
Thanks for the corrections following the last update. This is a great theme and I'm very grateful for all of your hard work!

I've spotted three small things in the 2.3.2 update:

- [x] The nav drawer does not display correctly on the reset password page
![screen shot 2018-06-09 at 17 05 33](https://user-images.githubusercontent.com/37707292/41193854-6f1dec58-6c0a-11e8-9d92-f9874e738966.png)

- [x] The homepage slider images no longer have an animation between slides. The text still animates, but the images do not.

- [x] The "View All Policies" page at /admin/tool/policy/viewall.php does not show the header, footer or navigation drawer.
![screen shot 2018-06-11 at 16 08 00](https://user-images.githubusercontent.com/37707292/41240189-d5e08ff8-6d91-11e8-8fa6-a9e70f28f6d9.png)

**Comment by willianmano** [comment]
@sean1746 Thanks again for your help. The last issue is a popup page, This is the desired behavior, I just removed the left margin.

**Comment by sean1746** [comment]
@willianmano thanks very much for your hard work maintaining this theme, it's excellent!
