### ISSUE TITLE
Issues in 2.3.3 version

### ISSUE THREAD

**Issue by adamslodki** [willianmano/moodle-theme_moove#95]
Hi,
I customized version 2.3.2 to my needs, but after today's update to 2.3.3 I can not set a static height: 300px in hidden navigation.

My custom CSS looks like this:

```
.text{
  font-size: 13px;
}

#nav-drawer {
  overflow: scroll;
  overflow-x: hidden;
  .list-group .list-group-item a {
    padding: .20rem .5rem;
  }
}

#nav-drawer.closed {
  overflow: visible;

  [data-key="mycourses"] {
    ul{
      margin-top: -18px;
    }

    #MyCourseList{
      overflow: scroll;
      overflow-x: hidden;
      height: 300px;
    }
  }
}
```

"MyCourseList" id is added by me to `<ul>` in _flat_navigation.mustache_.
This custom CSS works great in version 2.2.0 and 2.3.2.

Still the nav drawer does not display correctly on the reset password page.
I hide it with CSS:
`#page-login-forgot_password {
  #nav-drawer{
    display: none;
  }
}`

In version 2.3.2 an above there is no language menu on the top bar. I added  in _header.mustache_ to swow it.

```
<li class="nav-item">
  {{{ output.render_lang_menu }}}
</li>
```

**Comment by suser222** [comment]
The problem still persists when the menu is expanded. When the list of courses is long, they go outside the browser window.
![hiddent course list](https://user-images.githubusercontent.com/2067454/42036335-7645d8e4-7ae5-11e8-9c7d-3d2984c7c699.png)
