### ISSUE TITLE
Version 2.3.4

### ISSUE THREAD

**Issue by ghost** [willianmano/moodle-theme_moove#97]
Hi, thanks very much for the bug fixes this version I raised in an earlier issue.

There are still a couple of issues related to the enhancements to the nav drawer: 

- [ ] The 'My Courses' menu still appears to change position on the Course page, and now seems to display below the site admin link in the nav drawer (when logged in as Admin). For consistency between pages, I think it should display directly below the calendar? The position is correct for Teacher users. See screenshots.
Screenshot from Dashboard with My Courses link in the correct position:
![screen shot 2018-06-27 at 17 05 24](https://user-images.githubusercontent.com/37707292/41986138-2a2f6ea6-7a2d-11e8-85a1-f6a8e765d8de.png)
Screenshot showing icon in the wrong position on the course page:
![screen shot 2018-06-27 at 17 05 35](https://user-images.githubusercontent.com/37707292/41986151-31d2ce6e-7a2d-11e8-8082-136808179c81.png)

- [ ] When logged in as a student user, the nav drawer icons display in a different order. The course sections doesn't appear at the top above the gradebook as it does when logged in as an admin user and teacher user.
![screen shot 2018-06-27 at 17 16 14](https://user-images.githubusercontent.com/37707292/41986597-80b50cda-7a2e-11e8-9c68-85a1ec4d2fe4.png)

- [ ] The course sections links do not actually work! Clicking them simply refreshes the current page.

- [ ] The front-page counter for Activities also counts labels that are added to courses. This produces an inaccurate activity figure.

Thanks again for your ongoing hard work with this theme, it's excellent!

**Comment by giselebrugger** [comment]
Icons dashbord and home differents in versions

Moove : 2.3.0
2018042100

![2_3_0](https://user-images.githubusercontent.com/5620195/42284167-0a405b1e-7f82-11e8-8af2-f05692ce732a.png)


2.3.4
2018062000
![2_3_4](https://user-images.githubusercontent.com/5620195/42284169-0ff25b0c-7f82-11e8-93a4-9c899e82a90d.png)

**Comment by michael-LTS1** [comment]
> Hi, thanks very much for the bug fixes this version I raised in an earlier issue.
> 
> There are still a couple of issues related to the enhancements to the nav drawer:
> 
> * [ ]  The 'My Courses' menu still appears to change position on the Course page, and now seems to display below the site admin link in the nav drawer (when logged in as Admin). For consistency between pages, I think it should display directly below the calendar? The position is correct for Teacher users. See screenshots.
>   Screenshot from Dashboard with My Courses link in the correct position:
>   ![screen shot 2018-06-27 at 17 05 24](https://user-images.githubusercontent.com/37707292/41986138-2a2f6ea6-7a2d-11e8-85a1-f6a8e765d8de.png)
>   Screenshot showing icon in the wrong position on the course page:
>   ![screen shot 2018-06-27 at 17 05 35](https://user-images.githubusercontent.com/37707292/41986151-31d2ce6e-7a2d-11e8-8082-136808179c81.png)
> * [ ]  When logged in as a student user, the nav drawer icons display in a different order. The course sections doesn't appear at the top above the gradebook as it does when logged in as an admin user and teacher user.
>   ![screen shot 2018-06-27 at 17 16 14](https://user-images.githubusercontent.com/37707292/41986597-80b50cda-7a2e-11e8-9c68-85a1ec4d2fe4.png)
> * [ ]  The course sections links do not actually work! Clicking them simply refreshes the current page.
> * [ ]  The front-page counter for Activities also counts labels that are added to courses. This produces an inaccurate activity figure.
> 
> Thanks again for your ongoing hard work with this theme, it's excellent!

Also having the same issue showing on Moodle 3.5.2 and Moove 2.3.8.  Mycourses link appears in a different spot within a course page menu compared to on the Dashboard.  Tested on Boost and not getting same issues.

![moove-course](https://user-images.githubusercontent.com/33850075/49056080-2e1fb180-f24e-11e8-9f4f-f91ff1783d1f.PNG)
![moove-dash](https://user-images.githubusercontent.com/33850075/49056082-2e1fb180-f24e-11e8-8405-6474eca27138.PNG)
