### ISSUE TITLE
I loose first menu line

### ISSUE THREAD

**Issue by jmd87fr** [willianmano/moodle-theme_moove#98]
Hi Willian
Maybe I mad a mistake but I have no more 
![image](https://user-images.githubusercontent.com/5038301/42026867-816bb0d0-7ac8-11e8-9988-eada7aefee7d.png)
Need your help :-)

**Comment by willianmano** [comment]
Loose first menu line? Could you explain it better?

**Comment by jmd87fr** [comment]
I give you a screenhot (from your theme) I loose this part of the theme (language menu / message / notification / avatar / ...
